<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:os="http://www.optimizationservices.org" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.optimizationservices.org">
	<!--OScL.wsdl: version - 1.0.0 -->
	<message name="callRequest">
		<part name="osslInput" type="xsd:string"/>
		<part name="osol" type="xsd:string"/>
	</message>
	<message name="callResponse">
		<part name="osslOutput" type="xsd:string"/>
	</message>
	<portType name="OSSimulationService">
		<operation name="call" parameterOrder="osslInput osol">
			<input name="callRequest" message="os:callRequest"/>
			<output name="callResponse" message="os:callResponse"/>
		</operation>
	</portType>
	<binding name="OSSimulationServiceSoapBinding" type="os:OSSimulationService">
		<wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="call">
			<wsdlsoap:operation soapAction="OSSimulationService#call"/>
			<input>
				<wsdlsoap:body use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://www.optimizationservices.org"/>
			</input>
			<output>
				<wsdlsoap:body use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://www.optimizationservices.org"/>
			</output>
		</operation>
	</binding>
	<service name="OSSimulationService">
		<!--All port locations, i.e. service URI addresses, are to be found dynamically in the OS registry and NOT to be hard coded below in <port><port>-->
		<!-- The following is just a hard coded example-->
		<port name="OSSimulationService" binding="os:OSSimulationServiceSoapBinding">
			<wsdlsoap:address location="http://www.optimizationservices.org/os/SampleSimulationService.jws"/>
		</port>
	</service>
</wsdl:definitions>
