/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bin_0005corg_0005coptimizationservices_0005cossolver_0005csolver_0005cKnitroSolver */

#ifndef _Included_bin_0005corg_0005coptimizationservices_0005cossolver_0005csolver_0005cKnitroSolver
#define _Included_bin_0005corg_0005coptimizationservices_0005cossolver_0005csolver_0005cKnitroSolver
#ifdef __cplusplus
extern "C" {
#endif
#undef bin_0005corg_0005coptimizationservices_0005cossolver_0005csolver_0005cKnitroSolver_KTR_INFBOUND
#define bin_0005corg_0005coptimizationservices_0005cossolver_0005csolver_0005cKnitroSolver_KTR_INFBOUND InfD
/*
 * Class:     bin_0005corg_0005coptimizationservices_0005cossolver_0005csolver_0005cKnitroSolver
 * Method:    nativeMain
 * Signature: (IIIII[D[D[D[D[I[D[I[I)V
 */
JNIEXPORT void JNICALL Java_bin_0005corg_0005coptimizationservices_0005cossolver_0005csolver_0005cKnitroSolver_nativeMain
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jdoubleArray, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
