/* A Bison parser, made by GNU Bison 2.3.  */

/* Skeleton interface for Bison's Yacc-like parsers in C

   Copyright (C) 1984, 1989, 1990, 2000, 2001, 2002, 2003, 2004, 2005, 2006
   Free Software Foundation, Inc.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin Street, Fifth Floor,
   Boston, MA 02110-1301, USA.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.

   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

/* Tokens.  */
#ifndef YYTOKENTYPE
# define YYTOKENTYPE
/* Put the tokens into the symbol table, so that GDB and other debuggers
   know about them.  */
enum yytokentype
{
    ATTRIBUTETEXT = 258,
    ELEMENTTEXT = 259,
    ITEMTEXT = 260,
    INTEGER = 261,
    DOUBLE = 262,
    QUOTE = 263,
    TWOQUOTES = 264,
    GREATERTHAN = 265,
    ENDOFELEMENT = 266,
    OSRLSTART = 267,
    OSRLSTARTEMPTY = 268,
    OSRLATTRIBUTETEXT = 269,
    OSRLEND = 270,
    NUMBEROFCONATT = 271,
    NUMBEROFCONSTRAINTSATT = 272,
    NUMBEROFELATT = 273,
    NUMBEROFENUMERATIONSATT = 274,
    NUMBEROFIDXATT = 275,
    NUMBEROFITEMSATT = 276,
    NUMBEROFOBJATT = 277,
    NUMBEROFOBJECTIVESATT = 278,
    NUMBEROFOTHERCONSTRAINTRESULTSATT = 279,
    NUMBEROFOTHEROBJECTIVERESULTSATT = 280,
    NUMBEROFOTHERRESULTSATT = 281,
    NUMBEROFOTHERSOLUTIONRESULTSATT = 282,
    NUMBEROFOTHERVARIABLERESULTSATT = 283,
    NUMBEROFSOLUTIONSATT = 284,
    NUMBEROFSOLVEROUTPUTSATT = 285,
    NUMBEROFSUBSTATUSESATT = 286,
    NUMBEROFTIMESATT = 287,
    NUMBEROFVARATT = 288,
    NUMBEROFVARIABLESATT = 289,
    NUMBEROFVARIDXATT = 290,
    TARGETOBJECTIVEIDXATT = 291,
    IDXATT = 292,
    INCRATT = 293,
    MULTATT = 294,
    SIZEOFATT = 295,
    CATEGORYATT = 296,
    EMPTYCATEGORYATT = 297,
    DESCRIPTIONATT = 298,
    EMPTYDESCRIPTIONATT = 299,
    NAMEATT = 300,
    EMPTYNAMEATT = 301,
    TYPEATT = 302,
    EMPTYTYPEATT = 303,
    UNITATT = 304,
    EMPTYUNITATT = 305,
    VALUEATT = 306,
    EMPTYVALUEATT = 307,
    WEIGHTEDOBJECTIVESATT = 308,
    EMPTYWEIGHTEDOBJECTIVESATT = 309,
    TARGETOBJECTIVENAMEATT = 310,
    EMPTYTARGETOBJECTIVENAMEATT = 311,
    HEADERSTART = 312,
    HEADEREND = 313,
    GENERALSTART = 314,
    GENERALEND = 315,
    SYSTEMSTART = 316,
    SYSTEMEND = 317,
    SERVICESTART = 318,
    SERVICEEND = 319,
    JOBSTART = 320,
    JOBEND = 321,
    OPTIMIZATIONSTART = 322,
    OPTIMIZATIONEND = 323,
    ITEMSTART = 324,
    ITEMEND = 325,
    ITEMSTARTANDEND = 326,
    ITEMEMPTY = 327,
    FILENAMESTART = 328,
    FILENAMEEND = 329,
    FILENAMEEMPTY = 330,
    FILENAMESTARTANDEND = 331,
    FILESOURCESTART = 332,
    FILESOURCEEND = 333,
    FILESOURCEEMPTY = 334,
    FILESOURCESTARTANDEND = 335,
    FILEDESCRIPTIONSTART = 336,
    FILEDESCRIPTIONEND = 337,
    FILEDESCRIPTIONEMPTY = 338,
    FILEDESCRIPTIONSTARTANDEND = 339,
    FILECREATORSTART = 340,
    FILECREATOREND = 341,
    FILECREATOREMPTY = 342,
    FILECREATORSTARTANDEND = 343,
    FILELICENCESTART = 344,
    FILELICENCEEND = 345,
    FILELICENCEEMPTY = 346,
    FILELICENCESTARTANDEND = 347,
    ACTUALSTARTTIMESTART = 348,
    ACTUALSTARTTIMEEND = 349,
    ATLOWERSTART = 350,
    ATLOWEREND = 351,
    ATUPPERSTART = 352,
    ATUPPEREND = 353,
    AVAILABLECPUNUMBERSTART = 354,
    AVAILABLECPUNUMBEREND = 355,
    AVAILABLECPUSPEEDSTART = 356,
    AVAILABLECPUSPEEDEND = 357,
    AVAILABLEDISKSPACESTART = 358,
    AVAILABLEDISKSPACEEND = 359,
    AVAILABLEMEMORYSTART = 360,
    AVAILABLEMEMORYEND = 361,
    BASE64START = 362,
    BASE64END = 363,
    BASICSTART = 364,
    BASICEND = 365,
    BASISSTATUSSTART = 366,
    BASISSTATUSEND = 367,
    BASSTATUSSTART = 368,
    BASSTATUSEND = 369,
    CONSTART = 370,
    CONEND = 371,
    CONSTRAINTSSTART = 372,
    CONSTRAINTSEND = 373,
    CURRENTJOBCOUNTSTART = 374,
    CURRENTJOBCOUNTEND = 375,
    CURRENTSTATESTART = 376,
    CURRENTSTATEEND = 377,
    DUALVALUESSTART = 378,
    DUALVALUESEND = 379,
    ELSTART = 380,
    ELEND = 381,
    ENUMERATIONSTART = 382,
    ENUMERATIONEND = 383,
    ENDTIMESTART = 384,
    ENDTIMEEND = 385,
    GENERALSTATUSSTART = 386,
    GENERALSTATUSEND = 387,
    GENERALSUBSTATUSSTART = 388,
    GENERALSUBSTATUSEND = 389,
    IDXSTART = 390,
    IDXEND = 391,
    INSTANCENAMESTART = 392,
    INSTANCENAMEEND = 393,
    ISFREESTART = 394,
    ISFREEEND = 395,
    JOBIDSTART = 396,
    JOBIDEND = 397,
    MESSAGESTART = 398,
    MESSAGEEND = 399,
    OBJSTART = 400,
    OBJEND = 401,
    OBJECTIVESSTART = 402,
    OBJECTIVESEND = 403,
    OPTIMIZATIONSOLUTIONSTATUSSTART = 404,
    OPTIMIZATIONSOLUTIONSTATUSEND = 405,
    OPTIMIZATIONSOLUTIONSUBSTATUSSTART = 406,
    OPTIMIZATIONSOLUTIONSUBSTATUSEND = 407,
    OTHERSTART = 408,
    OTHEREND = 409,
    OTHERRESULTSSTART = 410,
    OTHERRESULTSEND = 411,
    OTHERSOLUTIONRESULTSTART = 412,
    OTHERSOLUTIONRESULTEND = 413,
    OTHERSOLUTIONRESULTSSTART = 414,
    OTHERSOLUTIONRESULTSEND = 415,
    OTHERSOLVEROUTPUTSTART = 416,
    OTHERSOLVEROUTPUTEND = 417,
    SCHEDULEDSTARTTIMESTART = 418,
    SCHEDULEDSTARTTIMEEND = 419,
    SERVICENAMESTART = 420,
    SERVICENAMEEND = 421,
    SERVICEURISTART = 422,
    SERVICEURIEND = 423,
    SERVICEUTILIZATIONSTART = 424,
    SERVICEUTILIZATIONEND = 425,
    SOLUTIONSTART = 426,
    SOLUTIONEND = 427,
    SOLVERINVOKEDSTART = 428,
    SOLVERINVOKEDEND = 429,
    SOLVEROUTPUTSTART = 430,
    SOLVEROUTPUTEND = 431,
    STATUSSTART = 432,
    STATUSEND = 433,
    SUBMITTIMESTART = 434,
    SUBMITTIMEEND = 435,
    SUBSTATUSSTART = 436,
    SUBSTATUSEND = 437,
    SUPERBASICSTART = 438,
    SUPERBASICEND = 439,
    SYSTEMINFORMATIONSTART = 440,
    SYSTEMINFORMATIONEND = 441,
    TIMESTART = 442,
    TIMEEND = 443,
    TIMESERVICESTARTEDSTART = 444,
    TIMESERVICESTARTEDEND = 445,
    TIMESTAMPSTART = 446,
    TIMESTAMPEND = 447,
    TIMINGINFORMATIONSTART = 448,
    TIMINGINFORMATIONEND = 449,
    TOTALJOBSSOFARSTART = 450,
    TOTALJOBSSOFAREND = 451,
    UNKNOWNSTART = 452,
    UNKNOWNEND = 453,
    USEDCPUNUMBERSTART = 454,
    USEDCPUNUMBEREND = 455,
    USEDCPUSPEEDSTART = 456,
    USEDCPUSPEEDEND = 457,
    USEDDISKSPACESTART = 458,
    USEDDISKSPACEEND = 459,
    USEDMEMORYSTART = 460,
    USEDMEMORYEND = 461,
    VALUESSTART = 462,
    VALUESEND = 463,
    VALUESSTRINGSTART = 464,
    VALUESSTRINGEND = 465,
    VARSTART = 466,
    VAREND = 467,
    VARIABLESSTART = 468,
    VARIABLESEND = 469,
    VARIDXSTART = 470,
    VARIDXEND = 471,
    DUMMY = 472
};
#endif
/* Tokens.  */
#define ATTRIBUTETEXT 258
#define ELEMENTTEXT 259
#define ITEMTEXT 260
#define INTEGER 261
#define DOUBLE 262
#define QUOTE 263
#define TWOQUOTES 264
#define GREATERTHAN 265
#define ENDOFELEMENT 266
#define OSRLSTART 267
#define OSRLSTARTEMPTY 268
#define OSRLATTRIBUTETEXT 269
#define OSRLEND 270
#define NUMBEROFCONATT 271
#define NUMBEROFCONSTRAINTSATT 272
#define NUMBEROFELATT 273
#define NUMBEROFENUMERATIONSATT 274
#define NUMBEROFIDXATT 275
#define NUMBEROFITEMSATT 276
#define NUMBEROFOBJATT 277
#define NUMBEROFOBJECTIVESATT 278
#define NUMBEROFOTHERCONSTRAINTRESULTSATT 279
#define NUMBEROFOTHEROBJECTIVERESULTSATT 280
#define NUMBEROFOTHERRESULTSATT 281
#define NUMBEROFOTHERSOLUTIONRESULTSATT 282
#define NUMBEROFOTHERVARIABLERESULTSATT 283
#define NUMBEROFSOLUTIONSATT 284
#define NUMBEROFSOLVEROUTPUTSATT 285
#define NUMBEROFSUBSTATUSESATT 286
#define NUMBEROFTIMESATT 287
#define NUMBEROFVARATT 288
#define NUMBEROFVARIABLESATT 289
#define NUMBEROFVARIDXATT 290
#define TARGETOBJECTIVEIDXATT 291
#define IDXATT 292
#define INCRATT 293
#define MULTATT 294
#define SIZEOFATT 295
#define CATEGORYATT 296
#define EMPTYCATEGORYATT 297
#define DESCRIPTIONATT 298
#define EMPTYDESCRIPTIONATT 299
#define NAMEATT 300
#define EMPTYNAMEATT 301
#define TYPEATT 302
#define EMPTYTYPEATT 303
#define UNITATT 304
#define EMPTYUNITATT 305
#define VALUEATT 306
#define EMPTYVALUEATT 307
#define WEIGHTEDOBJECTIVESATT 308
#define EMPTYWEIGHTEDOBJECTIVESATT 309
#define TARGETOBJECTIVENAMEATT 310
#define EMPTYTARGETOBJECTIVENAMEATT 311
#define HEADERSTART 312
#define HEADEREND 313
#define GENERALSTART 314
#define GENERALEND 315
#define SYSTEMSTART 316
#define SYSTEMEND 317
#define SERVICESTART 318
#define SERVICEEND 319
#define JOBSTART 320
#define JOBEND 321
#define OPTIMIZATIONSTART 322
#define OPTIMIZATIONEND 323
#define ITEMSTART 324
#define ITEMEND 325
#define ITEMSTARTANDEND 326
#define ITEMEMPTY 327
#define FILENAMESTART 328
#define FILENAMEEND 329
#define FILENAMEEMPTY 330
#define FILENAMESTARTANDEND 331
#define FILESOURCESTART 332
#define FILESOURCEEND 333
#define FILESOURCEEMPTY 334
#define FILESOURCESTARTANDEND 335
#define FILEDESCRIPTIONSTART 336
#define FILEDESCRIPTIONEND 337
#define FILEDESCRIPTIONEMPTY 338
#define FILEDESCRIPTIONSTARTANDEND 339
#define FILECREATORSTART 340
#define FILECREATOREND 341
#define FILECREATOREMPTY 342
#define FILECREATORSTARTANDEND 343
#define FILELICENCESTART 344
#define FILELICENCEEND 345
#define FILELICENCEEMPTY 346
#define FILELICENCESTARTANDEND 347
#define ACTUALSTARTTIMESTART 348
#define ACTUALSTARTTIMEEND 349
#define ATLOWERSTART 350
#define ATLOWEREND 351
#define ATUPPERSTART 352
#define ATUPPEREND 353
#define AVAILABLECPUNUMBERSTART 354
#define AVAILABLECPUNUMBEREND 355
#define AVAILABLECPUSPEEDSTART 356
#define AVAILABLECPUSPEEDEND 357
#define AVAILABLEDISKSPACESTART 358
#define AVAILABLEDISKSPACEEND 359
#define AVAILABLEMEMORYSTART 360
#define AVAILABLEMEMORYEND 361
#define BASE64START 362
#define BASE64END 363
#define BASICSTART 364
#define BASICEND 365
#define BASISSTATUSSTART 366
#define BASISSTATUSEND 367
#define BASSTATUSSTART 368
#define BASSTATUSEND 369
#define CONSTART 370
#define CONEND 371
#define CONSTRAINTSSTART 372
#define CONSTRAINTSEND 373
#define CURRENTJOBCOUNTSTART 374
#define CURRENTJOBCOUNTEND 375
#define CURRENTSTATESTART 376
#define CURRENTSTATEEND 377
#define DUALVALUESSTART 378
#define DUALVALUESEND 379
#define ELSTART 380
#define ELEND 381
#define ENUMERATIONSTART 382
#define ENUMERATIONEND 383
#define ENDTIMESTART 384
#define ENDTIMEEND 385
#define GENERALSTATUSSTART 386
#define GENERALSTATUSEND 387
#define GENERALSUBSTATUSSTART 388
#define GENERALSUBSTATUSEND 389
#define IDXSTART 390
#define IDXEND 391
#define INSTANCENAMESTART 392
#define INSTANCENAMEEND 393
#define ISFREESTART 394
#define ISFREEEND 395
#define JOBIDSTART 396
#define JOBIDEND 397
#define MESSAGESTART 398
#define MESSAGEEND 399
#define OBJSTART 400
#define OBJEND 401
#define OBJECTIVESSTART 402
#define OBJECTIVESEND 403
#define OPTIMIZATIONSOLUTIONSTATUSSTART 404
#define OPTIMIZATIONSOLUTIONSTATUSEND 405
#define OPTIMIZATIONSOLUTIONSUBSTATUSSTART 406
#define OPTIMIZATIONSOLUTIONSUBSTATUSEND 407
#define OTHERSTART 408
#define OTHEREND 409
#define OTHERRESULTSSTART 410
#define OTHERRESULTSEND 411
#define OTHERSOLUTIONRESULTSTART 412
#define OTHERSOLUTIONRESULTEND 413
#define OTHERSOLUTIONRESULTSSTART 414
#define OTHERSOLUTIONRESULTSEND 415
#define OTHERSOLVEROUTPUTSTART 416
#define OTHERSOLVEROUTPUTEND 417
#define SCHEDULEDSTARTTIMESTART 418
#define SCHEDULEDSTARTTIMEEND 419
#define SERVICENAMESTART 420
#define SERVICENAMEEND 421
#define SERVICEURISTART 422
#define SERVICEURIEND 423
#define SERVICEUTILIZATIONSTART 424
#define SERVICEUTILIZATIONEND 425
#define SOLUTIONSTART 426
#define SOLUTIONEND 427
#define SOLVERINVOKEDSTART 428
#define SOLVERINVOKEDEND 429
#define SOLVEROUTPUTSTART 430
#define SOLVEROUTPUTEND 431
#define STATUSSTART 432
#define STATUSEND 433
#define SUBMITTIMESTART 434
#define SUBMITTIMEEND 435
#define SUBSTATUSSTART 436
#define SUBSTATUSEND 437
#define SUPERBASICSTART 438
#define SUPERBASICEND 439
#define SYSTEMINFORMATIONSTART 440
#define SYSTEMINFORMATIONEND 441
#define TIMESTART 442
#define TIMEEND 443
#define TIMESERVICESTARTEDSTART 444
#define TIMESERVICESTARTEDEND 445
#define TIMESTAMPSTART 446
#define TIMESTAMPEND 447
#define TIMINGINFORMATIONSTART 448
#define TIMINGINFORMATIONEND 449
#define TOTALJOBSSOFARSTART 450
#define TOTALJOBSSOFAREND 451
#define UNKNOWNSTART 452
#define UNKNOWNEND 453
#define USEDCPUNUMBERSTART 454
#define USEDCPUNUMBEREND 455
#define USEDCPUSPEEDSTART 456
#define USEDCPUSPEEDEND 457
#define USEDDISKSPACESTART 458
#define USEDDISKSPACEEND 459
#define USEDMEMORYSTART 460
#define USEDMEMORYEND 461
#define VALUESSTART 462
#define VALUESEND 463
#define VALUESSTRINGSTART 464
#define VALUESSTRINGEND 465
#define VARSTART 466
#define VAREND 467
#define VARIABLESSTART 468
#define VARIABLESEND 469
#define VARIDXSTART 470
#define VARIDXEND 471
#define DUMMY 472




#if ! defined YYSTYPE && ! defined YYSTYPE_IS_DECLARED
typedef union YYSTYPE

{
    double dval;
    int ival;
    char* sval;
}
/* Line 1529 of yacc.c.  */

YYSTYPE;
# define yystype YYSTYPE /* obsolescent; will be withdrawn */
# define YYSTYPE_IS_DECLARED 1
# define YYSTYPE_IS_TRIVIAL 1
#endif



#if ! defined YYLTYPE && ! defined YYLTYPE_IS_DECLARED
typedef struct YYLTYPE
{
    int first_line;
    int first_column;
    int last_line;
    int last_column;
} YYLTYPE;
# define yyltype YYLTYPE /* obsolescent; will be withdrawn */
# define YYLTYPE_IS_DECLARED 1
# define YYLTYPE_IS_TRIVIAL 1
#endif


