/* A Bison parser, made by GNU Bison 2.3.  */

/* Skeleton interface for Bison's Yacc-like parsers in C

   Copyright (C) 1984, 1989, 1990, 2000, 2001, 2002, 2003, 2004, 2005, 2006
   Free Software Foundation, Inc.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin Street, Fifth Floor,
   Boston, MA 02110-1301, USA.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.

   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

/* Tokens.  */
#ifndef YYTOKENTYPE
# define YYTOKENTYPE
   /* Put the tokens into the symbol table, so that GDB and other debuggers
      know about them.  */
   enum yytokentype {
     ATTRIBUTETEXT = 258,
     ELEMENTTEXT = 259,
     ITEMTEXT = 260,
     INTEGER = 261,
     DOUBLE = 262,
     QUOTE = 263,
     TWOQUOTES = 264,
     GREATERTHAN = 265,
     ENDOFELEMENT = 266,
     OSOLSTART = 267,
     OSOLSTARTEMPTY = 268,
     OSOLATTRIBUTETEXT = 269,
     OSOLEND = 270,
     NUMBEROFOTHEROPTIONSATT = 271,
     NUMBEROFENUMERATIONSATT = 272,
     NUMBEROFJOBIDSATT = 273,
     NUMBEROFPATHSATT = 274,
     NUMBEROFPATHPAIRSATT = 275,
     FROMATT = 276,
     TOATT = 277,
     MAKECOPYATT = 278,
     CATEGORYATT = 279,
     TYPEATT = 280,
     GROUPWEIGHTATT = 281,
     NUMBEROFPROCESSESATT = 282,
     NUMBEROFSOLVEROPTIONSATT = 283,
     NUMBEROFSOSATT = 284,
     NUMBEROFVARIABLESATT = 285,
     NUMBEROFOBJECTIVESATT = 286,
     NUMBEROFCONSTRAINTSATT = 287,
     NUMBEROFOTHERVARIABLEOPTIONSATT = 288,
     NUMBEROFOTHEROBJECTIVEOPTIONSATT = 289,
     NUMBEROFOTHERCONSTRAINTOPTIONSATT = 290,
     NUMBEROFITEMSATT = 291,
     NUMBEROFVARATT = 292,
     NUMBEROFOBJATT = 293,
     NUMBEROFCONATT = 294,
     NUMBEROFELATT = 295,
     NAMEATT = 296,
     IDXATT = 297,
     SOSIDXATT = 298,
     VALUEATT = 299,
     UNITATT = 300,
     DESCRIPTIONATT = 301,
     EMPTYTYPEATT = 302,
     EMPTYNAMEATT = 303,
     EMPTYCATEGORYATT = 304,
     EMPTYDESCRIPTIONATT = 305,
     EMPTYUNITATT = 306,
     EMPTYVALUEATT = 307,
     EMPTYLBVALUEATT = 308,
     EMPTYUBVALUEATT = 309,
     LBVALUEATT = 310,
     UBVALUEATT = 311,
     EMPTYLBDUALVALUEATT = 312,
     EMPTYUBDUALVALUEATT = 313,
     LBDUALVALUEATT = 314,
     UBDUALVALUEATT = 315,
     SOLVERATT = 316,
     EMPTYSOLVERATT = 317,
     WEIGHTATT = 318,
     EMPTYWEIGHTATT = 319,
     TRANSPORTTYPEATT = 320,
     LOCATIONTYPEATT = 321,
     GENERALSTART = 322,
     GENERALEND = 323,
     SYSTEMSTART = 324,
     SYSTEMEND = 325,
     SERVICESTART = 326,
     SERVICEEND = 327,
     JOBSTART = 328,
     JOBEND = 329,
     OPTIMIZATIONSTART = 330,
     OPTIMIZATIONEND = 331,
     SERVICEURISTART = 332,
     SERVICEURIEND = 333,
     SERVICENAMESTART = 334,
     SERVICENAMEEND = 335,
     INSTANCENAMESTART = 336,
     INSTANCENAMEEND = 337,
     INSTANCELOCATIONSTART = 338,
     INSTANCELOCATIONEND = 339,
     JOBIDSTART = 340,
     JOBIDEND = 341,
     SOLVERTOINVOKESTART = 342,
     SOLVERTOINVOKEEND = 343,
     LICENSESTART = 344,
     LICENSEEND = 345,
     USERNAMESTART = 346,
     USERNAMEEND = 347,
     PASSWORDSTART = 348,
     PASSWORDEND = 349,
     CONTACTSTART = 350,
     CONTACTEND = 351,
     OTHEROPTIONSSTART = 352,
     OTHEROPTIONSEND = 353,
     OTHERSTART = 354,
     OTHEREND = 355,
     MINDISKSPACESTART = 356,
     MINDISKSPACEEND = 357,
     MINMEMORYSTART = 358,
     MINMEMORYEND = 359,
     MINCPUSPEEDSTART = 360,
     MINCPUSPEEDEND = 361,
     MINCPUNUMBERSTART = 362,
     MINCPUNUMBEREND = 363,
     SERVICETYPESTART = 364,
     SERVICETYPEEND = 365,
     MAXTIMESTART = 366,
     MAXTIMEEND = 367,
     REQUESTEDSTARTTIMESTART = 368,
     REQUESTEDSTARTTIMEEND = 369,
     DEPENDENCIESSTART = 370,
     DEPENDENCIESEND = 371,
     REQUIREDDIRECTORIESSTART = 372,
     REQUIREDDIRECTORIESEND = 373,
     REQUIREDFILESSTART = 374,
     REQUIREDFILESEND = 375,
     PATHSTART = 376,
     PATHEND = 377,
     PATHPAIRSTART = 378,
     PATHPAIREND = 379,
     DIRECTORIESTOMAKESTART = 380,
     DIRECTORIESTOMAKEEND = 381,
     FILESTOMAKESTART = 382,
     FILESTOMAKEEND = 383,
     DIRECTORIESTODELETESTART = 384,
     DIRECTORIESTODELETEEND = 385,
     FILESTODELETESTART = 386,
     FILESTODELETEEND = 387,
     INPUTDIRECTORIESTOMOVESTART = 388,
     INPUTDIRECTORIESTOMOVEEND = 389,
     INPUTFILESTOMOVESTART = 390,
     INPUTFILESTOMOVEEND = 391,
     OUTPUTDIRECTORIESTOMOVESTART = 392,
     OUTPUTDIRECTORIESTOMOVEEND = 393,
     OUTPUTFILESTOMOVESTART = 394,
     OUTPUTFILESTOMOVEEND = 395,
     PROCESSESTOKILLSTART = 396,
     PROCESSESTOKILLEND = 397,
     PROCESSSTART = 398,
     PROCESSEND = 399,
     VARIABLESSTART = 400,
     VARIABLESEND = 401,
     INITIALVARIABLEVALUESSTART = 402,
     INITIALVARIABLEVALUESEND = 403,
     VARSTART = 404,
     VAREND = 405,
     INITIALVARIABLEVALUESSTRINGSTART = 406,
     INITIALVARIABLEVALUESSTRINGEND = 407,
     INITIALBASISSTATUSSTART = 408,
     INITIALBASISSTATUSEND = 409,
     BASICSTART = 410,
     BASICEND = 411,
     ATUPPERSTART = 412,
     ATUPPEREND = 413,
     ATLOWERSTART = 414,
     ATLOWEREND = 415,
     SUPERBASICSTART = 416,
     SUPERBASICEND = 417,
     ISFREESTART = 418,
     ISFREEEND = 419,
     UNKNOWNSTART = 420,
     UNKNOWNEND = 421,
     INTEGERVARIABLEBRANCHINGWEIGHTSSTART = 422,
     INTEGERVARIABLEBRANCHINGWEIGHTSEND = 423,
     SOSVARIABLEBRANCHINGWEIGHTSSTART = 424,
     SOSVARIABLEBRANCHINGWEIGHTSEND = 425,
     SOSSTART = 426,
     SOSEND = 427,
     OBJECTIVESSTART = 428,
     OBJECTIVESEND = 429,
     INITIALOBJECTIVEVALUESSTART = 430,
     INITIALOBJECTIVEVALUESEND = 431,
     OBJSTART = 432,
     OBJEND = 433,
     INITIALOBJECTIVEBOUNDSSTART = 434,
     INITIALOBJECTIVEBOUNDSEND = 435,
     CONSTRAINTSSTART = 436,
     CONSTRAINTSEND = 437,
     INITIALCONSTRAINTVALUESSTART = 438,
     INITIALCONSTRAINTVALUESEND = 439,
     CONSTART = 440,
     CONEND = 441,
     INITIALDUALVALUESSTART = 442,
     INITIALDUALVALUESEND = 443,
     SOLVEROPTIONSSTART = 444,
     SOLVEROPTIONSEND = 445,
     SOLVEROPTIONSTART = 446,
     SOLVEROPTIONEND = 447,
     ENUMERATIONSTART = 448,
     ENUMERATIONEND = 449,
     ITEMEMPTY = 450,
     ITEMSTART = 451,
     ITEMEND = 452,
     ITEMSTARTANDEND = 453,
     BASE64START = 454,
     BASE64END = 455,
     INCRATT = 456,
     MULTATT = 457,
     SIZEOFATT = 458,
     ELSTART = 459,
     ELEND = 460,
     DUMMY = 461
   };
#endif
/* Tokens.  */
#define ATTRIBUTETEXT 258
#define ELEMENTTEXT 259
#define ITEMTEXT 260
#define INTEGER 261
#define DOUBLE 262
#define QUOTE 263
#define TWOQUOTES 264
#define GREATERTHAN 265
#define ENDOFELEMENT 266
#define OSOLSTART 267
#define OSOLSTARTEMPTY 268
#define OSOLATTRIBUTETEXT 269
#define OSOLEND 270
#define NUMBEROFOTHEROPTIONSATT 271
#define NUMBEROFENUMERATIONSATT 272
#define NUMBEROFJOBIDSATT 273
#define NUMBEROFPATHSATT 274
#define NUMBEROFPATHPAIRSATT 275
#define FROMATT 276
#define TOATT 277
#define MAKECOPYATT 278
#define CATEGORYATT 279
#define TYPEATT 280
#define GROUPWEIGHTATT 281
#define NUMBEROFPROCESSESATT 282
#define NUMBEROFSOLVEROPTIONSATT 283
#define NUMBEROFSOSATT 284
#define NUMBEROFVARIABLESATT 285
#define NUMBEROFOBJECTIVESATT 286
#define NUMBEROFCONSTRAINTSATT 287
#define NUMBEROFOTHERVARIABLEOPTIONSATT 288
#define NUMBEROFOTHEROBJECTIVEOPTIONSATT 289
#define NUMBEROFOTHERCONSTRAINTOPTIONSATT 290
#define NUMBEROFITEMSATT 291
#define NUMBEROFVARATT 292
#define NUMBEROFOBJATT 293
#define NUMBEROFCONATT 294
#define NUMBEROFELATT 295
#define NAMEATT 296
#define IDXATT 297
#define SOSIDXATT 298
#define VALUEATT 299
#define UNITATT 300
#define DESCRIPTIONATT 301
#define EMPTYTYPEATT 302
#define EMPTYNAMEATT 303
#define EMPTYCATEGORYATT 304
#define EMPTYDESCRIPTIONATT 305
#define EMPTYUNITATT 306
#define EMPTYVALUEATT 307
#define EMPTYLBVALUEATT 308
#define EMPTYUBVALUEATT 309
#define LBVALUEATT 310
#define UBVALUEATT 311
#define EMPTYLBDUALVALUEATT 312
#define EMPTYUBDUALVALUEATT 313
#define LBDUALVALUEATT 314
#define UBDUALVALUEATT 315
#define SOLVERATT 316
#define EMPTYSOLVERATT 317
#define WEIGHTATT 318
#define EMPTYWEIGHTATT 319
#define TRANSPORTTYPEATT 320
#define LOCATIONTYPEATT 321
#define GENERALSTART 322
#define GENERALEND 323
#define SYSTEMSTART 324
#define SYSTEMEND 325
#define SERVICESTART 326
#define SERVICEEND 327
#define JOBSTART 328
#define JOBEND 329
#define OPTIMIZATIONSTART 330
#define OPTIMIZATIONEND 331
#define SERVICEURISTART 332
#define SERVICEURIEND 333
#define SERVICENAMESTART 334
#define SERVICENAMEEND 335
#define INSTANCENAMESTART 336
#define INSTANCENAMEEND 337
#define INSTANCELOCATIONSTART 338
#define INSTANCELOCATIONEND 339
#define JOBIDSTART 340
#define JOBIDEND 341
#define SOLVERTOINVOKESTART 342
#define SOLVERTOINVOKEEND 343
#define LICENSESTART 344
#define LICENSEEND 345
#define USERNAMESTART 346
#define USERNAMEEND 347
#define PASSWORDSTART 348
#define PASSWORDEND 349
#define CONTACTSTART 350
#define CONTACTEND 351
#define OTHEROPTIONSSTART 352
#define OTHEROPTIONSEND 353
#define OTHERSTART 354
#define OTHEREND 355
#define MINDISKSPACESTART 356
#define MINDISKSPACEEND 357
#define MINMEMORYSTART 358
#define MINMEMORYEND 359
#define MINCPUSPEEDSTART 360
#define MINCPUSPEEDEND 361
#define MINCPUNUMBERSTART 362
#define MINCPUNUMBEREND 363
#define SERVICETYPESTART 364
#define SERVICETYPEEND 365
#define MAXTIMESTART 366
#define MAXTIMEEND 367
#define REQUESTEDSTARTTIMESTART 368
#define REQUESTEDSTARTTIMEEND 369
#define DEPENDENCIESSTART 370
#define DEPENDENCIESEND 371
#define REQUIREDDIRECTORIESSTART 372
#define REQUIREDDIRECTORIESEND 373
#define REQUIREDFILESSTART 374
#define REQUIREDFILESEND 375
#define PATHSTART 376
#define PATHEND 377
#define PATHPAIRSTART 378
#define PATHPAIREND 379
#define DIRECTORIESTOMAKESTART 380
#define DIRECTORIESTOMAKEEND 381
#define FILESTOMAKESTART 382
#define FILESTOMAKEEND 383
#define DIRECTORIESTODELETESTART 384
#define DIRECTORIESTODELETEEND 385
#define FILESTODELETESTART 386
#define FILESTODELETEEND 387
#define INPUTDIRECTORIESTOMOVESTART 388
#define INPUTDIRECTORIESTOMOVEEND 389
#define INPUTFILESTOMOVESTART 390
#define INPUTFILESTOMOVEEND 391
#define OUTPUTDIRECTORIESTOMOVESTART 392
#define OUTPUTDIRECTORIESTOMOVEEND 393
#define OUTPUTFILESTOMOVESTART 394
#define OUTPUTFILESTOMOVEEND 395
#define PROCESSESTOKILLSTART 396
#define PROCESSESTOKILLEND 397
#define PROCESSSTART 398
#define PROCESSEND 399
#define VARIABLESSTART 400
#define VARIABLESEND 401
#define INITIALVARIABLEVALUESSTART 402
#define INITIALVARIABLEVALUESEND 403
#define VARSTART 404
#define VAREND 405
#define INITIALVARIABLEVALUESSTRINGSTART 406
#define INITIALVARIABLEVALUESSTRINGEND 407
#define INITIALBASISSTATUSSTART 408
#define INITIALBASISSTATUSEND 409
#define BASICSTART 410
#define BASICEND 411
#define ATUPPERSTART 412
#define ATUPPEREND 413
#define ATLOWERSTART 414
#define ATLOWEREND 415
#define SUPERBASICSTART 416
#define SUPERBASICEND 417
#define ISFREESTART 418
#define ISFREEEND 419
#define UNKNOWNSTART 420
#define UNKNOWNEND 421
#define INTEGERVARIABLEBRANCHINGWEIGHTSSTART 422
#define INTEGERVARIABLEBRANCHINGWEIGHTSEND 423
#define SOSVARIABLEBRANCHINGWEIGHTSSTART 424
#define SOSVARIABLEBRANCHINGWEIGHTSEND 425
#define SOSSTART 426
#define SOSEND 427
#define OBJECTIVESSTART 428
#define OBJECTIVESEND 429
#define INITIALOBJECTIVEVALUESSTART 430
#define INITIALOBJECTIVEVALUESEND 431
#define OBJSTART 432
#define OBJEND 433
#define INITIALOBJECTIVEBOUNDSSTART 434
#define INITIALOBJECTIVEBOUNDSEND 435
#define CONSTRAINTSSTART 436
#define CONSTRAINTSEND 437
#define INITIALCONSTRAINTVALUESSTART 438
#define INITIALCONSTRAINTVALUESEND 439
#define CONSTART 440
#define CONEND 441
#define INITIALDUALVALUESSTART 442
#define INITIALDUALVALUESEND 443
#define SOLVEROPTIONSSTART 444
#define SOLVEROPTIONSEND 445
#define SOLVEROPTIONSTART 446
#define SOLVEROPTIONEND 447
#define ENUMERATIONSTART 448
#define ENUMERATIONEND 449
#define ITEMEMPTY 450
#define ITEMSTART 451
#define ITEMEND 452
#define ITEMSTARTANDEND 453
#define BASE64START 454
#define BASE64END 455
#define INCRATT 456
#define MULTATT 457
#define SIZEOFATT 458
#define ELSTART 459
#define ELEND 460
#define DUMMY 461




#if ! defined YYSTYPE && ! defined YYSTYPE_IS_DECLARED
typedef union YYSTYPE

{
	double dval;
	int ival;
	char* sval;
}
/* Line 1529 of yacc.c.  */

	YYSTYPE;
# define yystype YYSTYPE /* obsolescent; will be withdrawn */
# define YYSTYPE_IS_DECLARED 1
# define YYSTYPE_IS_TRIVIAL 1
#endif



#if ! defined YYLTYPE && ! defined YYLTYPE_IS_DECLARED
typedef struct YYLTYPE
{
  int first_line;
  int first_column;
  int last_line;
  int last_column;
} YYLTYPE;
# define yyltype YYLTYPE /* obsolescent; will be withdrawn */
# define YYLTYPE_IS_DECLARED 1
# define YYLTYPE_IS_TRIVIAL 1
#endif


