/* A Bison parser, made by GNU Bison 2.3.  */

/* Skeleton interface for Bison's Yacc-like parsers in C

   Copyright (C) 1984, 1989, 1990, 2000, 2001, 2002, 2003, 2004, 2005, 2006
   Free Software Foundation, Inc.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin Street, Fifth Floor,
   Boston, MA 02110-1301, USA.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.

   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

/* Tokens.  */
#ifndef YYTOKENTYPE
# define YYTOKENTYPE
   /* Put the tokens into the symbol table, so that GDB and other debuggers
      know about them.  */
   enum yytokentype {
     ATTRIBUTETEXT = 258,
     ELEMENTTEXT = 259,
     ITEMTEXT = 260,
     INTEGER = 261,
     DOUBLE = 262,
     QUOTE = 263,
     TWOQUOTES = 264,
     GREATERTHAN = 265,
     ENDOFELEMENT = 266,
     OSRLSTART = 267,
     OSRLSTARTEMPTY = 268,
     OSRLATTRIBUTETEXT = 269,
     OSRLEND = 270,
     NUMBEROFCONATT = 271,
     NUMBEROFCONSTRAINTSATT = 272,
     NUMBEROFELATT = 273,
     NUMBEROFENUMERATIONSATT = 274,
     NUMBEROFIDXATT = 275,
     NUMBEROFITEMSATT = 276,
     NUMBEROFOBJATT = 277,
     NUMBEROFOBJECTIVESATT = 278,
     NUMBEROFOTHERCONSTRAINTRESULTSATT = 279,
     NUMBEROFOTHEROBJECTIVERESULTSATT = 280,
     NUMBEROFOTHERRESULTSATT = 281,
     NUMBEROFOTHERSOLUTIONRESULTSATT = 282,
     NUMBEROFOTHERVARIABLERESULTSATT = 283,
     NUMBEROFSOLUTIONSATT = 284,
     NUMBEROFSOLVEROUTPUTSATT = 285,
     NUMBEROFSUBSTATUSESATT = 286,
     NUMBEROFTIMESATT = 287,
     NUMBEROFVARATT = 288,
     NUMBEROFVARIABLESATT = 289,
     NUMBEROFVARIDXATT = 290,
     TARGETOBJECTIVEIDXATT = 291,
     IDXATT = 292,
     INCRATT = 293,
     MULTATT = 294,
     SIZEOFATT = 295,
     CATEGORYATT = 296,
     EMPTYCATEGORYATT = 297,
     DESCRIPTIONATT = 298,
     EMPTYDESCRIPTIONATT = 299,
     NAMEATT = 300,
     EMPTYNAMEATT = 301,
     TYPEATT = 302,
     EMPTYTYPEATT = 303,
     UNITATT = 304,
     EMPTYUNITATT = 305,
     VALUEATT = 306,
     EMPTYVALUEATT = 307,
     WEIGHTEDOBJECTIVESATT = 308,
     EMPTYWEIGHTEDOBJECTIVESATT = 309,
     GENERALSTART = 310,
     GENERALEND = 311,
     SYSTEMSTART = 312,
     SYSTEMEND = 313,
     SERVICESTART = 314,
     SERVICEEND = 315,
     JOBSTART = 316,
     JOBEND = 317,
     OPTIMIZATIONSTART = 318,
     OPTIMIZATIONEND = 319,
     ITEMSTART = 320,
     ITEMEND = 321,
     ITEMSTARTANDEND = 322,
     ITEMEMPTY = 323,
     ACTUALSTARTTIMESTART = 324,
     ACTUALSTARTTIMEEND = 325,
     ATLOWERSTART = 326,
     ATLOWEREND = 327,
     ATUPPERSTART = 328,
     ATUPPEREND = 329,
     AVAILABLECPUNUMBERSTART = 330,
     AVAILABLECPUNUMBEREND = 331,
     AVAILABLECPUSPEEDSTART = 332,
     AVAILABLECPUSPEEDEND = 333,
     AVAILABLEDISKSPACESTART = 334,
     AVAILABLEDISKSPACEEND = 335,
     AVAILABLEMEMORYSTART = 336,
     AVAILABLEMEMORYEND = 337,
     BASE64START = 338,
     BASE64END = 339,
     BASICSTART = 340,
     BASICEND = 341,
     BASISSTATUSSTART = 342,
     BASISSTATUSEND = 343,
     BASSTATUSSTART = 344,
     BASSTATUSEND = 345,
     CONSTART = 346,
     CONEND = 347,
     CONSTRAINTSSTART = 348,
     CONSTRAINTSEND = 349,
     CURRENTJOBCOUNTSTART = 350,
     CURRENTJOBCOUNTEND = 351,
     CURRENTSTATESTART = 352,
     CURRENTSTATEEND = 353,
     DUALVALUESSTART = 354,
     DUALVALUESEND = 355,
     ELSTART = 356,
     ELEND = 357,
     ENUMERATIONSTART = 358,
     ENUMERATIONEND = 359,
     ENDTIMESTART = 360,
     ENDTIMEEND = 361,
     GENERALSTATUSSTART = 362,
     GENERALSTATUSEND = 363,
     GENERALSUBSTATUSSTART = 364,
     GENERALSUBSTATUSEND = 365,
     IDXSTART = 366,
     IDXEND = 367,
     INSTANCENAMESTART = 368,
     INSTANCENAMEEND = 369,
     ISFREESTART = 370,
     ISFREEEND = 371,
     JOBIDSTART = 372,
     JOBIDEND = 373,
     MESSAGESTART = 374,
     MESSAGEEND = 375,
     OBJSTART = 376,
     OBJEND = 377,
     OBJECTIVESSTART = 378,
     OBJECTIVESEND = 379,
     OPTIMIZATIONSOLUTIONSTATUSSTART = 380,
     OPTIMIZATIONSOLUTIONSTATUSEND = 381,
     OPTIMIZATIONSOLUTIONSUBSTATUSSTART = 382,
     OPTIMIZATIONSOLUTIONSUBSTATUSEND = 383,
     OTHERSTART = 384,
     OTHEREND = 385,
     OTHERRESULTSSTART = 386,
     OTHERRESULTSEND = 387,
     OTHERSOLUTIONRESULTSTART = 388,
     OTHERSOLUTIONRESULTEND = 389,
     OTHERSOLUTIONRESULTSSTART = 390,
     OTHERSOLUTIONRESULTSEND = 391,
     OTHERSOLVEROUTPUTSTART = 392,
     OTHERSOLVEROUTPUTEND = 393,
     SCHEDULEDSTARTTIMESTART = 394,
     SCHEDULEDSTARTTIMEEND = 395,
     SERVICENAMESTART = 396,
     SERVICENAMEEND = 397,
     SERVICEURISTART = 398,
     SERVICEURIEND = 399,
     SERVICEUTILIZATIONSTART = 400,
     SERVICEUTILIZATIONEND = 401,
     SOLUTIONSTART = 402,
     SOLUTIONEND = 403,
     SOLVERINVOKEDSTART = 404,
     SOLVERINVOKEDEND = 405,
     SOLVEROUTPUTSTART = 406,
     SOLVEROUTPUTEND = 407,
     STATUSSTART = 408,
     STATUSEND = 409,
     SUBMITTIMESTART = 410,
     SUBMITTIMEEND = 411,
     SUBSTATUSSTART = 412,
     SUBSTATUSEND = 413,
     SUPERBASICSTART = 414,
     SUPERBASICEND = 415,
     SYSTEMINFORMATIONSTART = 416,
     SYSTEMINFORMATIONEND = 417,
     TIMESTART = 418,
     TIMEEND = 419,
     TIMESERVICESTARTEDSTART = 420,
     TIMESERVICESTARTEDEND = 421,
     TIMESTAMPSTART = 422,
     TIMESTAMPEND = 423,
     TIMINGINFORMATIONSTART = 424,
     TIMINGINFORMATIONEND = 425,
     TOTALJOBSSOFARSTART = 426,
     TOTALJOBSSOFAREND = 427,
     UNKNOWNSTART = 428,
     UNKNOWNEND = 429,
     USEDCPUNUMBERSTART = 430,
     USEDCPUNUMBEREND = 431,
     USEDCPUSPEEDSTART = 432,
     USEDCPUSPEEDEND = 433,
     USEDDISKSPACESTART = 434,
     USEDDISKSPACEEND = 435,
     USEDMEMORYSTART = 436,
     USEDMEMORYEND = 437,
     VALUESSTART = 438,
     VALUESEND = 439,
     VALUESSTRINGSTART = 440,
     VALUESSTRINGEND = 441,
     VARSTART = 442,
     VAREND = 443,
     VARIABLESSTART = 444,
     VARIABLESEND = 445,
     VARIDXSTART = 446,
     VARIDXEND = 447,
     DUMMY = 448
   };
#endif
/* Tokens.  */
#define ATTRIBUTETEXT 258
#define ELEMENTTEXT 259
#define ITEMTEXT 260
#define INTEGER 261
#define DOUBLE 262
#define QUOTE 263
#define TWOQUOTES 264
#define GREATERTHAN 265
#define ENDOFELEMENT 266
#define OSRLSTART 267
#define OSRLSTARTEMPTY 268
#define OSRLATTRIBUTETEXT 269
#define OSRLEND 270
#define NUMBEROFCONATT 271
#define NUMBEROFCONSTRAINTSATT 272
#define NUMBEROFELATT 273
#define NUMBEROFENUMERATIONSATT 274
#define NUMBEROFIDXATT 275
#define NUMBEROFITEMSATT 276
#define NUMBEROFOBJATT 277
#define NUMBEROFOBJECTIVESATT 278
#define NUMBEROFOTHERCONSTRAINTRESULTSATT 279
#define NUMBEROFOTHEROBJECTIVERESULTSATT 280
#define NUMBEROFOTHERRESULTSATT 281
#define NUMBEROFOTHERSOLUTIONRESULTSATT 282
#define NUMBEROFOTHERVARIABLERESULTSATT 283
#define NUMBEROFSOLUTIONSATT 284
#define NUMBEROFSOLVEROUTPUTSATT 285
#define NUMBEROFSUBSTATUSESATT 286
#define NUMBEROFTIMESATT 287
#define NUMBEROFVARATT 288
#define NUMBEROFVARIABLESATT 289
#define NUMBEROFVARIDXATT 290
#define TARGETOBJECTIVEIDXATT 291
#define IDXATT 292
#define INCRATT 293
#define MULTATT 294
#define SIZEOFATT 295
#define CATEGORYATT 296
#define EMPTYCATEGORYATT 297
#define DESCRIPTIONATT 298
#define EMPTYDESCRIPTIONATT 299
#define NAMEATT 300
#define EMPTYNAMEATT 301
#define TYPEATT 302
#define EMPTYTYPEATT 303
#define UNITATT 304
#define EMPTYUNITATT 305
#define VALUEATT 306
#define EMPTYVALUEATT 307
#define WEIGHTEDOBJECTIVESATT 308
#define EMPTYWEIGHTEDOBJECTIVESATT 309
#define GENERALSTART 310
#define GENERALEND 311
#define SYSTEMSTART 312
#define SYSTEMEND 313
#define SERVICESTART 314
#define SERVICEEND 315
#define JOBSTART 316
#define JOBEND 317
#define OPTIMIZATIONSTART 318
#define OPTIMIZATIONEND 319
#define ITEMSTART 320
#define ITEMEND 321
#define ITEMSTARTANDEND 322
#define ITEMEMPTY 323
#define ACTUALSTARTTIMESTART 324
#define ACTUALSTARTTIMEEND 325
#define ATLOWERSTART 326
#define ATLOWEREND 327
#define ATUPPERSTART 328
#define ATUPPEREND 329
#define AVAILABLECPUNUMBERSTART 330
#define AVAILABLECPUNUMBEREND 331
#define AVAILABLECPUSPEEDSTART 332
#define AVAILABLECPUSPEEDEND 333
#define AVAILABLEDISKSPACESTART 334
#define AVAILABLEDISKSPACEEND 335
#define AVAILABLEMEMORYSTART 336
#define AVAILABLEMEMORYEND 337
#define BASE64START 338
#define BASE64END 339
#define BASICSTART 340
#define BASICEND 341
#define BASISSTATUSSTART 342
#define BASISSTATUSEND 343
#define BASSTATUSSTART 344
#define BASSTATUSEND 345
#define CONSTART 346
#define CONEND 347
#define CONSTRAINTSSTART 348
#define CONSTRAINTSEND 349
#define CURRENTJOBCOUNTSTART 350
#define CURRENTJOBCOUNTEND 351
#define CURRENTSTATESTART 352
#define CURRENTSTATEEND 353
#define DUALVALUESSTART 354
#define DUALVALUESEND 355
#define ELSTART 356
#define ELEND 357
#define ENUMERATIONSTART 358
#define ENUMERATIONEND 359
#define ENDTIMESTART 360
#define ENDTIMEEND 361
#define GENERALSTATUSSTART 362
#define GENERALSTATUSEND 363
#define GENERALSUBSTATUSSTART 364
#define GENERALSUBSTATUSEND 365
#define IDXSTART 366
#define IDXEND 367
#define INSTANCENAMESTART 368
#define INSTANCENAMEEND 369
#define ISFREESTART 370
#define ISFREEEND 371
#define JOBIDSTART 372
#define JOBIDEND 373
#define MESSAGESTART 374
#define MESSAGEEND 375
#define OBJSTART 376
#define OBJEND 377
#define OBJECTIVESSTART 378
#define OBJECTIVESEND 379
#define OPTIMIZATIONSOLUTIONSTATUSSTART 380
#define OPTIMIZATIONSOLUTIONSTATUSEND 381
#define OPTIMIZATIONSOLUTIONSUBSTATUSSTART 382
#define OPTIMIZATIONSOLUTIONSUBSTATUSEND 383
#define OTHERSTART 384
#define OTHEREND 385
#define OTHERRESULTSSTART 386
#define OTHERRESULTSEND 387
#define OTHERSOLUTIONRESULTSTART 388
#define OTHERSOLUTIONRESULTEND 389
#define OTHERSOLUTIONRESULTSSTART 390
#define OTHERSOLUTIONRESULTSEND 391
#define OTHERSOLVEROUTPUTSTART 392
#define OTHERSOLVEROUTPUTEND 393
#define SCHEDULEDSTARTTIMESTART 394
#define SCHEDULEDSTARTTIMEEND 395
#define SERVICENAMESTART 396
#define SERVICENAMEEND 397
#define SERVICEURISTART 398
#define SERVICEURIEND 399
#define SERVICEUTILIZATIONSTART 400
#define SERVICEUTILIZATIONEND 401
#define SOLUTIONSTART 402
#define SOLUTIONEND 403
#define SOLVERINVOKEDSTART 404
#define SOLVERINVOKEDEND 405
#define SOLVEROUTPUTSTART 406
#define SOLVEROUTPUTEND 407
#define STATUSSTART 408
#define STATUSEND 409
#define SUBMITTIMESTART 410
#define SUBMITTIMEEND 411
#define SUBSTATUSSTART 412
#define SUBSTATUSEND 413
#define SUPERBASICSTART 414
#define SUPERBASICEND 415
#define SYSTEMINFORMATIONSTART 416
#define SYSTEMINFORMATIONEND 417
#define TIMESTART 418
#define TIMEEND 419
#define TIMESERVICESTARTEDSTART 420
#define TIMESERVICESTARTEDEND 421
#define TIMESTAMPSTART 422
#define TIMESTAMPEND 423
#define TIMINGINFORMATIONSTART 424
#define TIMINGINFORMATIONEND 425
#define TOTALJOBSSOFARSTART 426
#define TOTALJOBSSOFAREND 427
#define UNKNOWNSTART 428
#define UNKNOWNEND 429
#define USEDCPUNUMBERSTART 430
#define USEDCPUNUMBEREND 431
#define USEDCPUSPEEDSTART 432
#define USEDCPUSPEEDEND 433
#define USEDDISKSPACESTART 434
#define USEDDISKSPACEEND 435
#define USEDMEMORYSTART 436
#define USEDMEMORYEND 437
#define VALUESSTART 438
#define VALUESEND 439
#define VALUESSTRINGSTART 440
#define VALUESSTRINGEND 441
#define VARSTART 442
#define VAREND 443
#define VARIABLESSTART 444
#define VARIABLESEND 445
#define VARIDXSTART 446
#define VARIDXEND 447
#define DUMMY 448




#if ! defined YYSTYPE && ! defined YYSTYPE_IS_DECLARED
typedef union YYSTYPE

{
	double dval;
	int ival;
	char* sval;
}
/* Line 1529 of yacc.c.  */

	YYSTYPE;
# define yystype YYSTYPE /* obsolescent; will be withdrawn */
# define YYSTYPE_IS_DECLARED 1
# define YYSTYPE_IS_TRIVIAL 1
#endif



#if ! defined YYLTYPE && ! defined YYLTYPE_IS_DECLARED
typedef struct YYLTYPE
{
  int first_line;
  int first_column;
  int last_line;
  int last_column;
} YYLTYPE;
# define yyltype YYLTYPE /* obsolescent; will be withdrawn */
# define YYLTYPE_IS_DECLARED 1
# define YYLTYPE_IS_TRIVIAL 1
#endif


