/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSSolverInterfaces/KnitroSolver.cpp File Reference
/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSSolverInterfaces/KnitroSolver.cpp File Reference
#include "KnitroSolver.h"
#include "CommonUtil.h"
#include <dlfcn.h>
Functions
static int wrapperEvalFC (const int evalRequestCode, const int n, const int m, const int nnzJ, const int nnzH, const double *const daX, const double *const daLambda, double *const dObj, double *const daC, double *const daG, double *const daJ, double *const daH, double *const daHV, void *userParams)
static int wrapperEvalGA (const int evalRequestCode, const int n, const int m, const int nnzJ, const int nnzH, const double *const daX, const double *const daLambda, double *const dObj, double *const daC, double *const daG, double *const daJ, double *const daH, double *const daHV, void *userParams)
By necessity this wrapper signature matches the function KTR_callback.
static int wrapperEvalHorHV (const int evalRequestCode, const int n, const int m, const int nnzJ, const int nnzH, const double *const daX, const double *const daLambda, double *const dObj, double *const daC, double *const daG, double *const daJ, double *const daH, double *const daHV, void *userParams)
By necessity this wrapper signature matches the function KTR_callback.
Variables
static NlpProblemDef * g_pTheNlpProblemDefInstance = NULL
static NlpProblemDef * g_pOptProblem = NULL
Detailed Description
This file defines the KnitroSolver class. Read an OSInstance object and convert in Knitro data structures
Author:
Robert Fourer, Jun Ma, Kipp Martin,
Version:
1.0, 10/05/2005
Since:
OS1.0
Remarks:
Copyright (C) 2005, Robert Fourer, Jun Ma, Kipp Martin, Northwestern University, and the University of Chicago. All Rights Reserved. This software is licensed under the Common Public License. Please see the accompanying LICENSE file in root directory for terms.
Definition in file KnitroSolver.cpp.
Function Documentation
static int wrapperEvalFC (const int evalRequestCode, const int n, const int m, const int nnzJ, const int nnzH, const double *const daX, const double *const daLambda, double *const dObj, double *const daC, double *const daG, double *const daJ, double *const daH, double *const daHV, void * userParams) [static]
Definition at line 44 of file KnitroSolver.cpp.
References g_pOptProblem.
Referenced by KnitroSolver::solve().
static int wrapperEvalGA (const int evalRequestCode, const int n, const int m, const int nnzJ, const int nnzH, const double *const daX, const double *const daLambda, double *const dObj, double *const daC, double *const daG, double *const daJ, double *const daH, double *const daHV, void * userParams) [static]
By necessity this wrapper signature matches the function KTR_callback.
It calls the current optimization problem's eval method.
Definition at line 79 of file KnitroSolver.cpp.
References g_pOptProblem.
Referenced by KnitroSolver::solve().
static int wrapperEvalHorHV (const int evalRequestCode, const int n, const int m, const int nnzJ, const int nnzH, const double *const daX, const double *const daLambda, double *const dObj, double *const daC, double *const daG, double *const daJ, double *const daH, double *const daHV, void * userParams) [static]
By necessity this wrapper signature matches the function KTR_callback.
It calls the current optimization problem's eval method.
Definition at line 114 of file KnitroSolver.cpp.
References g_pOptProblem.
Referenced by KnitroSolver::solve().
Variable Documentation
NlpProblemDef* g_pTheNlpProblemDefInstance = NULL [static]
Definition at line 39 of file KnitroSolver.cpp.
NlpProblemDef* g_pOptProblem = NULL [static]
Definition at line 42 of file KnitroSolver.cpp.
Referenced by KnitroSolver::solve(), wrapperEvalFC(), wrapperEvalGA(), and wrapperEvalHorHV().