/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/applications/amplClient/OSAmplClient.cpp File Reference
/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/applications/amplClient/OSAmplClient.cpp File Reference
#include "OSCoinSolver.h"
#include "OSConfig.h"
#include "OSnl2osil.h"
#include "OSiLReader.h"
#include "OSrLReader.h"
#include "OSiLWriter.h"
#include "OSrLWriter.h"
#include "OSInstance.h"
#include "OSResult.h"
#include "OSFileUtil.h"
#include "OSDefaultSolver.h"
#include "OSSolverAgent.h"
#include "OShL.h"
#include "OSErrorClass.h"
#include <sstream>
#include <asl.h>
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
amplclient_option: 1. solver: possible values - clp, glpk, cplex, cplex, lindo 2. location: possible values - NULL (empty) or url of the solver service
Definition at line 80 of file OSAmplClient.cpp.
References DefaultSolver::buildSolverInstance(), OSnl2osil::createOSInstance(), ErrorClass::errormsg, OSResult::getOptimalDualVariableValues(), OSResult::getOptimalPrimalVariableValues(), DefaultSolver::osinstance, OSnl2osil::osinstance, osinstance, DefaultSolver::osol, osresult, DefaultSolver::osrl, OSrLReader::readOSrL(), OSResult::setGeneralMessage(), OSResult::setGeneralStatusType(), OSSolverAgent::solve(), DefaultSolver::solve(), DefaultSolver::sSolverName, FileUtil::writeFileFromString(), OSiLWriter::writeOSiL(), and OSrLWriter::writeOSrL().