/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/examples/addCuts/OSAddCuts.cpp File Reference
/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/examples/addCuts/OSAddCuts.cpp File Reference
#include <cppad/cppad.hpp>
#include "OSConfig.h"
#include "OSCoinSolver.h"
#include "OSResult.h"
#include "OSiLReader.h"
#include "OSiLWriter.h"
#include "OSrLReader.h"
#include "OSrLWriter.h"
#include "OSInstance.h"
#include "OSFileUtil.h"
#include "OSDefaultSolver.h"
#include "OSWSUtil.h"
#include "OSSolverAgent.h"
#include "OShL.h"
#include "OSErrorClass.h"
#include "OSmps2osil.h"
#include "OSBase64.h"
#include "OSCommonUtil.h"
#include "CglGomory.hpp"
#include "CglSimpleRounding.hpp"
#include "CglKnapsackCover.hpp"
#include "OSMathUtil.h"
#include <iostream>
Functions
int main ()
Function Documentation
int main ()
Definition at line 50 of file OSAddCuts.cpp.
References CoinSolver::buildSolverInstance(), ErrorClass::errormsg, FileUtil::getFileAsString(), DefaultSolver::osinstance, CoinSolver::osiSolver, OSiLReader::readOSiL(), and DefaultSolver::sSolverName.