/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSUtils/OSMathUtil.cpp File Reference
/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSUtils/OSMathUtil.cpp File Reference
#include "OSDataStructures.h"
#include "OSMathUtil.h"
#include <iostream>
Functions
double os_strtod_wrap (const char *str, char **strEnd)
std::string os_dtoa_format (double x)
Function Documentation
double os_strtod_wrap (const char * str, char ** strEnd)
Definition at line 95 of file OSMathUtil.cpp.
References os_strtod().
std::string os_dtoa_format (double x)
Definition at line 104 of file OSMathUtil.cpp.
References os_dtoa(), and os_freedtoa().
Referenced by OSiLWriter::writeOSiL().