/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/examples/instanceGenerator/OSInstanceGenerator.cpp File Reference
/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/examples/instanceGenerator/OSInstanceGenerator.cpp File Reference
#include <iostream>
#include <vector>
#include "OSConfig.h"
#include "OSInstance.h"
#include "OSiLWriter.h"
#include "OSParameters.h"
#include "OSnLNode.h"
#include "OSErrorClass.h"
Functions
int main ()
Function Documentation
int main ()
Definition at line 55 of file OSInstanceGenerator.cpp.
References OSInstance::addConstraint(), OSInstance::addObjective(), OSInstance::addVariable(), SparseVector::bDeleteArrays, OSnLNode::createExpressionTreeFromPostfix(), ErrorClass::errormsg, OSnLNodeVariable::idx, Nl::idx, SparseVector::indexes, OSInstance::instanceData, OSnLNode::inumberOfChildren, OSnLNode::m_mChildren, OSExpressionTree::m_treeRoot, NonlinearExpressions::nl, InstanceData::nonlinearExpressions, NonlinearExpressions::numberOfNonlinearExpressions, OSDBL_MAX, Nl::osExpressionTree, osinstance, OSNAN, OSInstance::setConstraintNumber(), OSInstance::setInstanceDescription(), OSInstance::setInstanceSource(), OSInstance::setLinearConstraintCoefficients(), OSInstance::setObjectiveNumber(), OSInstance::setVariableNumber(), OSnLNodeNumber::value, SparseVector::values, and OSiLWriter::writeOSiL().