/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSCommonInterfaces/OSiLReader.cpp File Reference
/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSCommonInterfaces/OSiLReader.cpp File Reference
Author:
Robert Fourer, Jun Ma, Kipp Martin,
#include "OSiLReader.h"
Functions
void yygetOSInstance (const char *osil, OSInstance *osinstance, OSiLParserData *parserData) throw (ErrorClass)
int osillex_init (void **ptr_yy_globals)
int osillex_destroy (void *scanner)
void osilset_extra (OSiLParserData *parserData, void *yyscanner)
Detailed Description
Author:
Robert Fourer, Jun Ma, Kipp Martin,
Version:
1.0, 10/05/2005
Since:
OS1.0
Remarks:
Copyright (C) 2005, Robert Fourer, Jun Ma, Kipp Martin, Northwestern University, and the University of Chicago. All Rights Reserved. This software is licensed under the Common Public License. Please see the accompanying LICENSE file in root directory for terms.
Definition in file OSiLReader.cpp.
Function Documentation
void yygetOSInstance (const char * osil, OSInstance * osinstance, OSiLParserData * parserData) throw (ErrorClass)
Referenced by OSiLReader::readOSiL().
int osillex_init (void ** ptr_yy_globals)
Definition at line 3235 of file OSParseosil.cpp.
References osilalloc(), and yy_init_globals().
Referenced by OSiLReader::OSiLReader().
int osillex_destroy (void * scanner)
Definition at line 3290 of file OSParseosil.cpp.
References osil_delete_buffer(), osilfree(), osilpop_buffer_state(), yyguts_t::yy_buffer_stack, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yy_init_globals(), and yyguts_t::yy_start_stack.
Referenced by OSiLReader::~OSiLReader().
void osilset_extra (OSiLParserData * parserData, void * yyscanner)
Referenced by OSiLReader::OSiLReader().