/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSSolverService.cpp File Reference
/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSSolverService.cpp File Reference
Author:
Robert Fourer, Jun Ma, Kipp Martin,
#include "OSCoinSolver.h"
#include "OSResult.h"
#include "OSiLReader.h"
#include "OSiLWriter.h"
#include "OSrLReader.h"
#include "OSrLWriter.h"
#include "OSInstance.h"
#include "OSFileUtil.h"
#include "OSConfig.h"
#include "OSDefaultSolver.h"
#include "OSWSUtil.h"
#include "OSSolverAgent.h"
#include "OShL.h"
#include "OSErrorClass.h"
#include "OSmps2osil.h"
#include "OSBase64.h"
#include "OSCommonUtil.h"
#include "OSOptionsStruc.h"
Defines
#define MAXCHARS 5000
Typedefs
typedef struct
yy_buffer_state * YY_BUFFER_STATE
Functions
YY_BUFFER_STATE osss_scan_string (const char *osss, void *scanner)
void setyyextra (osOptionsStruc *osoptions, void *scanner)
int ossslex (void *scanner)
int ossslex_init (void **ptr)
int ossslex_destroy (void *scanner)
void solve ()
void getJobID ()
void send ()
void kill ()
void retrieve ()
void knock ()
void getOSiLFromNl ()
void getOSiLFromMps ()
string getServiceURI (std::string osol)
string getInstanceLocation (std::string osol)
string getSolverName (std::string osol)
int main (int argC, const char *argV[])
Variables
osOptionsStruc * osoptions
Detailed Description
Author:
Robert Fourer, Jun Ma, Kipp Martin,
Version:
1.0, 10/05/2005
Since:
OS1.0
Remarks:
Copyright (C) 2005, Robert Fourer, Jun Ma, Kipp Martin, Northwestern University, and the University of Chicago. All Rights Reserved. This software is licensed under the Common Public License. Please see the accompanying LICENSE file in root directory for terms.
INPUTS:
-osil xxx.osil (file name on local machine of optimization instance, this is NULL by default, however if this remains NULL a problem instance must be specified in the osol file)
-osol xxx.osol (file name on local machine of solver options, default default value is NULL)
-osrl xxx.osrl (file name on local machine where the optimization result is put, default is NULL)
-serviceLocation location URL (the URL of the server that is called remotely if the problem not solved locally, default is NULL)
-serviceMethod (send, solve, kill, knock, getJobID, retrieve, default value is solve)
-os (Not used for now -- ignore)
-osplInput xxx.ospl name of file with input in OS Process Language
-osplOutput xxx.ospl name of output file in OS Process Language
-mps xxxx.mps (converts mps format to osil and has same effect as -osil)
-nl xxxx.nl (converts nl format to osil and has same effect as -osil)
-solver solverName (the name of the solver to be invoked)
-browser path location to browser e.g. /Applications/Firefox.app/Contents/MacOS/firefox (default is NULL)
-config pathToConfigFile is the path to a configure file with the problem parameters
-insList xxx.dat (used only for LINDO, file location on local machine of LINDO instruction list)
Definition in file OSSolverService.cpp.
Define Documentation
#define MAXCHARS 5000
Definition at line 147 of file OSSolverService.cpp.
Referenced by main().
Typedef Documentation
typedef struct yy_buffer_state* YY_BUFFER_STATE
Definition at line 149 of file OSSolverService.cpp.
Function Documentation
YY_BUFFER_STATE osss_scan_string (const char * osss, void * scanner)
void setyyextra (osOptionsStruc * osoptions, void * scanner)
int ossslex (void * scanner)
int ossslex_init (void ** ptr)
int ossslex_destroy (void * scanner)
void solve ()
Definition at line 386 of file OSSolverService.cpp.
References osOptionsStruc::browser, DefaultSolver::buildSolverInstance(), OSmps2osil::createOSInstance(), OSnl2osil::createOSInstance(), ErrorClass::errormsg, getOSiLFromMps(), getOSiLFromNl(), osOptionsStruc::mpsFile, osOptionsStruc::nlFile, osOptionsStruc::osil, OSmps2osil::osinstance, OSnl2osil::osinstance, DefaultSolver::osinstance, DefaultSolver::osol, osOptionsStruc::osol, osresult, DefaultSolver::osrl, osOptionsStruc::osrlFile, OSiLReader::readOSiL(), osOptionsStruc::serviceLocation, OSResult::setGeneralMessage(), OSResult::setGeneralStatusType(), DefaultSolver::solve(), OSSolverAgent::solve(), osOptionsStruc::solverName, DefaultSolver::sSolverName, FileUtil::writeFileFromString(), and OSrLWriter::writeOSrL().
Referenced by main().
void getJobID ()
Definition at line 635 of file OSSolverService.cpp.
References ErrorClass::errormsg, OSSolverAgent::getJobID(), osOptionsStruc::osol, osresult, osOptionsStruc::osrlFile, osOptionsStruc::serviceLocation, OSResult::setGeneralMessage(), OSResult::setGeneralStatusType(), FileUtil::writeFileFromString(), and OSrLWriter::writeOSrL().
Referenced by main().
void send ()
Definition at line 714 of file OSSolverService.cpp.
References ErrorClass::errormsg, OSSolverAgent::getJobID(), getOSiLFromMps(), getOSiLFromNl(), osOptionsStruc::mpsFile, osOptionsStruc::nlFile, osOptionsStruc::osil, osOptionsStruc::osol, osOptionsStruc::osolFile, osresult, osOptionsStruc::osrlFile, OSSolverAgent::send(), osOptionsStruc::serviceLocation, OSResult::setGeneralMessage(), OSResult::setGeneralStatusType(), FileUtil::writeFileFromString(), and OSrLWriter::writeOSrL().
Referenced by main().
void kill ()
Definition at line 842 of file OSSolverService.cpp.
References ErrorClass::errormsg, OSSolverAgent::kill(), osOptionsStruc::osol, osOptionsStruc::osplOutputFile, osresult, osOptionsStruc::osrlFile, osOptionsStruc::serviceLocation, OSResult::setGeneralMessage(), OSResult::setGeneralStatusType(), FileUtil::writeFileFromString(), and OSrLWriter::writeOSrL().
Referenced by main().
void retrieve ()
Definition at line 793 of file OSSolverService.cpp.
References osOptionsStruc::browser, ErrorClass::errormsg, osOptionsStruc::osol, osresult, osOptionsStruc::osrlFile, OSSolverAgent::retrieve(), osOptionsStruc::serviceLocation, OSResult::setGeneralMessage(), OSResult::setGeneralStatusType(), FileUtil::writeFileFromString(), and OSrLWriter::writeOSrL().
Referenced by main().
void knock ()
Definition at line 674 of file OSSolverService.cpp.
References ErrorClass::errormsg, OSSolverAgent::knock(), osOptionsStruc::osol, osOptionsStruc::osplInput, osOptionsStruc::osplOutputFile, osresult, osOptionsStruc::osrlFile, osOptionsStruc::serviceLocation, OSResult::setGeneralMessage(), OSResult::setGeneralStatusType(), FileUtil::writeFileFromString(), and OSrLWriter::writeOSrL().
Referenced by main().
void getOSiLFromNl ()
Definition at line 883 of file OSSolverService.cpp.
References OSnl2osil::createOSInstance(), ErrorClass::errormsg, osOptionsStruc::nlFile, osOptionsStruc::osil, OSnl2osil::osinstance, and OSiLWriter::writeOSiL().
Referenced by send(), and solve().
void getOSiLFromMps ()
Definition at line 909 of file OSSolverService.cpp.
References OSmps2osil::createOSInstance(), ErrorClass::errormsg, osOptionsStruc::mpsFile, osOptionsStruc::osil, OSmps2osil::osinstance, and OSiLWriter::writeOSiL().
Referenced by send(), and solve().
string getServiceURI (std::string osol)
Definition at line 931 of file OSSolverService.cpp.
Referenced by main().
string getInstanceLocation (std::string osol)
Definition at line 952 of file OSSolverService.cpp.
Referenced by main().
string getSolverName (std::string osol)
Definition at line 973 of file OSSolverService.cpp.
Referenced by main().
int main (int argC, const char * argV[])
Definition at line 182 of file OSSolverService.cpp.
References osOptionsStruc::browser, osOptionsStruc::configFile, ErrorClass::errormsg, FileUtil::getFileAsChar(), FileUtil::getFileAsString(), getInstanceLocation(), getJobID(), getServiceURI(), getSolverName(), osOptionsStruc::insList, osOptionsStruc::insListFile, osOptionsStruc::invokeHelp, kill(), knock(), MAXCHARS, osOptionsStruc::mpsFile, osOptionsStruc::nlFile, osOptionsStruc::osil, osOptionsStruc::osilFile, osOptionsStruc::osol, osOptionsStruc::osolFile, osOptionsStruc::osplInput, osOptionsStruc::osplInputFile, osOptionsStruc::osplOutput, osOptionsStruc::osplOutputFile, osOptionsStruc::osrl, osOptionsStruc::osrlFile, osss_scan_string(), ossslex(), ossslex_destroy(), ossslex_init(), retrieve(), scanner, send(), osOptionsStruc::serviceLocation, osOptionsStruc::serviceMethod, setyyextra(), solve(), osOptionsStruc::solverName, and osOptionsStruc::writeVersion.
Variable Documentation
osOptionsStruc* osoptions
Definition at line 179 of file OSSolverService.cpp.