/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/examples/osTestCode/OSTestCode.cpp File Reference
/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/examples/osTestCode/OSTestCode.cpp File Reference
Author:
Robert Fourer, Jun Ma, Kipp Martin,
#include <cppad/cppad.hpp>
#include "OSConfig.h"
#include "OSCoinSolver.h"
#include "OSResult.h"
#include "OSiLReader.h"
#include "OSiLWriter.h"
#include "OSrLReader.h"
#include "OSrLWriter.h"
#include "OSInstance.h"
#include "OSFileUtil.h"
#include "OSDefaultSolver.h"
#include "OSWSUtil.h"
#include "OSSolverAgent.h"
#include "OShL.h"
#include "OSErrorClass.h"
#include "OSmps2osil.h"
#include "OSBase64.h"
#include "OSCommonUtil.h"
#include "OSMathUtil.h"
#include <iostream>
Functions
int main ()
Detailed Description
Author:
Robert Fourer, Jun Ma, Kipp Martin,
Version:
1.0, 10/05/2005
Since:
OS1.0
Remarks:
Copyright (C) 2005, Robert Fourer, Jun Ma, Kipp Martin, Northwestern University, and the University of Chicago. All Rights Reserved. This software is licensed under the Common Public License. Please see the accompanying LICENSE file in root directory for terms.
This is a dummy executable that does nothing but print Hello World. I put in test code here when doing various tests.
Definition in file OSTestCode.cpp.
Function Documentation
int main ()
Definition at line 52 of file OSTestCode.cpp.
References OSInstance::addConstraint(), OSInstance::addObjective(), OSInstance::addVariable(), SparseVector::bDeleteArrays, CoinSolver::buildSolverInstance(), ErrorClass::errormsg, SparseVector::indexes, OSDBL_MAX, DefaultSolver::osinstance, osinstance, OSNAN, DefaultSolver::osrl, OSInstance::setConstraintNumber(), OSInstance::setInstanceDescription(), OSInstance::setInstanceSource(), OSInstance::setLinearConstraintCoefficients(), OSInstance::setObjectiveNumber(), OSInstance::setVariableNumber(), CoinSolver::solve(), DefaultSolver::sSolverName, SparseVector::values, and OSiLWriter::writeOSiL().