/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSParsers/OSParseosrl.cpp File Reference
/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSParsers/OSParseosrl.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
#include <iostream>
#include "OSConfig.h"
#include <sstream>
#include "OSErrorClass.h"
#include "OSrLParserData.h"
#include "OSParseosrl.tab.hpp"
#include <unistd.h>
Classes
struct yy_buffer_state
struct yy_trans_info
struct yyguts_t
Defines
#define YY_INT_ALIGNED short int
#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 33
#define FLEX_BETA
#define INT8_MIN (-128)
#define INT16_MIN (-32767-1)
#define INT32_MIN (-2147483647-1)
#define INT8_MAX (127)
#define INT16_MAX (32767)
#define INT32_MAX (2147483647)
#define UINT8_MAX (255U)
#define UINT16_MAX (65535U)
#define UINT32_MAX (4294967295U)
#define yyconst
#define YY_NULL 0
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r
#define BEGIN yyg->yy_start = 1 + 2 *
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
#define YY_NEW_FILE osrlrestart(yyin ,yyscanner)
#define YY_END_OF_BUFFER_CHAR 0
#define YY_BUF_SIZE 16384
#define YY_STATE_BUF_SIZE ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))
#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
#define YY_LESS_LINENO(n)
#define yyless(n)
#define unput(c) yyunput(c, yyg->yytext_ptr , yyscanner)
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
#define YY_BUFFER_EOF_PENDING 2
#define YY_CURRENT_BUFFER
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]
#define YY_FLUSH_BUFFER osrl_flush_buffer(YY_CURRENT_BUFFER ,yyscanner)
#define yy_new_buffer osrl_create_buffer
#define yy_set_interactive(is_interactive)
#define yy_set_bol(at_bol)
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)
#define osrlwrap(n) 1
#define YY_SKIP_YYWRAP
#define yytext_ptr yytext_r
#define YY_DO_BEFORE_ACTION
#define YY_NUM_RULES 81
#define YY_END_OF_BUFFER 82
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#define YY_PRINT ;
#define YY_EXTRA_TYPE OSrLParserData*
#define INITIAL 0
#define attributetext 1
#define osrlattributetext 2
#define comment 3
#define xmldeclaration 4
#define yylval yyg->yylval_r
#define yylloc yyg->yylloc_r
#define YY_READ_BUF_SIZE 8192
#define ECHO (void) fwrite(yytext, yyleng, 1, yyout)
#define YY_INPUT(buf, result, max_size)
#define yyterminate() return YY_NULL
#define YY_START_STACK_INCR 25
#define YY_FATAL_ERROR(msg) yy_fatal_error(msg , yyscanner)
#define YY_DECL_IS_OURS 1
#define YY_DECL int osrllex (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner)
#define YY_BREAK break;
#define YY_RULE_SETUP YY_USER_ACTION
#define YY_EXIT_FAILURE 2
#define yyless(n)
#define YYTABLES_NAME "yytables"
Typedefs
typedef signed char flex_int8_t
typedef short int flex_int16_t
typedef int flex_int32_t
typedef unsigned char flex_uint8_t
typedef unsigned
short int flex_uint16_t
typedef unsigned int flex_uint32_t
typedef void * yyscan_t
typedef struct
yy_buffer_state * YY_BUFFER_STATE
typedef unsigned int yy_size_t
typedef unsigned char YY_CHAR
typedef int yy_state_type
Functions
int osrllex_init (yyscan_t *scanner)
void osrlrestart (FILE *input_file, yyscan_t yyscanner)
void osrl_switch_to_buffer (YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
YY_BUFFER_STATE osrl_create_buffer (FILE *file, int size, yyscan_t yyscanner)
void osrl_delete_buffer (YY_BUFFER_STATE b, yyscan_t yyscanner)
void osrl_flush_buffer (YY_BUFFER_STATE b, yyscan_t yyscanner)
Discard all buffered characters.
void osrlpush_buffer_state (YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
Pushes the new state onto the stack.
void osrlpop_buffer_state (yyscan_t yyscanner)
Removes and deletes the top of the stack, if present.
static void osrlensure_buffer_stack (yyscan_t yyscanner)
static void osrl_load_buffer_state (yyscan_t yyscanner)
static void osrl_init_buffer (YY_BUFFER_STATE b, FILE *file, yyscan_t yyscanner)
The main scanner function which does all the work.
YY_BUFFER_STATE osrl_scan_buffer (char *base, yy_size_t size, yyscan_t yyscanner)
Setup the input buffer state to scan directly from a user-specified character buffer.
YY_BUFFER_STATE osrl_scan_string (yyconst char *yystr, yyscan_t yyscanner)
Setup the input buffer state to scan a string.
YY_BUFFER_STATE osrl_scan_bytes (yyconst char *yybytes, int _yybytes_len, yyscan_t yyscanner)
Setup the input buffer state to scan the given bytes.
void * osrlalloc (yy_size_t, yyscan_t yyscanner)
void * osrlrealloc (void *, yy_size_t, yyscan_t yyscanner)
void osrlfree (void *, yyscan_t yyscanner)
static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
static yy_state_type yy_try_NUL_trans (yy_state_type current_state, yyscan_t yyscanner)
static int yy_get_next_buffer (yyscan_t yyscanner)
static void yy_fatal_error (yyconst char msg[], yyscan_t yyscanner)
static int yy_init_globals (yyscan_t yyscanner)
int osrllex_destroy (yyscan_t yyscanner)
int osrlget_debug (yyscan_t yyscanner)
void osrlset_debug (int debug_flag, yyscan_t yyscanner)
YY_EXTRA_TYPE osrlget_extra (yyscan_t yyscanner)
Get the user-defined data for this scanner.
void osrlset_extra (YY_EXTRA_TYPE user_defined, yyscan_t yyscanner)
Set the user-defined data.
FILE * osrlget_in (yyscan_t yyscanner)
Get the input stream.
void osrlset_in (FILE *in_str, yyscan_t yyscanner)
Set the input stream.
FILE * osrlget_out (yyscan_t yyscanner)
Get the output stream.
void osrlset_out (FILE *out_str, yyscan_t yyscanner)
int osrlget_leng (yyscan_t yyscanner)
Get the length of the current token.
char * osrlget_text (yyscan_t yyscanner)
Get the current token.
int osrlget_lineno (yyscan_t yyscanner)
Get the current line number.
void osrlset_lineno (int line_number, yyscan_t yyscanner)
Set the current line number.
YYSTYPE * osrlget_lval (yyscan_t yyscanner)
void osrlset_lval (YYSTYPE *yylval_param, yyscan_t yyscanner)
YYLTYPE * osrlget_lloc (yyscan_t yyscanner)
void osrlset_lloc (YYLTYPE *yylloc_param, yyscan_t yyscanner)
static void yyunput (int c, char *buf_ptr, yyscan_t yyscanner)
static int input (yyscan_t yyscanner)
int osrllex (YYSTYPE *yylval_param, YYLTYPE *yylloc_param, yyscan_t yyscanner)
static void yy_fatal_error (yyconst char *msg, yyscan_t yyscanner)
int osrlget_column (yyscan_t yyscanner)
Get the current column number.
void osrlset_column (int column_no, yyscan_t yyscanner)
Set the current column.
Variables
static yyconst
flex_int16_t yy_accept [719]
static yyconst
flex_int32_t yy_ec [256]
static yyconst
flex_int32_t yy_meta [53]
static yyconst
flex_int16_t yy_base [727]
static yyconst
flex_int16_t yy_def [727]
static yyconst
flex_int16_t yy_nxt [1820]
static yyconst
flex_int16_t yy_chk [1820]
static yyconst
flex_int32_t yy_rule_can_match_eol [82]
Define Documentation
#define YY_INT_ALIGNED short int
Definition at line 5 of file OSParseosrl.cpp.
#define FLEX_SCANNER
Definition at line 9 of file OSParseosrl.cpp.
#define YY_FLEX_MAJOR_VERSION 2
Definition at line 10 of file OSParseosrl.cpp.
#define YY_FLEX_MINOR_VERSION 5
Definition at line 11 of file OSParseosrl.cpp.
#define YY_FLEX_SUBMINOR_VERSION 33
Definition at line 12 of file OSParseosrl.cpp.
#define FLEX_BETA
Definition at line 14 of file OSParseosrl.cpp.
#define INT8_MIN (-128)
Definition at line 61 of file OSParseosrl.cpp.
#define INT16_MIN (-32767-1)
Definition at line 64 of file OSParseosrl.cpp.
#define INT32_MIN (-2147483647-1)
Definition at line 67 of file OSParseosrl.cpp.
#define INT8_MAX (127)
Definition at line 70 of file OSParseosrl.cpp.
#define INT16_MAX (32767)
Definition at line 73 of file OSParseosrl.cpp.
#define INT32_MAX (2147483647)
Definition at line 76 of file OSParseosrl.cpp.
#define UINT8_MAX (255U)
Definition at line 79 of file OSParseosrl.cpp.
#define UINT16_MAX (65535U)
Definition at line 82 of file OSParseosrl.cpp.
#define UINT32_MAX (4294967295U)
Definition at line 85 of file OSParseosrl.cpp.
#define yyconst
Definition at line 107 of file OSParseosrl.cpp.
#define YY_NULL 0
Definition at line 111 of file OSParseosrl.cpp.
#define YY_SC_TO_UI (c) ((unsigned int) (unsigned char) c)
Definition at line 118 of file OSParseosrl.cpp.
#define yyin yyg->yyin_r
Definition at line 128 of file OSParseosrl.cpp.
#define yyout yyg->yyout_r
Definition at line 129 of file OSParseosrl.cpp.
#define yyextra yyg->yyextra_r
Definition at line 130 of file OSParseosrl.cpp.
#define yyleng yyg->yyleng_r
Definition at line 131 of file OSParseosrl.cpp.
#define yytext yyg->yytext_r
Definition at line 132 of file OSParseosrl.cpp.
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
Definition at line 133 of file OSParseosrl.cpp.
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
Definition at line 134 of file OSParseosrl.cpp.
#define yy_flex_debug yyg->yy_flex_debug_r
Definition at line 135 of file OSParseosrl.cpp.
#define BEGIN yyg->yy_start = 1 + 2 *
Definition at line 143 of file OSParseosrl.cpp.
#define YY_START ((yyg->yy_start - 1) / 2)
Definition at line 149 of file OSParseosrl.cpp.
#define YYSTATE YY_START
Definition at line 150 of file OSParseosrl.cpp.
#define YY_STATE_EOF (state) (YY_END_OF_BUFFER + state + 1)
Definition at line 153 of file OSParseosrl.cpp.
#define YY_NEW_FILE osrlrestart(yyin ,yyscanner)
Definition at line 156 of file OSParseosrl.cpp.
#define YY_END_OF_BUFFER_CHAR 0
Definition at line 158 of file OSParseosrl.cpp.
#define YY_BUF_SIZE 16384
Definition at line 162 of file OSParseosrl.cpp.
#define YY_STATE_BUF_SIZE ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))
Definition at line 167 of file OSParseosrl.cpp.
#define EOB_ACT_CONTINUE_SCAN 0
Definition at line 174 of file OSParseosrl.cpp.
#define EOB_ACT_END_OF_FILE 1
Definition at line 175 of file OSParseosrl.cpp.
#define EOB_ACT_LAST_MATCH 2
Definition at line 176 of file OSParseosrl.cpp.
#define YY_LESS_LINENO (n)
Value:
do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
Definition at line 185 of file OSParseosrl.cpp.
#define yyless (n)
Value:
do \
                { \
                /* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
                *yy_cp = yyg->yy_hold_char; \
                YY_RESTORE_YY_MORE_OFFSET \
                yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
                YY_DO_BEFORE_ACTION; /* set up yytext again */ \
                } \
        while ( 0 )
Definition at line 2815 of file OSParseosrl.cpp.
#define unput (c) yyunput(c, yyg->yytext_ptr , yyscanner)
Definition at line 207 of file OSParseosrl.cpp.
#define YY_BUFFER_NEW 0
Definition at line 267 of file OSParseosrl.cpp.
#define YY_BUFFER_NORMAL 1
Definition at line 268 of file OSParseosrl.cpp.
#define YY_BUFFER_EOF_PENDING 2
Definition at line 279 of file OSParseosrl.cpp.
#define YY_CURRENT_BUFFER
Value:
(yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
Definition at line 290 of file OSParseosrl.cpp.
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]
Definition at line 297 of file OSParseosrl.cpp.
#define YY_FLUSH_BUFFER osrl_flush_buffer(YY_CURRENT_BUFFER ,yyscanner)
Definition at line 311 of file OSParseosrl.cpp.
#define yy_new_buffer osrl_create_buffer
Definition at line 321 of file OSParseosrl.cpp.
#define yy_set_interactive (is_interactive)
Value:
{ \
        if ( ! YY_CURRENT_BUFFER ){ \
        osrlensure_buffer_stack (yyscanner); \
                YY_CURRENT_BUFFER_LVALUE =    \
            osrl_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
        } \
        YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
        }
Definition at line 323 of file OSParseosrl.cpp.
#define yy_set_bol (at_bol)
Value:
{ \
        if ( ! YY_CURRENT_BUFFER ){\
        osrlensure_buffer_stack (yyscanner); \
                YY_CURRENT_BUFFER_LVALUE =    \
            osrl_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
        } \
        YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
        }
Definition at line 333 of file OSParseosrl.cpp.
#define YY_AT_BOL () (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)
Definition at line 343 of file OSParseosrl.cpp.
#define osrlwrap (n) 1
Definition at line 347 of file OSParseosrl.cpp.
#define YY_SKIP_YYWRAP
Definition at line 348 of file OSParseosrl.cpp.
#define yytext_ptr yytext_r
Definition at line 354 of file OSParseosrl.cpp.
#define YY_DO_BEFORE_ACTION
Value:
yyg->yytext_ptr = yy_bp; \
        yyleng = (size_t) (yy_cp - yy_bp); \
        yyg->yy_hold_char = *yy_cp; \
        *yy_cp = '\0'; \
        yyg->yy_c_buf_p = yy_cp;
Definition at line 364 of file OSParseosrl.cpp.
#define YY_NUM_RULES 81
Definition at line 371 of file OSParseosrl.cpp.
#define YY_END_OF_BUFFER 82
Definition at line 372 of file OSParseosrl.cpp.
#define REJECT reject_used_but_not_detected
Definition at line 1093 of file OSParseosrl.cpp.
#define yymore () yymore_used_but_not_detected
Definition at line 1094 of file OSParseosrl.cpp.
#define YY_MORE_ADJ 0
Definition at line 1095 of file OSParseosrl.cpp.
#define YY_RESTORE_YY_MORE_OFFSET
Definition at line 1096 of file OSParseosrl.cpp.
#define YY_PRINT ;
Definition at line 1147 of file OSParseosrl.cpp.
#define YY_EXTRA_TYPE OSrLParserData*
Definition at line 1168 of file OSParseosrl.cpp.
#define INITIAL 0
Definition at line 1171 of file OSParseosrl.cpp.
#define attributetext 1
Definition at line 1172 of file OSParseosrl.cpp.
#define osrlattributetext 2
Definition at line 1173 of file OSParseosrl.cpp.
#define comment 3
Definition at line 1174 of file OSParseosrl.cpp.
#define xmldeclaration 4
Definition at line 1175 of file OSParseosrl.cpp.
#define yylval yyg->yylval_r
Definition at line 1231 of file OSParseosrl.cpp.
#define yylloc yyg->yylloc_r
Definition at line 1233 of file OSParseosrl.cpp.
#define YY_READ_BUF_SIZE 8192
Definition at line 1306 of file OSParseosrl.cpp.
#define ECHO (void) fwrite(yytext, yyleng, 1, yyout)
Definition at line 1314 of file OSParseosrl.cpp.
#define YY_INPUT (buf, result, max_size)
Value:
if (YY_CURRENT_BUFFER_LVALUE->yy_is_interactive) \
                { \
                int c = '*'; \
                size_t n; \
                for ( n = 0; n < max_size && \
                             (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
                        buf[n] = (char) c; \
                if ( c == '\n' ) \
                        buf[n++] = (char) c; \
                if ( c == EOF && ferror( yyin ) ) \
                        YY_FATAL_ERROR( "input in flex scanner failed" ); \
                result = n; \
                } \
        else \
                { \
                errno=0; \
                while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
                        { \
                        if( errno != EINTR) \
                                { \
                                YY_FATAL_ERROR( "input in flex scanner failed" ); \
                                break; \
                                } \
                        errno=0; \
                        clearerr(yyin); \
                        } \
                }\
\
Definition at line 1321 of file OSParseosrl.cpp.
#define yyterminate () return YY_NULL
Definition at line 1358 of file OSParseosrl.cpp.
#define YY_START_STACK_INCR 25
Definition at line 1363 of file OSParseosrl.cpp.
#define YY_FATAL_ERROR (msg) yy_fatal_error(msg , yyscanner)
Definition at line 1368 of file OSParseosrl.cpp.
#define YY_DECL_IS_OURS 1
Definition at line 1377 of file OSParseosrl.cpp.
#define YY_DECL int osrllex (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner)
Definition at line 1381 of file OSParseosrl.cpp.
#define YY_BREAK break;
Definition at line 1393 of file OSParseosrl.cpp.
#define YY_RULE_SETUP YY_USER_ACTION
Definition at line 1396 of file OSParseosrl.cpp.
#define YY_EXIT_FAILURE 2
Definition at line 2803 of file OSParseosrl.cpp.
#define yyless (n)
Value:
do \
                { \
                /* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
                yytext[yyleng] = yyg->yy_hold_char; \
                yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
                yyg->yy_hold_char = *yyg->yy_c_buf_p; \
                *yyg->yy_c_buf_p = '\0'; \
                yyleng = yyless_macro_arg; \
                } \
        while ( 0 )
Definition at line 2815 of file OSParseosrl.cpp.
#define YYTABLES_NAME "yytables"
Definition at line 3136 of file OSParseosrl.cpp.
Typedef Documentation
typedef signed char flex_int8_t
Definition at line 51 of file OSParseosrl.cpp.
typedef short int flex_int16_t
Definition at line 52 of file OSParseosrl.cpp.
typedef int flex_int32_t
Definition at line 53 of file OSParseosrl.cpp.
typedef unsigned char flex_uint8_t
Definition at line 54 of file OSParseosrl.cpp.
typedef unsigned short int flex_uint16_t
Definition at line 55 of file OSParseosrl.cpp.
typedef unsigned int flex_uint32_t
Definition at line 56 of file OSParseosrl.cpp.
typedef void* yyscan_t
Definition at line 123 of file OSParseosrl.cpp.
typedef struct yy_buffer_state* YY_BUFFER_STATE
Definition at line 171 of file OSParseosrl.cpp.
typedef unsigned int yy_size_t
Definition at line 216 of file OSParseosrl.cpp.
typedef unsigned char YY_CHAR
Definition at line 350 of file OSParseosrl.cpp.
typedef int yy_state_type
Definition at line 352 of file OSParseosrl.cpp.
Function Documentation
int osrllex_init (yyscan_t * scanner)
void osrlrestart (FILE * input_file, yyscan_t yyscanner)
void osrl_switch_to_buffer (YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
Referenced by osrl_scan_buffer().
YY_BUFFER_STATE osrl_create_buffer (FILE * file, int size, yyscan_t yyscanner)
void osrl_delete_buffer (YY_BUFFER_STATE b, yyscan_t yyscanner)
Referenced by osrllex_destroy(), and osrlpop_buffer_state().
void osrl_flush_buffer (YY_BUFFER_STATE b, yyscan_t yyscanner)
Discard all buffered characters.
On the next scan, YY_INPUT will be called.
Parameters:
b the buffer state to be flushed, usually YY_CURRENT_BUFFER.
yyscanner The scanner object.
Definition at line 2595 of file OSParseosrl.cpp.
References osrl_load_buffer_state(), yy_buffer_state::yy_at_bol, yy_buffer_state::yy_buf_pos, YY_BUFFER_NEW, yy_buffer_state::yy_buffer_status, yy_buffer_state::yy_ch_buf, YY_CURRENT_BUFFER, YY_END_OF_BUFFER_CHAR, and yy_buffer_state::yy_n_chars.
Referenced by osrl_init_buffer().
void osrlpush_buffer_state (YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
Pushes the new state onto the stack.
The new state becomes the current state. This function will allocate the stack if necessary.
Parameters:
new_buffer The new state.
yyscanner The scanner object.
Definition at line 2625 of file OSParseosrl.cpp.
References osrl_load_buffer_state(), osrlensure_buffer_stack(), yyguts_t::yy_buffer_stack_top, yyguts_t::yy_c_buf_p, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_did_buffer_switch_on_eof, yyguts_t::yy_hold_char, and yyguts_t::yy_n_chars.
void osrlpop_buffer_state (yyscan_t yyscanner)
Removes and deletes the top of the stack, if present.
The next element becomes the new top.
Parameters:
yyscanner The scanner object.
Definition at line 2656 of file OSParseosrl.cpp.
References osrl_delete_buffer(), osrl_load_buffer_state(), yyguts_t::yy_buffer_stack_top, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, and yyguts_t::yy_did_buffer_switch_on_eof.
Referenced by osrllex_destroy().
static void osrlensure_buffer_stack (yyscan_t yyscanner) [static]
Definition at line 2676 of file OSParseosrl.cpp.
References osrlalloc(), osrlrealloc(), yyguts_t::yy_buffer_stack, yyguts_t::yy_buffer_stack_max, and yyguts_t::yy_buffer_stack_top.
Referenced by osrlpush_buffer_state().
static void osrl_load_buffer_state (yyscan_t yyscanner) [static]
Referenced by osrl_flush_buffer(), osrlpop_buffer_state(), and osrlpush_buffer_state().
static void osrl_init_buffer (YY_BUFFER_STATE b, FILE * file, yyscan_t yyscanner) [static]
The main scanner function which does all the work.
Definition at line 2566 of file OSParseosrl.cpp.
References osrl_flush_buffer(), yy_buffer_state::yy_bs_column, yy_buffer_state::yy_bs_lineno, YY_CURRENT_BUFFER, yy_buffer_state::yy_fill_buffer, yy_buffer_state::yy_input_file, and yy_buffer_state::yy_is_interactive.
YY_BUFFER_STATE osrl_scan_buffer (char * base, yy_size_t size, yyscan_t yyscanner)
Setup the input buffer state to scan directly from a user-specified character buffer.
Parameters:
base the character buffer
size the size in bytes of the character buffer
yyscanner The scanner object.
Returns:
the newly allocated buffer state object.
Definition at line 2722 of file OSParseosrl.cpp.
References osrl_switch_to_buffer(), osrlalloc(), yy_buffer_state::yy_at_bol, yy_buffer_state::yy_buf_pos, yy_buffer_state::yy_buf_size, YY_BUFFER_NEW, yy_buffer_state::yy_buffer_status, yy_buffer_state::yy_ch_buf, YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, yy_buffer_state::yy_fill_buffer, yy_buffer_state::yy_input_file, yy_buffer_state::yy_is_interactive, yy_buffer_state::yy_is_our_buffer, and yy_buffer_state::yy_n_chars.
Referenced by osrl_scan_bytes().
YY_BUFFER_STATE osrl_scan_string (yyconst char * yystr, yyscan_t yyscanner)
Setup the input buffer state to scan a string.
The next call to osrllex() will scan from a copy of str.
Parameters:
str a NUL-terminated string to scan
yyscanner The scanner object.
Returns:
the newly allocated buffer state object.
Note:
If you want to scan bytes that may contain NUL values, then use osrl_scan_bytes() instead.
Definition at line 2759 of file OSParseosrl.cpp.
References osrl_scan_bytes().
YY_BUFFER_STATE osrl_scan_bytes (yyconst char * yybytes, int _yybytes_len, yyscan_t yyscanner)
Setup the input buffer state to scan the given bytes.
The next call to osrllex() will scan from a copy of bytes.
Parameters:
bytes the byte buffer to scan
len the number of bytes in the buffer pointed to by bytes.
yyscanner The scanner object.
Returns:
the newly allocated buffer state object.
Definition at line 2772 of file OSParseosrl.cpp.
References osrl_scan_buffer(), osrlalloc(), YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, and yy_buffer_state::yy_is_our_buffer.
Referenced by osrl_scan_string().
void * osrlalloc (yy_size_t size, yyscan_t yyscanner)
Definition at line 3114 of file OSParseosrl.cpp.
Referenced by osrl_scan_buffer(), osrl_scan_bytes(), osrlensure_buffer_stack(), and osrllex_init().
void * osrlrealloc (void * ptr, yy_size_t size, yyscan_t yyscanner)
Definition at line 3119 of file OSParseosrl.cpp.
Referenced by osrlensure_buffer_stack().
void osrlfree (void * ptr, yyscan_t yyscanner)
Definition at line 3131 of file OSParseosrl.cpp.
Referenced by osrllex_destroy().
static yy_state_type yy_get_previous_state (yyscan_t yyscanner) [static]
static yy_state_type yy_try_NUL_trans (yy_state_type current_state, yyscan_t yyscanner) [static]
static int yy_get_next_buffer (yyscan_t yyscanner) [static]
static void yy_fatal_error (yyconst char msg[], yyscan_t yyscanner) [static]
static int yy_init_globals (yyscan_t yyscanner) [static]
Definition at line 3027 of file OSParseosrl.cpp.
References yyguts_t::yy_buffer_stack, yyguts_t::yy_buffer_stack_max, yyguts_t::yy_buffer_stack_top, yyguts_t::yy_c_buf_p, yyguts_t::yy_init, yyguts_t::yy_start, yyguts_t::yy_start_stack, yyguts_t::yy_start_stack_depth, yyguts_t::yy_start_stack_ptr, yyin, and yyout.
int osrllex_destroy (yyscan_t yyscanner)
int osrlget_debug (yyscan_t yyscanner)
Definition at line 2961 of file OSParseosrl.cpp.
References yy_flex_debug.
void osrlset_debug (int debug_flag, yyscan_t yyscanner)
Definition at line 2967 of file OSParseosrl.cpp.
References yy_flex_debug.
YY_EXTRA_TYPE osrlget_extra (yyscan_t yyscanner)
Get the user-defined data for this scanner.
Parameters:
yyscanner The scanner object.
Definition at line 2834 of file OSParseosrl.cpp.
References yyextra.
void osrlset_extra (YY_EXTRA_TYPE user_defined, yyscan_t yyscanner)
Set the user-defined data.
This data is never touched by the scanner.
Parameters:
user_defined The data to be associated with this scanner.
yyscanner The scanner object.
Definition at line 2907 of file OSParseosrl.cpp.
References yyextra.
FILE * osrlget_in (yyscan_t yyscanner)
Get the input stream.
Parameters:
yyscanner The scanner object.
Definition at line 2869 of file OSParseosrl.cpp.
References yyin.
void osrlset_in (FILE * in_str, yyscan_t yyscanner)
Set the input stream.
This does not discard the current input buffer.
Parameters:
in_str A readable stream.
yyscanner The scanner object.
See also:
osrl_switch_to_buffer
Definition at line 2949 of file OSParseosrl.cpp.
References yyin.
FILE * osrlget_out (yyscan_t yyscanner)
Get the output stream.
Parameters:
yyscanner The scanner object.
Definition at line 2878 of file OSParseosrl.cpp.
References yyout.
void osrlset_out (FILE * out_str, yyscan_t yyscanner)
Definition at line 2955 of file OSParseosrl.cpp.
References yyout.
int osrlget_leng (yyscan_t yyscanner)
Get the length of the current token.
Parameters:
yyscanner The scanner object.
Definition at line 2887 of file OSParseosrl.cpp.
References yyleng.
char * osrlget_text (yyscan_t yyscanner)
Get the current token.
Parameters:
yyscanner The scanner object.
Definition at line 2897 of file OSParseosrl.cpp.
References yytext.
int osrlget_lineno (yyscan_t yyscanner)
Get the current line number.
Parameters:
yyscanner The scanner object.
Definition at line 2843 of file OSParseosrl.cpp.
References YY_CURRENT_BUFFER, and yylineno.
void osrlset_lineno (int line_number, yyscan_t yyscanner)
Set the current line number.
Parameters:
line_number
yyscanner The scanner object.
Definition at line 2917 of file OSParseosrl.cpp.
References YY_CURRENT_BUFFER, yy_fatal_error(), and yylineno.
YYSTYPE * osrlget_lval (yyscan_t yyscanner)
Definition at line 2975 of file OSParseosrl.cpp.
References yylval.
void osrlset_lval (YYSTYPE * yylval_param, yyscan_t yyscanner)
Definition at line 2981 of file OSParseosrl.cpp.
References yylval.
YYLTYPE * osrlget_lloc (yyscan_t yyscanner)
Definition at line 2987 of file OSParseosrl.cpp.
References yylloc.
void osrlset_lloc (YYLTYPE * yylloc_param, yyscan_t yyscanner)
Definition at line 2993 of file OSParseosrl.cpp.
References yylloc.
static void yyunput (int c, char * buf_ptr, yyscan_t yyscanner) [static]
static int input (yyscan_t yyscanner) [static]
int osrllex (YYSTYPE * yylval_param, YYLTYPE * yylloc_param, yyscan_t yyscanner)
static void yy_fatal_error (yyconst char * msg, yyscan_t yyscanner) [static]
Definition at line 2806 of file OSParseosrl.cpp.
References YY_EXIT_FAILURE.
int osrlget_column (yyscan_t yyscanner)
Get the current column number.
Parameters:
yyscanner The scanner object.
Definition at line 2856 of file OSParseosrl.cpp.
References YY_CURRENT_BUFFER, and yycolumn.
void osrlset_column (int column_no, yyscan_t yyscanner)
Set the current column.
Parameters:
line_number
yyscanner The scanner object.
Definition at line 2932 of file OSParseosrl.cpp.
References YY_CURRENT_BUFFER, yy_fatal_error(), and yycolumn.
Variable Documentation
yyconst flex_int16_t yy_accept[719] [static]
Definition at line 380 of file OSParseosrl.cpp.
yyconst flex_int32_t yy_ec[256] [static]
Definition at line 463 of file OSParseosrl.cpp.
yyconst flex_int32_t yy_meta[53] [static]
Initial value:
    {   0,
        1,    2,    2,    2,    1,    3,    2,    3,    1,    1,
        2,    2,    2,    2,    1,    4,    1,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2
    }
Definition at line 495 of file OSParseosrl.cpp.
yyconst flex_int16_t yy_base[727] [static]
Definition at line 505 of file OSParseosrl.cpp.
yyconst flex_int16_t yy_def[727] [static]
Definition at line 589 of file OSParseosrl.cpp.
yyconst flex_int16_t yy_nxt[1820] [static]
Definition at line 673 of file OSParseosrl.cpp.
yyconst flex_int16_t yy_chk[1820] [static]
Definition at line 877 of file OSParseosrl.cpp.
yyconst flex_int32_t yy_rule_can_match_eol[82] [static]
Initial value:
    {   0,
1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
    1, 0,     }
Definition at line 1082 of file OSParseosrl.cpp.