/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSModelInterfaces/OSMatlabSolver.cpp File Reference
/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSModelInterfaces/OSMatlabSolver.cpp File Reference
#include <iostream>
#include <string>
#include "mex.h"
#include "OSDataStructures.h"
#include "OSParameters.h"
#include "OSMatlab.h"
Defines
#define IsNonZero(d) ((d)!=0.0)
Functions
void mexFunction (int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
SparseMatrix * getConstraintMatrix (const mxArray *prhs)
Define Documentation
#define IsNonZero (d) ((d)!=0.0)
Definition at line 26 of file OSMatlabSolver.cpp.
Referenced by getConstraintMatrix().
Function Documentation
void mexFunction (int nlhs, mxArray * plhs[], int nrhs, const mxArray * prhs[])
The parameters are: A -- the constraint matrix BU -- upper bounds on the constraints BL -- lower bounds on the constraints C -- objective function vector VL -- lower bounds on the variables VU -- upper bounds on the variables ObjType -- 1 for max, 0 for min
Definition at line 34 of file OSMatlabSolver.cpp.
References OSMatlab::bl, OSMatlab::bu, OSMatlab::createOSInstance(), getConstraintMatrix(), OSMatlab::instanceName, OSMatlab::numCon, OSMatlab::numQTerms, OSMatlab::numVar, OSMatlab::obj, OSMatlab::objType, OSMatlab::osil, OSMatlab::qIndex1, OSMatlab::qIndex2, OSMatlab::qRows, OSMatlab::qVal, OSMatlab::sAgentAddress, OSMatlab::solve(), OSMatlab::sparseMat, OSMatlab::sSolverName, OSMatlab::varType, OSMatlab::vl, and OSMatlab::vu.
SparseMatrix* getConstraintMatrix (const mxArray * prhs)
Definition at line 222 of file OSMatlabSolver.cpp.
References SparseMatrix::bDeleteArrays, SparseMatrix::indexes, SparseMatrix::isColumnMajor, IsNonZero, SparseMatrix::starts, SparseMatrix::startSize, SparseMatrix::values, and SparseMatrix::valueSize.
Referenced by mexFunction().