/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSCommonInterfaces/OSrLReader.cpp File Reference
/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSCommonInterfaces/OSrLReader.cpp File Reference
Author:
Robert Fourer, Jun Ma, Kipp Martin,
#include "OSrLReader.h"
Functions
void yygetOSResult (const char *ch, OSResult *m_osresult, OSrLParserData *m_parserData) throw (ErrorClass)
int osrllex_init (void **ptr_yy_globals)
int osrllex_destroy (void *scanner)
void osrlset_extra (OSrLParserData *parserData, void *yyscanner)
Detailed Description
Author:
Robert Fourer, Jun Ma, Kipp Martin,
Version:
1.0, 10/05/2005
Since:
OS1.0
Remarks:
Copyright (C) 2005, Robert Fourer, Jun Ma, Kipp Martin, Northwestern University, and the University of Chicago. All Rights Reserved. This software is licensed under the Common Public License. Please see the accompanying LICENSE file in root directory for terms.
Definition in file OSrLReader.cpp.
Function Documentation
void yygetOSResult (const char * ch, OSResult * m_osresult, OSrLParserData * m_parserData) throw (ErrorClass)
Referenced by OSrLReader::readOSrL().
int osrllex_init (void ** ptr_yy_globals)
Definition at line 3006 of file OSParseosrl.cpp.
References osrlalloc(), and yy_init_globals().
Referenced by OSrLReader::OSrLReader().
int osrllex_destroy (void * scanner)
Definition at line 3061 of file OSParseosrl.cpp.
References osrl_delete_buffer(), osrlfree(), osrlpop_buffer_state(), yyguts_t::yy_buffer_stack, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yy_init_globals(), and yyguts_t::yy_start_stack.
Referenced by OSrLReader::~OSrLReader().
void osrlset_extra (OSrLParserData * parserData, void * yyscanner)
Referenced by OSrLReader::OSrLReader().