CommonUtil Class Reference
CommonUtil Class Reference
common utilities for OS classes.
#include <OSCommonUtil.h>
Public Member Functions
CommonUtil ()
Class constructor.
~CommonUtil ()
Class destructor.
Static Public Member Functions
static bool ISOSNAN (double number)
encode the data in base 64
Detailed Description
common utilities for OS classes.
Author:
Robert Fourer, Jun Ma, Kipp Martin
Version:
1.0, 03/14/2004
Since:
OS 1.0
Remarks:
The CommonUtil class contains methods for performing common operations used by many classes in the Optimization Services (OS) framework.
Definition at line 37 of file OSCommonUtil.h.
Constructor & Destructor Documentation
CommonUtil::CommonUtil ()
Class constructor.
Definition at line 23 of file OSCommonUtil.cpp.
CommonUtil::~CommonUtil ()
Class destructor.
Definition at line 26 of file OSCommonUtil.cpp.
Member Function Documentation
bool CommonUtil::ISOSNAN (double number) [static]
encode the data in base 64
Parameters:
number is a double number that is input
Returns:
true if the number is an OS NAN.
Definition at line 44 of file OSCommonUtil.cpp.
References OSNAN.
Referenced by IpoptProblem::eval_f(), IpoptProblem::eval_g(), KnitroProblem::evalFC(), KnitroProblem::evalGA(), IpoptProblem::get_starting_point(), KnitroProblem::loadProblemIntoKnitro(), OSInstance::processVariables(), and OSiLWriter::writeOSiL().
The documentation for this class was generated from the following files:
/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSUtils/OSCommonUtil.h
/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSUtils/OSCommonUtil.cpp