OSrLWriter Class Reference
OSrLWriter Class Reference
Take an OSResult object and write a string that validates against OSrL..
#include <OSrLWriter.h>
Public Member Functions
OSrLWriter ()
Default constructor.
~OSrLWriter ()
Class destructor.
std::string writeOSrL (OSResult *theosresult)
create an osrl string from an OSResult object
Private Attributes
OSResult * m_OSResult
m_OSResult is an object in the class OSResult, the data in m_OSResult are written to a string that validates against OSrL
Detailed Description
Take an OSResult object and write a string that validates against OSrL..
Definition at line 31 of file OSrLWriter.h.
Constructor & Destructor Documentation
OSrLWriter::OSrLWriter ()
Default constructor.
Definition at line 35 of file OSrLWriter.cpp.
OSrLWriter::~OSrLWriter ()
Class destructor.
Definition at line 38 of file OSrLWriter.cpp.
Member Function Documentation
std::string OSrLWriter::writeOSrL (OSResult * theosresult)
create an osrl string from an OSResult object
Parameters:
theosresult is a pointer to an OSResult object
Returns:
a string with the OSResult data that validates against the OSrL schema.
Definition at line 55 of file OSrLWriter.cpp.
References OtherConstraintResult::con, DualVariableValues::con, ConstraintValues::con, OptimizationSolution::constraints, OtherConstraintResult::description, OtherObjectiveResult::description, OtherVariableResult::description, OptimizationSolutionStatus::description, GeneralStatus::description, ConstraintSolution::dualValues, ResultHeader::generalStatus, ResultHeader::instanceName, ResultHeader::jobID, m_OSResult, OptimizationSolution::message, ResultHeader::message, OtherConstraintResult::name, OtherObjectiveResult::name, OtherVariableResult::name, OptimizationResult::numberOfConstraints, OptimizationResult::numberOfObjectives, ConstraintSolution::numberOfOtherConstraintResult, ObjectiveSolution::numberOfOtherObjectiveResult, VariableSolution::numberOfOtherVariableResult, OptimizationResult::numberOfSolutions, OptimizationResult::numberOfVariables, OtherObjectiveResult::obj, ObjectiveValues::obj, OptimizationSolution::objectiveIdx, OptimizationSolution::objectives, ResultData::optimization, ConstraintSolution::other, ObjectiveSolution::other, VariableSolution::other, OSResult::resultData, OSResult::resultHeader, ResultHeader::serviceName, ResultHeader::serviceURI, OptimizationResult::solution, OptimizationSolution::status, ResultHeader::time, OptimizationSolutionStatus::type, GeneralStatus::type, ConstraintSolution::values, ObjectiveSolution::values, VariableSolution::values, OtherVariableResult::var, VariableValues::var, and OptimizationSolution::variables.
Referenced by LindoSolver::buildSolverInstance(), KnitroSolver::buildSolverInstance(), IpoptSolver::buildSolverInstance(), CoinSolver::buildSolverInstance(), IpoptProblem::finalize_solution(), LindoSolver::generateLindoModel(), CoinSolver::getCoinSolverType(), getJobID(), kill(), knock(), main(), LindoSolver::optimize(), LindoSolver::processConstraints(), LindoSolver::processNonlinearExpressions(), LindoSolver::processQuadraticTerms(), LindoSolver::processVariables(), retrieve(), send(), CoinSolver::setCoinPackedMatrix(), solve(), LindoSolver::solve(), KnitroSolver::solve(), IpoptSolver::solve(), and CoinSolver::solve().
Member Data Documentation
OSResult* OSrLWriter::m_OSResult [private]
m_OSResult is an object in the class OSResult, the data in m_OSResult are written to a string that validates against OSrL
Definition at line 37 of file OSrLWriter.h.
Referenced by writeOSrL().
The documentation for this class was generated from the following files:
/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSCommonInterfaces/OSrLWriter.h
/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSCommonInterfaces/OSrLWriter.cpp