OSiLReader Class Reference
OSiLReader Class Reference
Used to read an OSiL string.
#include <OSiLReader.h>
Public Member Functions
OSiLReader ()
Default constructor.
~OSiLReader ()
Class destructor.
OSInstance * readOSiL (const std::string &osil) throw (ErrorClass)
parse the OSiL model instance.
Private Attributes
OSInstance * m_osinstance
osintance is the OSInstance object returned by the OSiLReader
OSiLParserData * m_parserData
parerData is the object used in the parser to temporarily store data
Detailed Description
Used to read an OSiL string.
Remarks:
This class wraps around the OSiL parser and sends the parser an OSiL string and is returned an OSInstance object.
Definition at line 37 of file OSiLReader.h.
Constructor & Destructor Documentation
OSiLReader::OSiLReader ()
Default constructor.
Definition at line 28 of file OSiLReader.cpp.
References m_osinstance, m_parserData, osillex_init(), osilset_extra(), and OSiLParserData::scanner.
OSiLReader::~OSiLReader ()
Class destructor.
Definition at line 36 of file OSiLReader.cpp.
References m_osinstance, m_parserData, osillex_destroy(), and OSiLParserData::scanner.
Member Function Documentation
OSInstance * OSiLReader::readOSiL (const std::string & osil) throw (ErrorClass)
parse the OSiL model instance.
Parameters:
osil a string that holds the problem instance.
Returns:
the instance as an OSInstance object.
Definition at line 45 of file OSiLReader.cpp.
References ErrorClass::errormsg, m_osinstance, m_parserData, and yygetOSInstance().
Referenced by LindoSolver::buildSolverInstance(), IpoptSolver::buildSolverInstance(), CoinSolver::buildSolverInstance(), main(), solve(), and KnitroSolver::solve().
Member Data Documentation
OSInstance* OSiLReader::m_osinstance [private]
osintance is the OSInstance object returned by the OSiLReader
Definition at line 65 of file OSiLReader.h.
Referenced by OSiLReader(), readOSiL(), and ~OSiLReader().
OSiLParserData* OSiLReader::m_parserData [private]
parerData is the object used in the parser to temporarily store data
Definition at line 69 of file OSiLReader.h.
Referenced by OSiLReader(), readOSiL(), and ~OSiLReader().
The documentation for this class was generated from the following files:
/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSCommonInterfaces/OSiLReader.h
/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSCommonInterfaces/OSiLReader.cpp