OSnLNodeIf Class Reference
OSnLNodeIf Class Reference
The OSnLNodeIf Class.
#include <OSnLNode.h>
Public Member Functions
OSnLNodeIf ()
default constructor.
~OSnLNodeIf ()
default destructor.
virtual double calculateFunction (double *x)
virtual OSnLNode * cloneOSnLNode ()
virtual AD< double > constructCppADTape (std::map< int, int > *cppADIdx, CppAD::vector< AD< double > > *XAD)
The implementation of the virtual functions.
Detailed Description
The OSnLNodeIf Class.
Author:
Robert Fourer, Jun Ma, Kipp Martin,
Version:
1.0, 10/05/2005
Since:
OS1.0
Remarks:
The in-memory representation of the OSnL element <if>
Definition at line 1028 of file OSnLNode.h.
Constructor & Destructor Documentation
OSnLNodeIf::OSnLNodeIf ()
default constructor.
Definition at line 1290 of file OSnLNode.cpp.
References OSnLNode::inodeInt, OSnLNode::inodeType, OSnLNode::inumberOfChildren, OSnLNode::m_mChildren, and OSnLNode::snodeName.
Referenced by cloneOSnLNode().
OSnLNodeIf::~OSnLNodeIf ()
default destructor.
Definition at line 1303 of file OSnLNode.cpp.
References OSnLNode::inumberOfChildren, and OSnLNode::m_mChildren.
Member Function Documentation
double OSnLNodeIf::calculateFunction (double * x) [virtual]
Calculate the function value given the current variable values. This is an abstract method which is required to be implemented by the concrete operator nodes that derive or extend from this OSnLNode class.
Parameters:
x holds the values of the variables in a double array.
Returns:
the function value given the current variable values.
Implements OSnLNode.
Definition at line 1315 of file OSnLNode.cpp.
References OSnLNode::calculateFunction(), OSnLNode::m_dFunctionValue, and OSnLNode::m_mChildren.
OSnLNode * OSnLNodeIf::cloneOSnLNode () [virtual]
Create or clone a node of this type. This is an abstract method which is required to be implemented by the concrete operator nodes that derive or extend from this OSnLNode class.
Parameters:
x holds the values of the variables in a double array.
Returns:
the function value given the current variable values.
Implements OSnLNode.
Definition at line 1332 of file OSnLNode.cpp.
References OSnLNodeIf().
double OSnLNodeIf::constructCppADTape (std::map< int, int > * cppADIdx, CppAD::vector< AD< double > > * XAD) [virtual]
The implementation of the virtual functions.
Returns:
a AD<double>.
Implements OSnLNode.
Definition at line 1321 of file OSnLNode.cpp.
References ErrorClass::errormsg, and OSnLNode::m_CppADTape.
The documentation for this class was generated from the following files:
/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSCommonInterfaces/OSnLNode.h
/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSCommonInterfaces/OSnLNode.cpp