OSnLNodeMin Class Reference
OSnLNodeMin Class Reference
The OSnLNodeMin Class.
#include <OSnLNode.h>
Public Member Functions
OSnLNodeMin ()
default constructor.
~OSnLNodeMin ()
default destructor.
virtual double calculateFunction (double *x)
virtual OSnLNode * cloneOSnLNode ()
virtual AD< double > constructCppADTape (std::map< int, int > *cppADIdx, CppAD::vector< AD< double > > *XAD)
The implementation of the virtual functions.
Detailed Description
The OSnLNodeMin Class.
Author:
Robert Fourer, Jun Ma, Kipp Martin,
Version:
1.0, 10/05/2005
Since:
OS1.0
Remarks:
The in-memory representation of the OSnL element <min>
Definition at line 402 of file OSnLNode.h.
Constructor & Destructor Documentation
OSnLNodeMin::OSnLNodeMin ()
default constructor.
Definition at line 612 of file OSnLNode.cpp.
References OSnLNode::inodeInt, OSnLNode::inodeType, OSnLNode::inumberOfChildren, and OSnLNode::snodeName.
Referenced by cloneOSnLNode().
OSnLNodeMin::~OSnLNodeMin ()
default destructor.
Definition at line 620 of file OSnLNode.cpp.
References OSnLNode::inumberOfChildren, and OSnLNode::m_mChildren.
Member Function Documentation
double OSnLNodeMin::calculateFunction (double * x) [virtual]
Calculate the function value given the current variable values. This is an abstract method which is required to be implemented by the concrete operator nodes that derive or extend from this OSnLNode class.
Parameters:
x holds the values of the variables in a double array.
Returns:
the function value given the current variable values.
Implements OSnLNode.
Definition at line 634 of file OSnLNode.cpp.
References OSnLNode::calculateFunction(), OSnLNode::inumberOfChildren, OSnLNode::m_dFunctionValue, and OSnLNode::m_mChildren.
OSnLNode * OSnLNodeMin::cloneOSnLNode () [virtual]
Create or clone a node of this type. This is an abstract method which is required to be implemented by the concrete operator nodes that derive or extend from this OSnLNode class.
Parameters:
x holds the values of the variables in a double array.
Returns:
the function value given the current variable values.
Implements OSnLNode.
Definition at line 659 of file OSnLNode.cpp.
References OSnLNodeMin().
double OSnLNodeMin::constructCppADTape (std::map< int, int > * cppADIdx, CppAD::vector< AD< double > > * XAD) [virtual]
The implementation of the virtual functions.
Returns:
a AD<double>.
Implements OSnLNode.
Definition at line 647 of file OSnLNode.cpp.
References ErrorClass::errormsg, and OSnLNode::m_CppADTape.
The documentation for this class was generated from the following files:
/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSCommonInterfaces/OSnLNode.h
/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSCommonInterfaces/OSnLNode.cpp