KnitroProblem Class Reference
KnitroProblem Class Reference
#include <OSKnitroSolver.h>
Public Member Functions
KnitroProblem (OSInstance *osinstance_, OSResult *osresult_)
the IpoptProblemclass constructor
virtual ~KnitroProblem ()
the IpoptProblem class destructor
int getN (void)
int getM (void)
void getInitialX (double *const daX)
bool loadProblemIntoKnitro (KTR_context_ptr kc)
Define the fixed problem definition information and pass it to KNITRO by calling KTR_init_problem.
bool areDerivativesImplemented (const DerivativesImplementedType nWhichDers)
int evalFC (const double *const daX, double *const dObj, double *const daC, void *userParams)
int evalGA (const double *const daX, double *const daG, double *const daJ, void *userParams)
int evalH (const double *const daX, const double *const daLambda, double *const daH, void *userParams)
int evalHV (const double *const daX, const double *const daLambda, double *const daHV, void *userParams)
Public Attributes
OSResult * osresult
OSInstance * osinstance
std::string knitroErrorMsg
Detailed Description
Definition at line 86 of file OSKnitroSolver.h.
Constructor & Destructor Documentation
KnitroProblem::KnitroProblem (OSInstance * osinstance_, OSResult * osresult_)
the IpoptProblemclass constructor
Definition at line 183 of file OSKnitroSolver.cpp.
References osinstance, and osresult.
KnitroProblem::~KnitroProblem () [virtual]
the IpoptProblem class destructor
Definition at line 192 of file OSKnitroSolver.cpp.
Member Function Documentation
int KnitroProblem::getN (void)
Definition at line 203 of file OSKnitroSolver.cpp.
int KnitroProblem::getM (void)
Definition at line 208 of file OSKnitroSolver.cpp.
void KnitroProblem::getInitialX (double *const daX)
Definition at line 213 of file OSKnitroSolver.cpp.
bool KnitroProblem::loadProblemIntoKnitro (KTR_context_ptr kc)
Define the fixed problem definition information and pass it to KNITRO by calling KTR_init_problem.
Definition at line 231 of file OSKnitroSolver.cpp.
References OSInstance::bUseExpTreeForFunEval, ErrorClass::errormsg, OSInstance::getConstraintLowerBounds(), OSInstance::getConstraintNumber(), OSInstance::getConstraintUpperBounds(), OSInstance::getJacobianSparsityPattern(), OSInstance::getLagrangianHessianSparsityPattern(), OSInstance::getNumberOfNonlinearExpressions(), OSInstance::getNumberOfQuadraticTerms(), OSInstance::getObjectiveNumber(), OSInstance::getVariableInitialValues(), OSInstance::getVariableLowerBounds(), OSInstance::getVariableNumber(), OSInstance::getVariableUpperBounds(), SparseHessianMatrix::hessColIdx, SparseHessianMatrix::hessDimension, SparseHessianMatrix::hessRowIdx, SparseJacobianMatrix::indexes, OSInstance::initForAlgDiff(), OSInstance::instanceData, CommonUtil::ISOSNAN(), knitroErrorMsg, Objective::maxOrMin, Objectives::obj, InstanceData::objectives, OSDBL_MAX, osinstance, SparseJacobianMatrix::starts, and SparseJacobianMatrix::valueSize.
bool KnitroProblem::areDerivativesImplemented (const DerivativesImplementedType nWhichDers)
Definition at line 395 of file OSKnitroSolver.cpp.
int KnitroProblem::evalFC (const double *const daX, double *const dObj, double *const daC, void * userParams)
Definition at line 409 of file OSKnitroSolver.cpp.
References OSInstance::calculateAllConstraintFunctionValues(), OSInstance::calculateAllObjectiveFunctionValues(), ErrorClass::errormsg, CommonUtil::ISOSNAN(), knitroErrorMsg, and osinstance.
int KnitroProblem::evalGA (const double *const daX, double *const daG, double *const daJ, void * userParams)
Definition at line 445 of file OSKnitroSolver.cpp.
References OSInstance::calculateAllConstraintFunctionGradients(), OSInstance::calculateAllObjectiveFunctionGradients(), ErrorClass::errormsg, CommonUtil::ISOSNAN(), knitroErrorMsg, osinstance, and SparseJacobianMatrix::values.
int KnitroProblem::evalH (const double *const daX, const double *const daLambda, double *const daH, void * userParams)
Definition at line 487 of file OSKnitroSolver.cpp.
References OSInstance::calculateLagrangianHessian(), ErrorClass::errormsg, SparseHessianMatrix::hessValues, knitroErrorMsg, and osinstance.
int KnitroProblem::evalHV (const double *const daX, const double *const daLambda, double *const daHV, void * userParams)
Definition at line 514 of file OSKnitroSolver.cpp.
Member Data Documentation
OSResult* KnitroProblem::osresult
Definition at line 95 of file OSKnitroSolver.h.
Referenced by KnitroProblem().
OSInstance* KnitroProblem::osinstance
Definition at line 97 of file OSKnitroSolver.h.
Referenced by evalFC(), evalGA(), evalH(), KnitroProblem(), and loadProblemIntoKnitro().
std::string KnitroProblem::knitroErrorMsg
Definition at line 126 of file OSKnitroSolver.h.
Referenced by evalFC(), evalGA(), evalH(), and loadProblemIntoKnitro().
The documentation for this class was generated from the following files:
/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSSolverInterfaces/OSKnitroSolver.h
/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSSolverInterfaces/OSKnitroSolver.cpp