OSnLNodeMinus Class Reference
OSnLNodeMinus Class Reference
The OSnLNodeMinus Class.
#include <OSnLNode.h>
Public Member Functions
OSnLNodeMinus ()
default constructor.
~OSnLNodeMinus ()
default destructor.
virtual double calculateFunction (double *x)
virtual OSnLNode * cloneOSnLNode ()
virtual AD< double > constructCppADTape (std::map< int, int > *cppADIdx, CppAD::vector< AD< double > > *XAD)
The implementation of the virtual functions.
Detailed Description
The OSnLNodeMinus Class.
Author:
Robert Fourer, Jun Ma, Kipp Martin,
Version:
1.0, 10/05/2005
Since:
OS1.0
Remarks:
The in-memory representation of the OSnL element <minus>
Definition at line 448 of file OSnLNode.h.
Constructor & Destructor Documentation
OSnLNodeMinus::OSnLNodeMinus ()
default constructor.
Definition at line 670 of file OSnLNode.cpp.
References OSnLNode::inodeInt, OSnLNode::inodeType, OSnLNode::inumberOfChildren, OSnLNode::m_mChildren, and OSnLNode::snodeName.
Referenced by cloneOSnLNode().
OSnLNodeMinus::~OSnLNodeMinus ()
default destructor.
Definition at line 682 of file OSnLNode.cpp.
References OSnLNode::inumberOfChildren, and OSnLNode::m_mChildren.
Member Function Documentation
double OSnLNodeMinus::calculateFunction (double * x) [virtual]
Calculate the function value given the current variable values. This is an abstract method which is required to be implemented by the concrete operator nodes that derive or extend from this OSnLNode class.
Parameters:
x holds the values of the variables in a double array.
Returns:
the function value given the current variable values.
Implements OSnLNode.
Definition at line 694 of file OSnLNode.cpp.
References OSnLNode::calculateFunction(), OSnLNode::m_dFunctionValue, and OSnLNode::m_mChildren.
OSnLNode * OSnLNodeMinus::cloneOSnLNode () [virtual]
Create or clone a node of this type. This is an abstract method which is required to be implemented by the concrete operator nodes that derive or extend from this OSnLNode class.
Parameters:
x holds the values of the variables in a double array.
Returns:
the function value given the current variable values.
Implements OSnLNode.
Definition at line 706 of file OSnLNode.cpp.
References OSnLNodeMinus().
double OSnLNodeMinus::constructCppADTape (std::map< int, int > * cppADIdx, CppAD::vector< AD< double > > * XAD) [virtual]
The implementation of the virtual functions.
Returns:
a AD<double>.
Implements OSnLNode.
Definition at line 700 of file OSnLNode.cpp.
References OSnLNode::constructCppADTape(), OSnLNode::m_CppADTape, and OSnLNode::m_mChildren.
The documentation for this class was generated from the following files:
/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSCommonInterfaces/OSnLNode.h
/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSCommonInterfaces/OSnLNode.cpp