OSInstance Class Reference
OSInstance Class Reference
The in-memory representation of an OSiL instance..
#include <OSInstance.h>
Public Member Functions
OSInstance ()
The OSInstance class constructor.
~OSInstance ()
The OSInstance class destructor.
std::string getInstanceName ()
Get instance name.
std::string getInstanceSource ()
Get instance source.
std::string getInstanceDescription ()
Get instance description.
int getVariableNumber ()
Get variable number.
std::string * getVariableNames ()
Get variable names.
double * getVariableInitialValues ()
Get variable initial values.
std::string * getVariableInitialStringValues ()
Get variable initial std::string values.
char * getVariableTypes ()
Get variable types.
int getNumberOfIntegerVariables ()
getNumberOfIntegerVariables
int getNumberOfBinaryVariables ()
getNumberOfBinaryVariables
double * getVariableLowerBounds ()
Get variable lower bounds.
double * getVariableUpperBounds ()
Get variable upper bounds.
int getObjectiveNumber ()
Get objective number.
std::string * getObjectiveNames ()
Get objective names.
std::string * getObjectiveMaxOrMins ()
Get objective maxOrMins.
int * getObjectiveCoefficientNumbers ()
Get objective coefficient number.
double * getObjectiveConstants ()
Get objective constants.
double * getObjectiveWeights ()
Get objective weights.
SparseVector ** getObjectiveCoefficients ()
Get objective coefficients.
double ** getDenseObjectiveCoefficients ()
getDenseObjectiveCoefficients.
int getConstraintNumber ()
Get constraint number.
std::string * getConstraintNames ()
Get constraint names.
double * getConstraintLowerBounds ()
Get constraint lower bounds.
double * getConstraintUpperBounds ()
Get constraint upper bounds.
char * getConstraintTypes ()
Get constraint types.
int getLinearConstraintCoefficientNumber ()
Get number of specified (usually nonzero) linear constraint coefficient values.
bool getLinearConstraintCoefficientMajor ()
Get whether the constraint coefficients is in column major (true) or row major (false).
SparseMatrix * getLinearConstraintCoefficientsInColumnMajor ()
Get linear constraint coefficients in column major.
SparseMatrix * getLinearConstraintCoefficientsInRowMajor ()
Get linear constraint coefficients in row major.
int getNumberOfQuadraticTerms ()
Get the number of specified (usually nonzero) qTerms in the quadratic coefficients.
QuadraticTerms * getQuadraticTerms ()
Get all the quadratic terms in the instance.
int * getQuadraticRowIndexes ()
Get the indexes of rows which have a quadratic term.
int getNumberOfQuadraticRowIndexes ()
Get the number of rows which have a quadratic term.
int getNumberOfNonlinearExpressions ()
Get number of nonlinear expressions.
OSExpressionTree * getNonlinearExpressionTree (int rowIdx)
Get the expression tree for a given row index.
OSExpressionTree * getNonlinearExpressionTreeMod (int rowIdx)
Get the expression tree for a given row index for the modified expression trees (quadratic terms added).
std::vector< OSnLNode * > getNonlinearExpressionTreeInPostfix (int rowIdx)
Get the postfix tokens for a given row index.
std::vector< OSnLNode * > getNonlinearExpressionTreeModInPostfix (int rowIdx)
Get the postfix tokens for a given row index for the modified Expression Tree (quadratic terms added).
std::vector< OSnLNode * > getNonlinearExpressionTreeInPrefix (int rowIdx)
Get the prefix tokens for a given row index.
std::vector< OSnLNode * > getNonlinearExpressionTreeModInPrefix (int rowIdx)
Get the prefix tokens for a given row index for the modified Expression Tree (quadratic terms added).
int getNumberOfNonlinearObjectives ()
Returns:
the number of Objectives with a nonlinear term
int getNumberOfNonlinearConstraints ()
Returns:
the number of Constraints with a nonlinear term
std::map< int,
OSExpressionTree * > getAllNonlinearExpressionTrees ()
Returns:
a map: the key is the row index and the value is the corresponding expression tree
std::map< int,
OSExpressionTree * > getAllNonlinearExpressionTreesMod ()
Returns:
a map: the key is the row index and the value is the corresponding expression tree
int * getNonlinearExpressionTreeIndexes ()
Get all the nonlinear expression tree indexes, i.e.
int getNumberOfNonlinearExpressionTreeIndexes ()
Get the number of unique Nonlinear exrpession tree indexes.
int * getNonlinearExpressionTreeModIndexes ()
Get all the nonlinear expression tree indexes, i.e.
int getNumberOfNonlinearExpressionTreeModIndexes ()
Get the number of unique Nonlinear exrpession tree indexes after modifying the expression tree to contain quadratic terms.
bool setInstanceSource (std::string source)
set the instance source.
bool setInstanceDescription (std::string description)
set the instance description.
bool setInstanceName (std::string name)
set the instance name.
bool setVariableNumber (int number)
set the variable number.
bool addVariable (int index, std::string name, double lowerBound, double upperBound, char type, double init, std::string initString)
add a variable.
bool setVariables (int number, std::string *names, double *lowerBounds, double *upperBounds, char *types, double *inits, std::string *initsString)
set all the variable related elements.
bool setObjectiveNumber (int number)
set the objective number.
bool addObjective (int index, std::string name, std::string maxOrMin, double constant, double weight, SparseVector *objectiveCoefficients)
add an objective.
bool setObjectives (int number, std::string *names, std::string *maxOrMins, double *constants, double *weights, SparseVector **objectitiveCoefficients)
set all the objectives related elements.
bool setConstraintNumber (int number)
set the constraint number.
bool addConstraint (int index, std::string name, double lowerBound, double upperBound, double constant)
add a constraint.
bool setConstraints (int number, std::string *names, double *lowerBounds, double *upperBounds, double *constants)
set all the constraint related elements.
bool setLinearConstraintCoefficients (int numberOfValues, bool isColumnMajor, double *values, int valuesBegin, int valuesEnd, int *indexes, int indexesBegin, int indexesEnd, int *starts, int startsBegin, int startsEnd)
set linear constraint coefficients
bool setQuadraticTerms (int number, int *rowIndexes, int *varOneIndexes, int *varTwoIndexes, double *coefficients, int begin, int end)
set quadratic terms
bool setQuadraticTermsInNonlinearExpressions (int number, int *rowIndexes, int *varOneIndexes, int *varTwoIndexes, double *coefficients)
set quadratic terms in nonlinearExpressions
bool initializeNonLinearStructures ()
Initialize the data structures for the nonlinear API.
double calculateFunctionValue (int idx, double *x, bool new_x)
Calculate the function value for function (constraint or objective) indexed by idx.
double * calculateAllConstraintFunctionValues (double *x, double *objLambda, double *conLambda, bool new_x, int highestOrder)
Calculate all of the constraint function values.
double * calculateAllConstraintFunctionValues (double *x, bool new_x)
Calculate all of the constraint function values, we are overloading this function and this version of the method will not use any AD and will evaluate function values from the OS Expression Tree.
double * calculateAllObjectiveFunctionValues (double *x, double *objLambda, double *conLambda, bool new_x, int highestOrder)
Calculate all of the objective function values.
double * calculateAllObjectiveFunctionValues (double *x, bool new_x)
Calculate all of the objective function values, we are overloading this function and this version of the method will not use any AD and will evaluate function values from the OS Expression Tree.
SparseJacobianMatrix * calculateAllConstraintFunctionGradients (double *x, double *objLambda, double *conLambda, bool new_x, int highestOrder)
Calculate the gradient of all constraint functions.
SparseVector * calculateConstraintFunctionGradient (double *x, double *objLambda, double *conLambda, int idx, bool new_x, int highestOrder)
Calculate the gradient of the constraint function indexed by idx.
SparseVector * calculateConstraintFunctionGradient (double *x, int idx, bool new_x)
Calculate the gradient of the constraint function indexed by idx this function is overloaded.
double ** calculateAllObjectiveFunctionGradients (double *x, double *objLambda, double *conLambda, bool new_x, int highestOrder)
Calculate the gradient of all objective functions.
double * calculateObjectiveFunctionGradient (double *x, double *objLambda, double *conLambda, int objIdx, bool new_x, int highestOrder)
Calculate the gradient of the objective function indexed by objIdx.
double * calculateObjectiveFunctionGradient (double *x, int objIdx, bool new_x)
Calculate the gradient of the objective function indexed by objIdx this function is overloaded.
SparseHessianMatrix * calculateLagrangianHessian (double *x, double *objLambda, double *conLambda, bool new_x, int highestOrder)
Calculate the Hessian of the Lagrangian Expression Tree This method will build the CppAD expression tree for only the first iteration Use this method on if the value of x does not affect the operations sequence.
SparseHessianMatrix * calculateHessian (double *x, int idx, bool new_x)
Calculate the Hessian of a constraint or objective function.
bool getSparseJacobianFromColumnMajor ()
Returns:
true if successful in generating the constraints gradient.
bool getSparseJacobianFromRowMajor ()
Returns:
true if successful in generating the constraints gradient.
OSExpressionTree * getLagrangianExpTree ()
Returns:
a pointer to the ExpressionTree for the Lagrangian function of current instance we only take the Lagrangian of the rows with nonlinear terms
std::map< int, int > getAllNonlinearVariablesIndexMap ()
Returns:
a pointer to a map of the indices of all of the variables that appear in the Lagrangian function
SparseHessianMatrix * getLagrangianHessianSparsityPattern ()
Returns:
a pointer to a SparseHessianMatrix with the nonzero structure of the Lagrangian Expression Tree
bool addQTermsToExressionTree ()
Returns:
true if successful in adding the qTerms to the ExpressionTree.
SparseJacobianMatrix * getJacobianSparsityPattern ()
Returns:
pointer to a SparseJacobianMatrix.
void duplicateExpressionTreesMap ()
duplicate the map of expression trees.
bool createCppADFun (std::vector< double > vdX)
Create the a CppAD Function object: this is a function where the domain is the set of variables for the problem and the range is the objective function plus constraints.
std::vector< double > forwardAD (int p, std::vector< double > vdX)
Perform an AD forward sweep.
std::vector< double > reverseAD (int p, std::vector< double > vdlambda)
Perform an AD reverse sweep.
bool getIterateResults (double *x, double *objLambda, double *conLambda, bool new_x, int highestOrder)
end revised AD code
bool getZeroOrderResults (double *x, double *objLambda, double *conLambda)
Calculate function values.
bool getFirstOrderResults (double *x, double *objLambda, double *conLambda)
Calculate first derivatives.
bool getSecondOrderResults (double *x, double *objLambda, double *conLambda)
Calculate second derivatives.
bool initForAlgDiff ()
This should be called by nonlinear solvers using callback functions.
bool initObjGradients ()
This should be called by initForAlgDiff().
Public Attributes
InstanceHeader * instanceHeader
A pointer to an InstanceHeader object.
InstanceData * instanceData
A pointer to an InstanceData object.
CppAD::ADFun< double > * Fad
F is a CppAD function the range space is the objective + constraints functions, x is the domeain space.
bool bUseExpTreeForFunEval
bUseExpTreeForFunEval is set to true if you wish to use the OS Expression Tree for function evaluations instead of AD -- false by default.
Private Member Functions
bool processVariables ()
process variables.
bool processObjectives ()
process objectives.
bool processConstraints ()
process constraints.
bool processLinearConstraintCoefficients ()
process linear constraint coefficients.
Private Attributes
std::string m_sInstanceName
m_sInstanceName holds the instance name.
std::string m_sInstanceSource
m_sInstanceSource holds the instance source.
std::string m_sInstanceDescription
m_sInstanceDescription holds the instance description.
bool m_bProcessVariables
m_bProcessVariables holds whether the variables are processed.
int m_iVariableNumber
m_iVariableNumber holds the variable number.
int m_iNumberOfIntegerVariables
m_iNumberOfIntegerVariables holds the number of integer variables.
int m_iNumberOfBinaryVariables
m_iNumberOfBinaryVariables holds the number of binary variables.
int m_iNumberOfQuadraticRowIndexes
m_iNumberOfQuadraticRowIndexes holds the number of distinct rows and objectives with quadratic terms.
bool m_bQuadraticRowIndexesProcessed
m_bQuadraticRowIndexesProcessed is true if getQuadraticRowIndexes() has been called.
int * m_miQuadRowIndexes
m_miQuadRowIndexes is an integer pointer to the distinct rows indexes with a quadratic term.
int m_iNumberOfNonlinearExpressionTreeIndexes
m_iNumberOfNonlinearExpressionTreeIndexes holds the number of distinct rows and objectives with nonlinear terms.
bool m_bNonlinearExpressionTreeIndexesProcessed
m_bNonlinearExpressionTreeIndexesProcessed is true if getNonlinearExpressionTreeIndexes has been called.
int * m_miNonlinearExpressionTreeIndexes
m_miNonlinearExpressionTreeIndexes is an integer pointer to the distinct rows indexes in the nonlinear expression tree map.
int m_iNumberOfNonlinearExpressionTreeModIndexes
m_iNumberOfNonlinearExpressionTreeModIndexes holds the number of distinct rows and objectives with nonlinear terms including quadratic terms added to the nonlinear expression trees.
bool m_bNonlinearExpressionTreeModIndexesProcessed
m_bNonlinearExpressionTreeModIndexesProcessed is true if getNonlinearExpressionTreeModIndexes has been called.
int * m_miNonlinearExpressionTreeModIndexes
m_miNonlinearExpressionTreeModIndexes is an integer pointer to the distinct rows indexes in the modified expression tree map.
std::string * m_msVariableNames
m_msVariableNames holds an array of variable names.
double * m_mdVariableInitialValues
m_mdVariableInitialValues holds a double array of the initial variable values.
std::string * m_msVariableInitialStringValues
m_msVariableInitialStringValues holds a std::string array of the initial variable values.
char * m_mcVariableTypes
m_mcVariableTypes holds a char array of variable types (default = 'C').
double * m_mdVariableLowerBounds
m_mdVariableLowerBounds holds a double array of variable lower bounds (default = 0.0).
double * m_mdVariableUpperBounds
m_mdVariableUpperBounds holds a double array of variable upper bounds (default = INF).
bool m_bProcessObjectives
m_bProcessObjectives holds whether the objectives are processed.
int m_iObjectiveNumber
m_iObjectiveNumber is the number of objective functions.
int m_iObjectiveNumberNonlinear
m_iObjectiveNumber is the number of objective functions with a nonlinear term.
std::string * m_msObjectiveNames
m_msObjectiveNames holds an array of objective names.
std::string * m_msMaxOrMins
m_msMaxOrMins holds a std::string array of objective maxOrMins ("max" or "min").
int * m_miNumberOfObjCoef
m_miNumberOfObjCoef holds an integer array of number of objective coefficients (default = 0.0).
double * m_mdObjectiveConstants
m_mdObjectiveConstants holds an array of objective constants (default = 0.0).
double * m_mdObjectiveWeights
m_mdObjectiveWeights holds an array of objective weights (default = 1.0).
SparseVector ** m_mObjectiveCoefficients
m_mObjectiveCoefficients holds an array of objective coefficients, one set of objective coefficients for each objective.
bool m_bGetDenseObjectives
m_bGetDenseObjectives holds whether the dense objective functions are processed.
double ** m_mmdDenseObjectiveCoefficients
m_mmdDenseObjectiveCoefficients holds an array of pointers, each pointer points to a vector of dense objective function coefficients
bool m_bProcessConstraints
m_bProcessConstraints holds whether the constraints are processed.
int m_iConstraintNumber
m_iConstraintNumber is the number of constraints.
int m_iConstraintNumberNonlinear
m_iConstraintNumberNonlinear is the number of constraints that have a nonlinear term.
std::string * m_msConstraintNames
m_msConstraintNames holds an array of constraint names.
double * m_mdConstraintLowerBounds
m_mdConstraintLowerBounds holds an array of constraint lower bounds (default = -INF).
double * m_mdConstraintUpperBounds
m_mdConstraintUpperBounds holds an array of constraint upper bounds (default = INF).
double * m_mdConstraintConstants
m_mdConstraintConstants holds an array of constraint constants (default = 0.0).
char * m_mcConstraintTypes
m_mcConstraintTypes holds a char array of constraint types (R for range; L for <=; G for >=; E for =; U for unconstrained)
bool m_bProcessLinearConstraintCoefficients
m_bProcessLinearConstraintCoefficients holds whether the linear constraint coefficients are processed.
int m_iLinearConstraintCoefficientNumber
m_iLinearConstraintCoefficientNumber holds the number of specified (usually nonzero) linear constraint coefficient values.
bool m_bColumnMajor
m_bColumnMajor holds whether the linear constraint coefficients are stored in column major.
bool m_binitForAlgDiff
m_binitForAlgDiff is true if initForAlgDiff() has been called.
SparseMatrix * m_linearConstraintCoefficientsInColumnMajor
m_linearConstraintCoefficientsInColumnMajor holds the standard 3 array data structure for linear constraint coefficients (starts, indexes and values) in column major.
SparseMatrix * m_linearConstraintCoefficientsInRowMajor
m_linearConstraintCoefficientsInRowMajor holds the standard 3 array data structure for linear constraint coefficients (starts, indexes and values) in row major.
bool m_bProcessQuadraticTerms
m_bProcessQuadraticTerms holds whether the quadratic terms are processed.
int m_iQuadraticTermNumber
m_iQuadraticTermNumber holds the number of specified (usually nonzero) qTerms in the quadratic coefficients.
double * m_mdConstraintFunctionValues
m_mdConstraintFunctionValues holds a double array of constraint function values -- the size of the array is equal to getConstraintNumber().
double * m_mdObjectiveFunctionValues
m_mdObjectiveFunctionValues holds a double array of objective function values -- the size of the array is equal to getObjectiveNumber().
int m_iJacValueSize
m_iJacValueSize is the number of nonzero partial derivates in the Jacobian.
int * m_miJacStart
m_miJacStart holds a int array of starts for the Jacobian matrix in sparse form (row major).
int * m_miJacIndex
m_miJacIndex holds a int array of variable indices for the Jacobian matrix in sparse form (row major).
double * m_mdJacValue
m_mdJacValue holds a double array of partial derivatives for the Jacobian matrix in sparse form (row major).
int * m_miJacNumConTerms
m_miJacNumConTerms holds a int array of the number of constant terms (gradient does not change) for the Jacobian matrix in sparse form (row major).
SparseJacobianMatrix * m_sparseJacMatrix
m_sparseJacMatrix is the Jacobian matrix stored in sparse matrix format
int m_iHighestTaylorCoeffOrder
m_iHighestTaylorCoeffOrder is the order of highest calculated Taylor coefficient
QuadraticTerms * m_quadraticTerms
m_quadraticTerms the data structure for all the quadratic terms in the instance.
bool m_bQTermsAdded
m_bQTermsAdded is true if we add the quadratic terms to the expression tree
unsigned int m_iNumberOfNonlinearVariables
m_iNumberOfNonlinearVariables is the number of variables that appear in a nonlinear expression.
bool m_bProcessNonlinearExpressions
m_bProcessNonlinearExpressions holds whether the nonlinear expressions are processed.
int m_iNonlinearExpressionNumber
m_iNonlinearExpressionNumber holds the number of nonlinear expressions.
int * m_miNonlinearExpressionIndexes
m_miNonlinearExpressionIndexes holds an integer array of nonlinear expression indexes, negative indexes correspond to objectives.
bool m_bProcessExpressionTrees
m_bProcessExpressionTrees is true if the expression trees have been processed.
bool m_bProcessExpressionTreesMod
m_bProcessExpressionTreesMod is true if the modified expression trees have been processed.
std::map< int,
OSExpressionTree * > m_mapExpressionTrees
m_mapExpressionTrees holds a hash map of expression tree pointers, with the key being the row index and value being the expression tree representing the nonlinear expression of that row.
std::map< int, int > m_mapCppADFunRangeIndex
OSExpressionTree * m_LagrangianExpTree
m_LagrangianExpTree is an OSExpressionTree object that is the expression tree for the Lagrangian function.
bool m_bLagrangianExpTreeCreated
m_bLagrangianHessionCreated is true if a Lagrangian function for the Hessian has been created
SparseHessianMatrix * m_LagrangianSparseHessian
m_LagrangianSparseHessian is the Hessian Matrix of the Lagrangian function in sparse format
bool m_bLagrangianSparseHessianCreated
m_bLagrangianSparseHessianCreated is true if the sparse Hessian Matrix for the Lagrangian was created
std::map< int, int > m_mapAllNonlinearVariablesIndex
m_mapAllNonlinearVariablesIndexMap is a map of the variables in the Lagrangian function
int * m_miNonLinearVarsReverseMap
m_miNonLinearVarsReverseMap maps the nonlinear variable number back into the original variable space
bool m_bAllNonlinearVariablesIndex
m_bAllNonlinearVariablesIndexMap is true if the map of the variables in the Lagrangian function has been constructed
std::map< int,
OSExpressionTree * > m_mapExpressionTreesMod
m_mapExpressionTreesMod holds a map of expression trees, with the key being the row index and value being the expression tree representing a modification of the nonlinear expression of that row.
bool m_bCppADFunIsCreated
m_bCppADFunIsCreated is true if we have created the OSInstanc CppAD Function
bool m_bCppADTapesBuilt
is true if a CppAD Expresion Tree has been built for each row and objective with a nonlinear expression.
bool m_bCppADMustReTape
is true if a CppAD Expresion Tree has an expression that can change depending on the value of the input, e.g.
bool m_bDuplicateExpressionTreesMap
m_bDuplicateExpressionTreeMap is true if m_mapExpressionTrees was duplicated.
bool m_bNonLinearStructuresInitialized
m_bNonLinearStructuresInitialized is true if initializeNonLinearStructures() has been called.
bool m_bSparseJacobianCalculated
m_bSparseJacobianCalculated is true if getJacobianSparsityPattern() has been called.
std::map< int,
std::vector
< OSnLNode * > > m_mapExpressionTreesInPostfix
m_mapExpressionTrees holds a hash map of expression trees in postfix format, with the key being the row index and value being the expression tree representing the nonlinear expression of that row.
int m_iHighestOrderEvaluated
m_iHighestOrderEvaluated is the highest order derivative of the current iterate
double ** m_mmdObjGradient
m_mdObjGradient holds an array of pointers, each pointer points to gradient of each objective function
CppAD::vector< AD
< double > > m_vX
m_vX is a vector of CppAD indpendent variables.
std::vector< double > m_vdX
m_vdX is a vector of primal variables at each iteration
std::vector< double > m_vdYval
m_vdYval is a vector of function values
std::vector< bool > m_vbLagHessNonz
m_vbLagHessNonz is a boolean vector holding the nonzero pattern of the Lagrangian of the Hessian
std::vector< double > m_vdYjacval
m_vdYval is a vector equal to a column or row of the Jacobian
std::vector< double > m_vdw
m_vdYval is a vector of derivatives -- output from a reverse sweep
std::vector< double > m_vdLambda
m_vdYval is a vector of Lagrange multipliers
std::vector< double > m_vdDomainUnitVec
m_vdDomainUnitVec is a unit vector in the domain space
std::vector< double > m_vdRangeUnitVec
m_vdRangeUnitVec is a unit vector in the range space
bool m_bProcessTimeDomain
m_bProcessTimeDomain holds whether the time domain has been processed.
bool m_bProcessTimeStages
m_bProcessTimeStages holds whether the time stages have been processed.
bool m_bProcessTimeInterval
m_bProcessTimeInterval holds whether a time interval has been processed.
bool m_bFiniteTimeStages
m_bFiniteTimeStages holds whether the time domain has the form of finite (discrete) stages.
int m_iNumberOfTimeStages
m_iNumberOfTimeStages holds the number of discrete stages
Detailed Description
The in-memory representation of an OSiL instance..
Remarks:
1. Elements become objects of class type (the ComplexType is the class)
2. The attributes, children of the element, and text correspond to members of the class. (Note text does not have a name and becomes .value)
3. Model groups such as choice and sequence and all correspond to arrays
anything specific to XML such as base64, multi, incr do not go into classes
The root OSnLNode of each <nl> element is called ExpressionTree
Root is not called osil it is called osinstance
The OSInstance class is composed of two objects: an InstanceHeader object and and InstanceData object
Definition at line 634 of file OSInstance.h.
Constructor & Destructor Documentation
OSInstance::OSInstance ()
The OSInstance class constructor.
Definition at line 31 of file OSInstance.cpp.
References instanceData, and instanceHeader.
OSInstance::~OSInstance ()
The OSInstance class destructor.
delete[] m_msObjectiveNames; m_msObjectiveNames = NULL; delete[] m_msMaxOrMins; m_msMaxOrMins = NULL; delete[] m_miNumberOfObjCoef; m_miNumberOfObjCoef = NULL; delete[] m_mdObjectiveConstants; m_mdObjectiveConstants = NULL; delete[] m_mdObjectiveWeights; m_mdObjectiveWeights = NULL;
Definition at line 127 of file OSInstance.cpp.
References Fad, instanceData, instanceHeader, m_bColumnMajor, m_bCppADFunIsCreated, m_bDuplicateExpressionTreesMap, m_binitForAlgDiff, m_bLagrangianExpTreeCreated, m_bLagrangianSparseHessianCreated, m_bNonlinearExpressionTreeIndexesProcessed, m_bNonlinearExpressionTreeModIndexesProcessed, m_bNonLinearStructuresInitialized, m_bProcessExpressionTrees, m_bProcessLinearConstraintCoefficients, m_bProcessObjectives, m_bProcessQuadraticTerms, m_bQuadraticRowIndexesProcessed, m_bSparseJacobianCalculated, m_LagrangianExpTree, m_LagrangianSparseHessian, m_linearConstraintCoefficientsInColumnMajor, m_linearConstraintCoefficientsInRowMajor, m_mapExpressionTrees, m_mapExpressionTreesMod, m_mcConstraintTypes, m_mcVariableTypes, m_mdConstraintConstants, m_mdConstraintFunctionValues, m_mdConstraintLowerBounds, m_mdConstraintUpperBounds, m_mdJacValue, m_mdObjectiveConstants, m_mdObjectiveFunctionValues, m_mdObjectiveWeights, m_mdVariableInitialValues, m_mdVariableLowerBounds, m_mdVariableUpperBounds, m_miJacIndex, m_miJacNumConTerms, m_miJacStart, m_miNonlinearExpressionTreeIndexes, m_miNonlinearExpressionTreeModIndexes, m_miNonLinearVarsReverseMap, m_miNumberOfObjCoef, m_miQuadRowIndexes, m_mmdDenseObjectiveCoefficients, m_mmdObjGradient, m_mObjectiveCoefficients, m_msConstraintNames, m_msMaxOrMins, m_msObjectiveNames, m_msVariableInitialStringValues, m_msVariableNames, m_quadraticTerms, m_sparseJacMatrix, Objectives::numberOfObjectives, InstanceData::objectives, QuadraticCoefficients::qTerm, and InstanceData::quadraticCoefficients.
Member Function Documentation
bool OSInstance::processVariables () [private]
process variables.
Returns:
true if the variables are processed.
Exceptions:
Exception if the elements in variables are logically inconsistent.
Definition at line 799 of file OSInstance.cpp.
References ErrorClass::errormsg, Variable::init, Variable::initString, instanceData, CommonUtil::ISOSNAN(), Variable::lb, m_bProcessVariables, m_iNumberOfBinaryVariables, m_iNumberOfIntegerVariables, m_mcVariableTypes, m_mdVariableInitialValues, m_mdVariableLowerBounds, m_mdVariableUpperBounds, m_msVariableInitialStringValues, m_msVariableNames, Variable::name, Variables::numberOfVariables, Variable::type, Variable::ub, Variables::var, and InstanceData::variables.
Referenced by getNumberOfBinaryVariables(), getNumberOfIntegerVariables(), getVariableInitialStringValues(), getVariableInitialValues(), getVariableLowerBounds(), getVariableNames(), getVariableTypes(), getVariableUpperBounds(), and initializeNonLinearStructures().
bool OSInstance::processObjectives () [private]
process objectives.
Returns:
true if the objectives are processed.
Exceptions:
Exception if the elements in objectives are logically inconsistent.
Definition at line 891 of file OSInstance.cpp.
References Objective::coef, Objective::constant, ErrorClass::errormsg, ObjCoef::idx, SparseVector::indexes, instanceData, m_bProcessObjectives, m_mdObjectiveConstants, m_mdObjectiveWeights, m_miNumberOfObjCoef, m_mObjectiveCoefficients, m_msMaxOrMins, m_msObjectiveNames, Objective::maxOrMin, Objective::name, SparseVector::number, Objective::numberOfObjCoef, Objectives::numberOfObjectives, Objectives::obj, InstanceData::objectives, ObjCoef::value, SparseVector::values, and Objective::weight.
Referenced by getObjectiveCoefficientNumbers(), getObjectiveCoefficients(), getObjectiveConstants(), getObjectiveMaxOrMins(), getObjectiveNames(), getObjectiveWeights(), and initializeNonLinearStructures().
bool OSInstance::processConstraints () [private]
process constraints.
Returns:
true if the constraints are processed.
Exceptions:
Exception if the elements in constraints are logically inconsistent.
Definition at line 1003 of file OSInstance.cpp.
References Constraints::con, Constraint::constant, InstanceData::constraints, ErrorClass::errormsg, instanceData, Constraint::lb, m_bProcessConstraints, m_mcConstraintTypes, m_mdConstraintConstants, m_mdConstraintLowerBounds, m_mdConstraintUpperBounds, m_msConstraintNames, Constraint::name, Constraints::numberOfConstraints, OSDBL_MAX, and Constraint::ub.
Referenced by getConstraintLowerBounds(), getConstraintNames(), getConstraintTypes(), getConstraintUpperBounds(), and initializeNonLinearStructures().
bool OSInstance::processLinearConstraintCoefficients () [private]
process linear constraint coefficients.
Returns:
true if the linear constraint coefficients are processed.
Exceptions:
Exception if the elements in linear constraint coefficients are logically inconsistent.
Definition at line 1078 of file OSInstance.cpp.
References SparseMatrix::bDeleteArrays, LinearConstraintCoefficients::colIdx, InstanceData::constraints, DoubleVector::el, IntVector::el, ErrorClass::errormsg, SparseMatrix::indexes, instanceData, SparseMatrix::isColumnMajor, InstanceData::linearConstraintCoefficients, m_bColumnMajor, m_bProcessLinearConstraintCoefficients, m_linearConstraintCoefficientsInColumnMajor, m_linearConstraintCoefficientsInRowMajor, Constraints::numberOfConstraints, LinearConstraintCoefficients::numberOfValues, Variables::numberOfVariables, LinearConstraintCoefficients::rowIdx, LinearConstraintCoefficients::start, SparseMatrix::starts, SparseMatrix::startSize, LinearConstraintCoefficients::value, SparseMatrix::values, SparseMatrix::valueSize, and InstanceData::variables.
Referenced by getLinearConstraintCoefficientMajor(), getLinearConstraintCoefficientsInColumnMajor(), and getLinearConstraintCoefficientsInRowMajor().
string OSInstance::getInstanceName ()
Get instance name.
Returns:
instance name. Null or empty std::string ("") if there is no instance name.
Definition at line 761 of file OSInstance.cpp.
References instanceHeader, m_sInstanceName, and InstanceHeader::name.
Referenced by LindoSolver::dataEchoCheck(), KnitroSolver::dataEchoCheck(), IpoptSolver::dataEchoCheck(), CoinSolver::dataEchoCheck(), IpoptProblem::finalize_solution(), LindoSolver::optimize(), KnitroSolver::solve(), and CoinSolver::solve().
string OSInstance::getInstanceSource ()
Get instance source.
Returns:
instance source. Null or empty std::string ("") if there is no instance source.
Definition at line 769 of file OSInstance.cpp.
References instanceHeader, m_sInstanceSource, and InstanceHeader::source.
Referenced by LindoSolver::dataEchoCheck(), KnitroSolver::dataEchoCheck(), IpoptSolver::dataEchoCheck(), and CoinSolver::dataEchoCheck().
string OSInstance::getInstanceDescription ()
Get instance description.
Returns:
instance description. Null or empty std::string ("") if there is no instance description.
Definition at line 776 of file OSInstance.cpp.
References InstanceHeader::description, instanceHeader, and m_sInstanceDescription.
Referenced by LindoSolver::dataEchoCheck(), KnitroSolver::dataEchoCheck(), IpoptSolver::dataEchoCheck(), and CoinSolver::dataEchoCheck().
int OSInstance::getVariableNumber ()
Get variable number.
Returns:
variable number.
Definition at line 783 of file OSInstance.cpp.
References instanceData, m_iVariableNumber, Variables::numberOfVariables, and InstanceData::variables.
Referenced by LindoSolver::buildSolverInstance(), CoinSolver::buildSolverInstance(), LindoSolver::dataEchoCheck(), KnitroSolver::dataEchoCheck(), IpoptSolver::dataEchoCheck(), CoinSolver::dataEchoCheck(), IpoptProblem::finalize_solution(), LindoSolver::generateLindoModel(), IpoptProblem::get_nlp_info(), getLinearConstraintCoefficientsInColumnMajor(), getSparseJacobianFromColumnMajor(), initObjGradients(), KnitroProblem::loadProblemIntoKnitro(), main(), LindoSolver::optimize(), LindoSolver::processVariables(), CoinSolver::setCoinPackedMatrix(), KnitroSolver::solve(), IpoptSolver::solve(), CoinSolver::solve(), and OSnl2osil::walkTree().
string * OSInstance::getVariableNames ()
Get variable names.
Returns:
a std::string array of variable names, null if no variable names.
Exceptions:
Exception if the elements in variables are logically inconsistent.
Definition at line 843 of file OSInstance.cpp.
References m_msVariableNames, and processVariables().
Referenced by LindoSolver::dataEchoCheck(), KnitroSolver::dataEchoCheck(), IpoptSolver::dataEchoCheck(), CoinSolver::dataEchoCheck(), and LindoSolver::processVariables().
double * OSInstance::getVariableInitialValues ()
Get variable initial values.
Returns:
a double array of variable initial values, null if no initial variable values.
Exceptions:
Exception if the elements in variables are logically inconsistent.
Definition at line 848 of file OSInstance.cpp.
References m_mdVariableInitialValues, and processVariables().
Referenced by IpoptProblem::get_starting_point(), and KnitroProblem::loadProblemIntoKnitro().
string * OSInstance::getVariableInitialStringValues ()
Get variable initial std::string values.
Returns:
a std::string array of variable initial values, null if no initial variable std::string values.
Exceptions:
Exception if the elements in variables are logically inconsistent.
Definition at line 853 of file OSInstance.cpp.
References m_msVariableInitialStringValues, and processVariables().
char * OSInstance::getVariableTypes ()
Get variable types.
C for Continuous
B for Binary
I for Integer
S for String
Returns:
a char array of variable types.
Exceptions:
Exception if the elements in variables are logically inconsistent.
Definition at line 858 of file OSInstance.cpp.
References m_mcVariableTypes, and processVariables().
Referenced by CoinSolver::buildSolverInstance(), LindoSolver::dataEchoCheck(), KnitroSolver::dataEchoCheck(), IpoptSolver::dataEchoCheck(), CoinSolver::dataEchoCheck(), and LindoSolver::processVariables().
int OSInstance::getNumberOfIntegerVariables ()
getNumberOfIntegerVariables
Returns:
an integer which is the number of I variables.
Definition at line 863 of file OSInstance.cpp.
References m_iNumberOfIntegerVariables, and processVariables().
Referenced by CoinSolver::buildSolverInstance(), LindoSolver::optimize(), and CoinSolver::solve().
int OSInstance::getNumberOfBinaryVariables ()
getNumberOfBinaryVariables
Returns:
an integer which is the number of B variables.
Definition at line 868 of file OSInstance.cpp.
References m_iNumberOfBinaryVariables, and processVariables().
Referenced by CoinSolver::buildSolverInstance(), LindoSolver::optimize(), and CoinSolver::solve().
double * OSInstance::getVariableLowerBounds ()
Get variable lower bounds.
Returns:
a double array of variable lower bounds.
Exceptions:
Exception if the elements in variables are logically inconsistent.
Definition at line 873 of file OSInstance.cpp.
References m_mdVariableLowerBounds, and processVariables().
Referenced by CoinSolver::buildSolverInstance(), LindoSolver::dataEchoCheck(), KnitroSolver::dataEchoCheck(), IpoptSolver::dataEchoCheck(), CoinSolver::dataEchoCheck(), IpoptProblem::get_bounds_info(), KnitroProblem::loadProblemIntoKnitro(), and LindoSolver::processVariables().
double * OSInstance::getVariableUpperBounds ()
Get variable upper bounds.
Returns:
a double array of variable upper bounds.
Exceptions:
Exception if the elements in variables are logically inconsistent.
Definition at line 878 of file OSInstance.cpp.
References m_mdVariableUpperBounds, and processVariables().
Referenced by CoinSolver::buildSolverInstance(), LindoSolver::dataEchoCheck(), KnitroSolver::dataEchoCheck(), IpoptSolver::dataEchoCheck(), CoinSolver::dataEchoCheck(), IpoptProblem::get_bounds_info(), KnitroProblem::loadProblemIntoKnitro(), and LindoSolver::processVariables().
int OSInstance::getObjectiveNumber ()
Get objective number.
Returns:
objective number.
Definition at line 883 of file OSInstance.cpp.
References instanceData, m_iObjectiveNumber, Objectives::numberOfObjectives, and InstanceData::objectives.
Referenced by CoinSolver::buildSolverInstance(), calculateAllObjectiveFunctionValues(), calculateFunctionValue(), calculateHessian(), IpoptProblem::get_nlp_info(), initObjGradients(), KnitroProblem::loadProblemIntoKnitro(), main(), LindoSolver::optimize(), and IpoptSolver::solve().
string * OSInstance::getObjectiveNames ()
Get objective names.
Returns:
a std::string array of objective names. Null if no objective names.
Exceptions:
Exception if the elements in objectives are logically inconsistent.
Definition at line 940 of file OSInstance.cpp.
References m_msObjectiveNames, and processObjectives().
string * OSInstance::getObjectiveMaxOrMins ()
Get objective maxOrMins.
One maxOrMin for each objective.
Returns:
a std::string array of objective maxOrMins ("max" or "min"), null if no objectives.
Exceptions:
Exception if the elements in objectives are logically inconsistent.
Definition at line 945 of file OSInstance.cpp.
References m_msMaxOrMins, and processObjectives().
Referenced by CoinSolver::buildSolverInstance(), LindoSolver::dataEchoCheck(), KnitroSolver::dataEchoCheck(), IpoptSolver::dataEchoCheck(), CoinSolver::dataEchoCheck(), and LindoSolver::generateLindoModel().
int * OSInstance::getObjectiveCoefficientNumbers ()
Get objective coefficient number.
One number for each objective.
Returns:
an integer array of size of which is equal to number of objectives, each element of the array is the number of nonzero coefficients in that objective function, null if no objectives.
Exceptions:
Exception if the elements in objectives are logically inconsistent.
Definition at line 950 of file OSInstance.cpp.
References m_miNumberOfObjCoef, and processObjectives().
double * OSInstance::getObjectiveConstants ()
Get objective constants.
One constant for each objective.
Returns:
a double array of objective constants, null if no objectives.
Exceptions:
Exception if the elements in objectives are logically inconsistent.
Definition at line 955 of file OSInstance.cpp.
References m_mdObjectiveConstants, and processObjectives().
Referenced by LindoSolver::generateLindoModel(), and CoinSolver::solve().
double * OSInstance::getObjectiveWeights ()
Get objective weights.
One weight for each objective.
Returns:
a double array of objective weights, null if no objectives.
Exceptions:
Exception if the elements in objectives are logically inconsistent.
Definition at line 960 of file OSInstance.cpp.
References m_mdObjectiveWeights, and processObjectives().
SparseVector ** OSInstance::getObjectiveCoefficients ()
Get objective coefficients.
One set of objective coefficients for each objective.
See also:
org.optimizationservices.oscommon.datastructure.SparseVector
Returns:
an array of objective coefficients, null if objective coefficients. Each member of the array is of type ObjectiveCoefficients. The ObjectiveCoefficients class contains two arrays: variableIndexes is an integer array and values is a double array of coefficient values.
Exceptions:
Exception if the elements in objectives are logically inconsistent.
Definition at line 965 of file OSInstance.cpp.
References m_mObjectiveCoefficients, and processObjectives().
Referenced by calculateFunctionValue(), and getDenseObjectiveCoefficients().
double ** OSInstance::getDenseObjectiveCoefficients ()
getDenseObjectiveCoefficients.
Returns:
an vector of pointers, each pointer points to a dense vector of ObjectiveCoefficients.
Definition at line 971 of file OSInstance.cpp.
References getObjectiveCoefficients(), SparseVector::indexes, instanceData, m_bGetDenseObjectives, m_mmdDenseObjectiveCoefficients, SparseVector::number, Objectives::numberOfObjectives, Variables::numberOfVariables, Objectives::obj, InstanceData::objectives, SparseVector::values, and InstanceData::variables.
Referenced by CoinSolver::buildSolverInstance(), LindoSolver::dataEchoCheck(), KnitroSolver::dataEchoCheck(), IpoptSolver::dataEchoCheck(), CoinSolver::dataEchoCheck(), LindoSolver::generateLindoModel(), initializeNonLinearStructures(), and initObjGradients().
int OSInstance::getConstraintNumber ()
Get constraint number.
Returns:
constraint number.
Definition at line 996 of file OSInstance.cpp.
References InstanceData::constraints, instanceData, m_iConstraintNumber, and Constraints::numberOfConstraints.
Referenced by CoinSolver::buildSolverInstance(), calculateAllConstraintFunctionValues(), calculateFunctionValue(), calculateHessian(), LindoSolver::dataEchoCheck(), KnitroSolver::dataEchoCheck(), IpoptSolver::dataEchoCheck(), CoinSolver::dataEchoCheck(), IpoptProblem::finalize_solution(), LindoSolver::generateLindoModel(), IpoptProblem::get_nlp_info(), getLinearConstraintCoefficientsInRowMajor(), getSparseJacobianFromColumnMajor(), getSparseJacobianFromRowMajor(), KnitroProblem::loadProblemIntoKnitro(), main(), LindoSolver::optimize(), LindoSolver::processConstraints(), CoinSolver::setCoinPackedMatrix(), KnitroSolver::solve(), and CoinSolver::solve().
string * OSInstance::getConstraintNames ()
Get constraint names.
Returns:
a std::string array of constraint names, null if no constraint names.
Exceptions:
Exception if the elements in constraints are logically inconsistent.
Definition at line 1050 of file OSInstance.cpp.
References m_msConstraintNames, and processConstraints().
Referenced by LindoSolver::dataEchoCheck(), KnitroSolver::dataEchoCheck(), IpoptSolver::dataEchoCheck(), CoinSolver::dataEchoCheck(), and LindoSolver::processConstraints().
double * OSInstance::getConstraintLowerBounds ()
Get constraint lower bounds.
Returns:
a double array of constraint lower bounds, null if no constraints.
Exceptions:
Exception if the elements in constraints are logically inconsistent.
Definition at line 1056 of file OSInstance.cpp.
References m_mdConstraintLowerBounds, and processConstraints().
Referenced by CoinSolver::buildSolverInstance(), LindoSolver::dataEchoCheck(), KnitroSolver::dataEchoCheck(), IpoptSolver::dataEchoCheck(), CoinSolver::dataEchoCheck(), IpoptProblem::get_bounds_info(), KnitroProblem::loadProblemIntoKnitro(), and LindoSolver::processConstraints().
double * OSInstance::getConstraintUpperBounds ()
Get constraint upper bounds.
Returns:
a double array of constraint upper bounds, null if constraints.
Exceptions:
Exception if the elements in constraints are logically inconsistent.
Definition at line 1066 of file OSInstance.cpp.
References m_mdConstraintUpperBounds, and processConstraints().
Referenced by CoinSolver::buildSolverInstance(), LindoSolver::dataEchoCheck(), KnitroSolver::dataEchoCheck(), IpoptSolver::dataEchoCheck(), CoinSolver::dataEchoCheck(), IpoptProblem::get_bounds_info(), KnitroProblem::loadProblemIntoKnitro(), and LindoSolver::processConstraints().
char * OSInstance::getConstraintTypes ()
Get constraint types.
R for range constraint lb <= constraint <= ub
L for less than constraint -INF <= con <= ub or con <= ub
G for greater than constraint lb <= con <= INF or con >= lb
E for equal to constraint lb <= con <= ub where lb = ub or con = lb/ub
U for unconstrained constraint -INF <= con <= INF
Returns:
a char array of constraint types, null if constraints.
Exceptions:
Exception if the elements in constraints are logically inconsistent.
Definition at line 1061 of file OSInstance.cpp.
References m_mcConstraintTypes, and processConstraints().
Referenced by LindoSolver::processConstraints().
int OSInstance::getLinearConstraintCoefficientNumber ()
Get number of specified (usually nonzero) linear constraint coefficient values.
Returns:
number of specified (usually nonzero) linear constraint coefficient values.
Definition at line 1071 of file OSInstance.cpp.
References instanceData, InstanceData::linearConstraintCoefficients, m_iLinearConstraintCoefficientNumber, and LinearConstraintCoefficients::numberOfValues.
Referenced by CoinSolver::buildSolverInstance(), LindoSolver::dataEchoCheck(), KnitroSolver::dataEchoCheck(), IpoptSolver::dataEchoCheck(), LindoSolver::generateLindoModel(), and CoinSolver::setCoinPackedMatrix().
bool OSInstance::getLinearConstraintCoefficientMajor ()
Get whether the constraint coefficients is in column major (true) or row major (false).
Returns:
whether the constraint coefficients is in column major (true) or row major (false).
Exceptions:
Exception if the elements in linear constraint coefficients are logically inconsistent.
Definition at line 1125 of file OSInstance.cpp.
References m_bColumnMajor, and processLinearConstraintCoefficients().
Referenced by getJacobianSparsityPattern(), and CoinSolver::setCoinPackedMatrix().
SparseMatrix * OSInstance::getLinearConstraintCoefficientsInColumnMajor ()
Get linear constraint coefficients in column major.
Returns:
a sparse matrix reprsentation of linear constraint coefficients in column major, null if no linear constraint coefficients.
Exceptions:
Exception if the elements in linear constraint coefficients are logically inconsistent.
See also:
org.optimizationservices.oscommon.datastructure.SparseMatrix
Definition at line 1130 of file OSInstance.cpp.
References MathUtil::convertLinearConstraintCoefficientMatrixToTheOtherMajor(), getVariableNumber(), SparseMatrix::indexes, m_bColumnMajor, m_linearConstraintCoefficientsInColumnMajor, m_linearConstraintCoefficientsInRowMajor, processLinearConstraintCoefficients(), SparseMatrix::starts, SparseMatrix::startSize, SparseMatrix::values, and SparseMatrix::valueSize.
Referenced by LindoSolver::dataEchoCheck(), KnitroSolver::dataEchoCheck(), IpoptSolver::dataEchoCheck(), LindoSolver::generateLindoModel(), and CoinSolver::setCoinPackedMatrix().
SparseMatrix * OSInstance::getLinearConstraintCoefficientsInRowMajor ()
Get linear constraint coefficients in row major.
Returns:
a sparse matrix reprsentation of linear constraint coefficients in row major, null if no linear constraint coefficients.
Exceptions:
Exception if the elements in linear constraint coefficients are logically inconsistent.
See also:
org.optimizationservices.oscommon.datastructure.SparseMatrix
Definition at line 1147 of file OSInstance.cpp.
References MathUtil::convertLinearConstraintCoefficientMatrixToTheOtherMajor(), getConstraintNumber(), SparseMatrix::indexes, m_bColumnMajor, m_linearConstraintCoefficientsInColumnMajor, m_linearConstraintCoefficientsInRowMajor, processLinearConstraintCoefficients(), SparseMatrix::starts, SparseMatrix::startSize, SparseMatrix::values, and SparseMatrix::valueSize.
Referenced by CoinSolver::setCoinPackedMatrix().
int OSInstance::getNumberOfQuadraticTerms ()
Get the number of specified (usually nonzero) qTerms in the quadratic coefficients.
Returns:
qTerm number.
Definition at line 1165 of file OSInstance.cpp.
References instanceData, m_iQuadraticTermNumber, QuadraticCoefficients::numberOfQuadraticTerms, and InstanceData::quadraticCoefficients.
Referenced by LindoSolver::buildSolverInstance(), LindoSolver::dataEchoCheck(), KnitroSolver::dataEchoCheck(), IpoptSolver::dataEchoCheck(), IpoptProblem::get_nlp_info(), getQuadraticRowIndexes(), initializeNonLinearStructures(), KnitroProblem::loadProblemIntoKnitro(), LindoSolver::processQuadraticTerms(), IpoptSolver::solve(), and CoinSolver::solve().
QuadraticTerms * OSInstance::getQuadraticTerms ()
Get all the quadratic terms in the instance.
Returns:
the QuadraticTerms data structure for all quadratic terms in the instance, null if no quadratic terms. The QuadraticTerms contains four arrays: rowIndexes, varOneIndexes, varTwoIndexes, coefficients.
Exceptions:
Exception if the elements in quadratic coefficients are logically inconsistent.
See also:
org.optimizationservices.oscommon.datastructure.QuadraticTerms
Definition at line 1175 of file OSInstance.cpp.
References QuadraticTerm::coef, QuadraticTerms::coefficients, ErrorClass::errormsg, QuadraticTerm::idx, QuadraticTerm::idxOne, QuadraticTerm::idxTwo, instanceData, m_bProcessQuadraticTerms, m_quadraticTerms, QuadraticCoefficients::numberOfQuadraticTerms, QuadraticCoefficients::qTerm, InstanceData::quadraticCoefficients, QuadraticTerms::rowIndexes, QuadraticTerms::varOneIndexes, and QuadraticTerms::varTwoIndexes.
Referenced by addQTermsToExressionTree(), LindoSolver::dataEchoCheck(), KnitroSolver::dataEchoCheck(), IpoptSolver::dataEchoCheck(), getQuadraticRowIndexes(), and LindoSolver::processQuadraticTerms().
int * OSInstance::getQuadraticRowIndexes ()
Get the indexes of rows which have a quadratic term.
Returns:
an integer pointer to the row indexes of rows with quadratic terms, objectives functions have index < 0 NULL if there are no quadratic terms.
Definition at line 1204 of file OSInstance.cpp.
References ErrorClass::errormsg, getNumberOfQuadraticTerms(), getQuadraticTerms(), m_bQuadraticRowIndexesProcessed, m_iNumberOfQuadraticRowIndexes, m_miQuadRowIndexes, and QuadraticTerms::rowIndexes.
Referenced by getNumberOfQuadraticRowIndexes().
int OSInstance::getNumberOfQuadraticRowIndexes ()
Get the number of rows which have a quadratic term.
Returns:
an integer which is the number of distinct rows (including obj) with quadratic terms,
Definition at line 1235 of file OSInstance.cpp.
References getQuadraticRowIndexes(), m_bQuadraticRowIndexesProcessed, and m_iNumberOfQuadraticRowIndexes.
int OSInstance::getNumberOfNonlinearExpressions ()
Get number of nonlinear expressions.
Returns:
the number of nonlinear expressions.
Definition at line 790 of file OSInstance.cpp.
References instanceData, m_iNonlinearExpressionNumber, InstanceData::nonlinearExpressions, and NonlinearExpressions::numberOfNonlinearExpressions.
Referenced by LindoSolver::buildSolverInstance(), IpoptProblem::get_nlp_info(), KnitroProblem::loadProblemIntoKnitro(), IpoptSolver::solve(), and CoinSolver::solve().
OSExpressionTree * OSInstance::getNonlinearExpressionTree (int rowIdx)
Get the expression tree for a given row index.
Returns:
an expression tree
define an iterator for the expression trees map allExpTrees
for(pos = m_mapExpressionTrees.begin(); pos != m_mapExpressionTrees.end(); ++pos){
Definition at line 1314 of file OSInstance.cpp.
References getAllNonlinearExpressionTrees(), m_bProcessExpressionTrees, and m_mapExpressionTrees.
Referenced by getNonlinearExpressionTreeInPostfix(), getNonlinearExpressionTreeInPrefix(), and main().
OSExpressionTree * OSInstance::getNonlinearExpressionTreeMod (int rowIdx)
Get the expression tree for a given row index for the modified expression trees (quadratic terms added).
Returns:
an expression tree
define an iterator for the expression trees map allExpTrees
for(pos = m_mapExpressionTrees.begin(); pos != m_mapExpressionTrees.end(); ++pos){
Definition at line 1336 of file OSInstance.cpp.
References getAllNonlinearExpressionTreesMod(), m_bProcessExpressionTreesMod, and m_mapExpressionTreesMod.
Referenced by getNonlinearExpressionTreeModInPostfix(), and getNonlinearExpressionTreeModInPrefix().
std::vector< OSnLNode * > OSInstance::getNonlinearExpressionTreeInPostfix (int rowIdx)
Get the postfix tokens for a given row index.
Returns:
a vector of pointers to OSnLNodes in postfix, if rowIdx does not index a row with a nonlinear term throw an exception
Definition at line 1358 of file OSInstance.cpp.
References ErrorClass::errormsg, getAllNonlinearExpressionTrees(), getNonlinearExpressionTree(), OSnLNode::getPostfixFromExpressionTree(), m_bProcessExpressionTrees, m_mapExpressionTrees, and OSExpressionTree::m_treeRoot.
Referenced by main().
std::vector< OSnLNode * > OSInstance::getNonlinearExpressionTreeModInPostfix (int rowIdx)
Get the postfix tokens for a given row index for the modified Expression Tree (quadratic terms added).
Returns:
a vector of pointers to OSnLNodes in postfix, if rowIdx does not index a row with a nonlinear term throw an exception
Definition at line 1378 of file OSInstance.cpp.
References ErrorClass::errormsg, getAllNonlinearExpressionTreesMod(), getNonlinearExpressionTreeMod(), OSnLNode::getPostfixFromExpressionTree(), m_bProcessExpressionTreesMod, m_mapExpressionTreesMod, and OSExpressionTree::m_treeRoot.
std::vector< OSnLNode * > OSInstance::getNonlinearExpressionTreeInPrefix (int rowIdx)
Get the prefix tokens for a given row index.
Returns:
a vector of pointers to OSnLNodes in prefix, if rowIdx does not index a row with a nonlinear term throw an exception
Definition at line 1398 of file OSInstance.cpp.
References ErrorClass::errormsg, getAllNonlinearExpressionTrees(), getNonlinearExpressionTree(), OSnLNode::getPrefixFromExpressionTree(), m_bProcessExpressionTrees, m_mapExpressionTrees, and OSExpressionTree::m_treeRoot.
Referenced by main().
std::vector< OSnLNode * > OSInstance::getNonlinearExpressionTreeModInPrefix (int rowIdx)
Get the prefix tokens for a given row index for the modified Expression Tree (quadratic terms added).
Returns:
a vector of pointers to OSnLNodes in prefix, if rowIdx does not index a row with a nonlinear term throw an exception
Definition at line 1417 of file OSInstance.cpp.
References ErrorClass::errormsg, getAllNonlinearExpressionTreesMod(), getNonlinearExpressionTreeMod(), OSnLNode::getPrefixFromExpressionTree(), m_bProcessExpressionTreesMod, m_mapExpressionTreesMod, and OSExpressionTree::m_treeRoot.
int OSInstance::getNumberOfNonlinearObjectives ()
Returns:
the number of Objectives with a nonlinear term
Definition at line 1305 of file OSInstance.cpp.
References getAllNonlinearExpressionTrees(), m_bProcessExpressionTrees, and m_iObjectiveNumberNonlinear.
Referenced by addQTermsToExressionTree(), LindoSolver::optimize(), and LindoSolver::processNonlinearExpressions().
int OSInstance::getNumberOfNonlinearConstraints ()
Returns:
the number of Constraints with a nonlinear term
Definition at line 1297 of file OSInstance.cpp.
References getAllNonlinearExpressionTrees(), m_bProcessExpressionTrees, and m_iConstraintNumberNonlinear.
Referenced by LindoSolver::optimize(), and LindoSolver::processNonlinearExpressions().
std::map< int, OSExpressionTree * > OSInstance::getAllNonlinearExpressionTrees ()
Returns:
a map: the key is the row index and the value is the corresponding expression tree
Definition at line 1436 of file OSInstance.cpp.
References OSExpressionTree::bDestroyNlNodes, Nl::idx, instanceData, Nl::m_bDeleteExpressionTree, m_bProcessExpressionTrees, m_iConstraintNumberNonlinear, m_iObjectiveNumberNonlinear, m_mapExpressionTrees, OSnLNode::m_mChildren, OSExpressionTree::m_treeRoot, NonlinearExpressions::nl, InstanceData::nonlinearExpressions, NonlinearExpressions::numberOfNonlinearExpressions, and Nl::osExpressionTree.
Referenced by duplicateExpressionTreesMap(), getNonlinearExpressionTree(), getNonlinearExpressionTreeIndexes(), getNonlinearExpressionTreeInPostfix(), getNonlinearExpressionTreeInPrefix(), getNumberOfNonlinearConstraints(), getNumberOfNonlinearObjectives(), and initializeNonLinearStructures().
std::map< int, OSExpressionTree * > OSInstance::getAllNonlinearExpressionTreesMod ()
Returns:
a map: the key is the row index and the value is the corresponding expression tree
Definition at line 1497 of file OSInstance.cpp.
References initializeNonLinearStructures(), m_bNonLinearStructuresInitialized, m_bProcessExpressionTreesMod, and m_mapExpressionTreesMod.
Referenced by getNonlinearExpressionTreeMod(), getNonlinearExpressionTreeModIndexes(), getNonlinearExpressionTreeModInPostfix(), getNonlinearExpressionTreeModInPrefix(), and LindoSolver::processNonlinearExpressions().
int * OSInstance::getNonlinearExpressionTreeIndexes ()
Get all the nonlinear expression tree indexes, i.e.
indexes of rows (objectives or constraints) that contain nonlinear expressions.
Returns:
a pointer to an integer array of nonlinear expression tree indexes.
Definition at line 1240 of file OSInstance.cpp.
References ErrorClass::errormsg, getAllNonlinearExpressionTrees(), m_bNonlinearExpressionTreeIndexesProcessed, m_iNumberOfNonlinearExpressionTreeIndexes, and m_miNonlinearExpressionTreeIndexes.
Referenced by getNumberOfNonlinearExpressionTreeIndexes().
int OSInstance::getNumberOfNonlinearExpressionTreeIndexes ()
Get the number of unique Nonlinear exrpession tree indexes.
Returns:
the number of unique nonlinear expression tree indexes.
Definition at line 1262 of file OSInstance.cpp.
References getNonlinearExpressionTreeIndexes(), m_bNonlinearExpressionTreeIndexesProcessed, and m_iNumberOfNonlinearExpressionTreeIndexes.
int * OSInstance::getNonlinearExpressionTreeModIndexes ()
Get all the nonlinear expression tree indexes, i.e.
indexes of rows (objetives or constraints) that contain nonlinear expressions after modifying the expression tree to contain quadratic terms.
Returns:
a pointer to an integer array of nonlinear expression tree indexes (including quadratic terms).
Definition at line 1269 of file OSInstance.cpp.
References ErrorClass::errormsg, getAllNonlinearExpressionTreesMod(), m_bNonlinearExpressionTreeModIndexesProcessed, m_iNumberOfNonlinearExpressionTreeModIndexes, and m_miNonlinearExpressionTreeModIndexes.
Referenced by getNumberOfNonlinearExpressionTreeModIndexes().
int OSInstance::getNumberOfNonlinearExpressionTreeModIndexes ()
Get the number of unique Nonlinear exrpession tree indexes after modifying the expression tree to contain quadratic terms.
Returns:
the number of unique nonlinear expression tree indexes (including quadratic terms).
Definition at line 1291 of file OSInstance.cpp.
References getNonlinearExpressionTreeModIndexes(), m_bNonlinearExpressionTreeModIndexesProcessed, and m_iNumberOfNonlinearExpressionTreeModIndexes.
bool OSInstance::setInstanceSource (std::string source)
set the instance source.
Parameters:
source holds the instance source.
Returns:
whether the instance source is set successfully.
Referenced by main().
bool OSInstance::setInstanceDescription (std::string description)
set the instance description.
Parameters:
description holds the instance description.
Returns:
whether the instance description is set successfully.
Referenced by OSnl2osil::createOSInstance(), OSMatlab::createOSInstance(), and main().
bool OSInstance::setInstanceName (std::string name)
set the instance name.
Parameters:
name holds the instance name.
Returns:
whether the instance name is set successfully.
Referenced by OSmps2osil::createOSInstance(), and OSMatlab::createOSInstance().
bool OSInstance::setVariableNumber (int number)
set the variable number.
Parameters:
number holds the variable number.
Returns:
whether the variable number is set successfully.
Definition at line 1532 of file OSInstance.cpp.
References instanceData, Variables::numberOfVariables, Variables::var, and InstanceData::variables.
Referenced by OSnl2osil::createOSInstance(), OSmps2osil::createOSInstance(), and main().
bool OSInstance::addVariable (int index, std::string name, double lowerBound, double upperBound, char type, double init, std::string initString)
add a variable.
In order to use the add method, the setVariableNumber must first be called so that the variable number is known ahead of time to assign appropriate memory. If a variable with the given variable index already exists, the old variable will be replaced.
Parameters:
index holds the variable index. It is required.
name holds the variable name; use null or empty std::string ("") if no variable name.
lowerBound holds the variable lower bound; use Double.NEGATIVE_INFINITY if no lower bound.
upperBound holds the variable upper bound; use Double.POSITIVE_INFINITY if no upper bound.
type holds the variable type character, B for Binary, I for Integer, S for String, C or any other char for Continuous)
init holds the double variable initial value; use Double.NaN if no initial value.
initString holds the std::string variable initial value; use null or empty std::string ("") if no initial std::string value.
Returns:
whether the variable is added successfully.
Referenced by OSnl2osil::createOSInstance(), OSmps2osil::createOSInstance(), and main().
bool OSInstance::setVariables (int number, std::string * names, double * lowerBounds, double * upperBounds, char * types, double * inits, std::string * initsString)
set all the variable related elements.
All the previous variable-related elements will be deleted.
Parameters:
number holds the number of variables. It is required.
names holds a std::string array of variable names; use null if no variable names.
lowerBounds holds a double array of variable lower bounds; use null if all lower bounds are 0; use Double.NEGATIVE_INFINITY if no lower bound for a specific variable in the array.
upperBounds holds a double array of variable upper bounds; use null if no upper bounds; use Double.POSITIVE_INFINITY if no upper bound for a specific variable in the array.
types holds a char array of variable types; use null if all variables are continuous; for a specfic variable in the array use B for Binary, I for Integer, S for String, C or any other char for Continuous,)
inits holds a double array of varible initial values; use null if no initial values.
initsString holds a std::string array of varible initial values; use null if no initial std::string values.
Returns:
whether the variables are set successfully.
Referenced by OSMatlab::createOSInstance().
bool OSInstance::setObjectiveNumber (int number)
set the objective number.
Parameters:
number holds the objective number.
Returns:
whether the objective number is set successfully.
Definition at line 1611 of file OSInstance.cpp.
References instanceData, Objectives::numberOfObjectives, Objectives::obj, and InstanceData::objectives.
Referenced by OSnl2osil::createOSInstance(), OSmps2osil::createOSInstance(), OSMatlab::createOSInstance(), and main().
bool OSInstance::addObjective (int index, std::string name, std::string maxOrMin, double constant, double weight, SparseVector * objectiveCoefficients)
add an objective.
In order to use the add method, the setObjectiveNumber must first be called so that the objective number is known ahead of time to assign appropriate memory. If a objective with the given objective index already exists, the old objective will be replaced. Objective index will start from -1, -2, -3, ... down, with -1 corresponding to the first objective.
Parameters:
index holds the objective index. Remember the first objective index is -1, second -2, ...
name holds the objective name; use null or empty std::string ("") if no objective name.
maxOrMin holds the objective sense or direction; it can only take two values: "max" or "min".
constant holds the objective constant; use 0.0 if no objective constant.
weight holds the objective weight; use 1.0 if no objective weight.
objectiveCoefficients holds the objective coefficients (null if no objective coefficients) in a sparse representation that holds two arrays: index array and a value array.
Returns:
whether the objective is added successfully.
Referenced by OSnl2osil::createOSInstance(), OSmps2osil::createOSInstance(), OSMatlab::createOSInstance(), and main().
bool OSInstance::setObjectives (int number, std::string * names, std::string * maxOrMins, double * constants, double * weights, SparseVector ** objectitiveCoefficients)
set all the objectives related elements.
All the previous objective-related elements will be deleted.
Parameters:
number holds the number of objectives. It is required.
names holds a std::string array of objective names; use null if no objective names.
maxOrMins holds a std::string array of objective objective senses or directions: "max" or "min"; use null if all objectives are "min".
constants holds a double array of objective constants; use null if all objective constants are 0.0.
weights holds a double array of objective weights; use null if all objective weights are 1.0.
objectitiveCoefficients holds an array of objective coefficients, (null if no objective have any coefficeints) For each objective, the coefficients are stored in a sparse representation that holds two arrays: index array and a value array. If for a specific objective, there are no objecitve coefficients, use null for the corresponding array member.
Returns:
whether the objectives are set successfully.
bool OSInstance::setConstraintNumber (int number)
set the constraint number.
Parameters:
number holds the constraint number.
Returns:
whether the constraint number is set successfully.
Definition at line 1704 of file OSInstance.cpp.
References Constraints::con, InstanceData::constraints, instanceData, and Constraints::numberOfConstraints.
Referenced by LindoSolver::buildSolverInstance(), OSnl2osil::createOSInstance(), OSmps2osil::createOSInstance(), and main().
bool OSInstance::addConstraint (int index, std::string name, double lowerBound, double upperBound, double constant)
add a constraint.
In order to use the add method, the setConstraintNumber must first be called so that the constraint number is known ahead of time to assign appropriate memory. If a constraint with the given constraint index already exists, the old constraint will be replaced.
Parameters:
index holds the constraint index. It is required.
name holds the constraint name; use null or empty std::string ("") if no constraint name.
lowerBound holds the constraint lower bound; use Double.NEGATIVE_INFINITY if no lower bound.
upperBound holds the constraint upper bound; use Double.POSITIVE_INFINITY if no upper bound.
Returns:
whether the constraint is added successfully.
Referenced by LindoSolver::buildSolverInstance(), OSnl2osil::createOSInstance(), OSmps2osil::createOSInstance(), and main().
bool OSInstance::setConstraints (int number, std::string * names, double * lowerBounds, double * upperBounds, double * constants)
set all the constraint related elements.
All the previous constraint-related elements will be deleted.
Parameters:
number holds the number of constraints. It is required.
names holds a std::string array of constraint names; use null if no constraint names.
lowerBounds holds a double array of constraint lower bounds; use null if no lower bounds; use Double.NEGATIVE_INFINITY if no lower bound for a specific constraint in the array.
upperBounds holds a double array of constraint upper bounds; use null if no upper bounds; use Double.POSITIVE_INFINITY if no upper bound for a specific constraint in the array.
Returns:
whether the constraints are set successfully.
Referenced by OSMatlab::createOSInstance().
bool OSInstance::setLinearConstraintCoefficients (int numberOfValues, bool isColumnMajor, double * values, int valuesBegin, int valuesEnd, int * indexes, int indexesBegin, int indexesEnd, int * starts, int startsBegin, int startsEnd)
set linear constraint coefficients
Parameters:
numberOfValues holds the number of specified coefficient values (usually nonzero) in the coefficient matrix.
isColumnMajor holds whether the coefficient matrix is stored in column major (true) or row major (false).
values holds a double array coefficient values in the matrix.
valuesBegin holds the begin index of the values array to copy from (usually 0).
valuesEnd holds the end index of the values array to copy till (usually values.lenght - 1).
indexes holds an integer array column/row indexes for each value in the values array.
indexesBegin holds the begin index of the indexes array to copy from (usually 0).
indexesEnd holds the end index of the indexes array to copy till (usually indexes.lenght - 1).
starts holds an integer array start indexes in the matrix; the first value of starts should always be 0.
startsBegin holds the begin index of the starts array to copy from (usually 0).
startsEnd holds the end index of the starts array to copy till (usually starts.lenght - 1).
Returns:
whether the linear constraint coefficients are set successfully.
Definition at line 1774 of file OSInstance.cpp.
References LinearConstraintCoefficients::colIdx, DoubleVector::el, IntVector::el, instanceData, InstanceData::linearConstraintCoefficients, LinearConstraintCoefficients::numberOfValues, LinearConstraintCoefficients::rowIdx, LinearConstraintCoefficients::start, and LinearConstraintCoefficients::value.
Referenced by OSnl2osil::createOSInstance(), OSmps2osil::createOSInstance(), OSMatlab::createOSInstance(), and main().
bool OSInstance::setQuadraticTerms (int number, int * rowIndexes, int * varOneIndexes, int * varTwoIndexes, double * coefficients, int begin, int end)
set quadratic terms
Parameters:
number holds the number of quadratic terms.
rowIndexes holds an integer array of row indexes of all the quadratic terms. A negative integer corresponds to an objective row, e.g. -1 for 1st objective and -2 for 2nd.
varOneIndexes holds an integer array of the first varialbe indexes of all the quadratic terms.
varTwoIndexes holds an integer array of the second varialbe indexes of all the quadratic terms.
coefficients holds a double array all the quadratic term coefficients.
begin holds the begin index of all the arrays to copy from (usually = 0).
end holds the end index of all the arrays to copy till (usually = array length -1).
Returns:
whether the quadratic terms are set successfully.
Definition at line 1847 of file OSInstance.cpp.
References QuadraticTerm::coef, QuadraticTerm::idx, QuadraticTerm::idxOne, QuadraticTerm::idxTwo, instanceData, QuadraticCoefficients::numberOfQuadraticTerms, QuadraticCoefficients::qTerm, and InstanceData::quadraticCoefficients.
bool OSInstance::setQuadraticTermsInNonlinearExpressions (int number, int * rowIndexes, int * varOneIndexes, int * varTwoIndexes, double * coefficients)
set quadratic terms in nonlinearExpressions
Parameters:
number holds the number of quadratic terms.
rowIndexes holds an integer array of row indexes of all the quadratic terms. A negative integer corresponds to an objective row, e.g. -1 for 1st objective and -2 for 2nd.
varOneIndexes holds an integer array of the first varialbe indexes of all the quadratic terms.
varTwoIndexes holds an integer array of the second varialbe indexes of all the quadratic terms.
coefficients holds a double array all the quadratic term coefficients.
Returns:
whether the quadratic terms are set successfully.
Definition at line 1877 of file OSInstance.cpp.
References OSnLNodeVariable::coef, OSnLNode::createExpressionTreeFromPostfix(), OSnLNodeVariable::idx, Nl::idx, instanceData, OSExpressionTree::m_treeRoot, NonlinearExpressions::nl, InstanceData::nonlinearExpressions, NonlinearExpressions::numberOfNonlinearExpressions, and Nl::osExpressionTree.
Referenced by OSMatlab::createOSInstance().
bool OSInstance::initializeNonLinearStructures ()
Initialize the data structures for the nonlinear API.
Returns:
true if we have initialized the nonlinear data strucutres.
Definition at line 1913 of file OSInstance.cpp.
References addQTermsToExressionTree(), InstanceData::constraints, duplicateExpressionTreesMap(), getAllNonlinearExpressionTrees(), getAllNonlinearVariablesIndexMap(), getDenseObjectiveCoefficients(), getNumberOfQuadraticTerms(), instanceData, m_bDuplicateExpressionTreesMap, m_bNonLinearStructuresInitialized, m_bProcessConstraints, m_bProcessExpressionTrees, m_bProcessObjectives, m_bProcessVariables, m_iConstraintNumber, m_iObjectiveNumber, m_iVariableNumber, m_mapExpressionTreesMod, m_mdConstraintFunctionValues, m_mdObjectiveFunctionValues, Constraints::numberOfConstraints, Objectives::numberOfObjectives, Variables::numberOfVariables, InstanceData::objectives, processConstraints(), processObjectives(), processVariables(), and InstanceData::variables.
Referenced by getAllNonlinearExpressionTreesMod(), getJacobianSparsityPattern(), initForAlgDiff(), and LindoSolver::processNonlinearExpressions().
double OSInstance::calculateFunctionValue (int idx, double * x, bool new_x)
Calculate the function value for function (constraint or objective) indexed by idx.
Parameters:
idx is the index on the constraint (0, 1, 2, 3, ...) or objective function (-1, -2, -3, ...).
x is a pointer (double array) to the current variable values
new_x is false if any evaluation method was previously called for the current x has been evaluated for the current iterate x use a value of false if not sure
Returns:
the function value as a double.
Definition at line 2078 of file OSInstance.cpp.
References SparseJacobianMatrix::conVals, ErrorClass::errormsg, getConstraintNumber(), getJacobianSparsityPattern(), getObjectiveCoefficients(), getObjectiveNumber(), SparseVector::indexes, SparseJacobianMatrix::indexes, initForAlgDiff(), m_binitForAlgDiff, m_bSparseJacobianCalculated, m_mapExpressionTreesMod, m_mdConstraintConstants, m_mdConstraintFunctionValues, m_mdObjectiveConstants, m_mdObjectiveFunctionValues, m_sparseJacMatrix, SparseVector::number, SparseJacobianMatrix::starts, SparseVector::values, and SparseJacobianMatrix::values.
Referenced by calculateAllConstraintFunctionValues(), calculateAllObjectiveFunctionValues(), and main().
double * OSInstance::calculateAllConstraintFunctionValues (double * x, double * objLambda, double * conLambda, bool new_x, int highestOrder)
Calculate all of the constraint function values.
Parameters:
x is a pointer (double array) to the current variable values
objLambda is the Lagrange multiplier on the objective function
conLambda is pointer (double array) of Lagrange multipliers on the constratins
new_x is false if any evaluation method was previously called for the current x for the current iterate
highestOrder is the highest order of the derivative being calculated
Returns:
a double array of constraint function values -- the size of the array is equal to getConstraintNumber().
Definition at line 2138 of file OSInstance.cpp.
References ErrorClass::errormsg, getIterateResults(), m_iHighestOrderEvaluated, and m_mdConstraintFunctionValues.
Referenced by IpoptProblem::eval_g(), KnitroProblem::evalFC(), getIterateResults(), and main().
double * OSInstance::calculateAllConstraintFunctionValues (double * x, bool new_x)
Calculate all of the constraint function values, we are overloading this function and this version of the method will not use any AD and will evaluate function values from the OS Expression Tree.
Parameters:
x is a pointer (double array) to the current variable values
new_x is false if any evaluation method was previously called for the current iterate
Returns:
a double array of constraint function values -- the size of the array is equal to getConstraintNumber().
Definition at line 2151 of file OSInstance.cpp.
References calculateFunctionValue(), ErrorClass::errormsg, getConstraintNumber(), m_iHighestOrderEvaluated, and m_mdConstraintFunctionValues.
double * OSInstance::calculateAllObjectiveFunctionValues (double * x, double * objLambda, double * conLambda, bool new_x, int highestOrder)
Calculate all of the objective function values.
Parameters:
x is a pointer (double array) to the current variable values
objLambda is the Lagrange multiplier on the objective function
conLambda is pointer (double array) of Lagrange multipliers on the constratins
new_x is false if any evaluation method was previously called for the current iterate
highestOrder is the highest order of the derivative being calculated
Returns:
a double array of objective function values -- the size of the array is equal to getObjectiveNumber().
Definition at line 2170 of file OSInstance.cpp.
References ErrorClass::errormsg, getIterateResults(), m_iHighestOrderEvaluated, and m_mdObjectiveFunctionValues.
Referenced by IpoptProblem::eval_f(), KnitroProblem::evalFC(), getIterateResults(), and main().
double * OSInstance::calculateAllObjectiveFunctionValues (double * x, bool new_x)
Calculate all of the objective function values, we are overloading this function and this version of the method will not use any AD and will evaluate function values from the OS Expression Tree.
Parameters:
x is a pointer (double array) to the current variable values
new_x is false if any evaluation method was previously called for the current iterate
Returns:
a double array of objective function values -- the size of the array is equal to getConstraintNumber().
Definition at line 2183 of file OSInstance.cpp.
References calculateFunctionValue(), ErrorClass::errormsg, getObjectiveNumber(), m_iHighestOrderEvaluated, and m_mdObjectiveFunctionValues.
SparseJacobianMatrix * OSInstance::calculateAllConstraintFunctionGradients (double * x, double * objLambda, double * conLambda, bool new_x, int highestOrder)
Calculate the gradient of all constraint functions.
Parameters:
x is a pointer (double array) to the current variable values
objLambda is the Lagrange multiplier on the objective function
conLambda is pointer (double array) of Lagrange multipliers on the constratins
new_x is false if any evaluation method was previously called for the current iterate
highestOrder is the highest order of the derivative being calculated
Returns:
a pointer a SparseJacobianMatrix.
Definition at line 2201 of file OSInstance.cpp.
References ErrorClass::errormsg, getIterateResults(), m_iHighestOrderEvaluated, and m_sparseJacMatrix.
Referenced by IpoptProblem::eval_jac_g(), KnitroProblem::evalGA(), and main().
SparseVector * OSInstance::calculateConstraintFunctionGradient (double * x, double * objLambda, double * conLambda, int idx, bool new_x, int highestOrder)
Calculate the gradient of the constraint function indexed by idx.
Parameters:
x is a pointer (double array) to the current variable values
objLambda is the Lagrange multiplier on the objective function
conLambda is pointer (double array) of Lagrange multipliers on the constratins idx is the index of the constraint function gradient
new_x is false if any evaluation method was previously called for the current iterate
highestOrder is the highest order of the derivative being calculated
Returns:
a pointer to a sparse vector of doubles.
Definition at line 2216 of file OSInstance.cpp.
References SparseVector::bDeleteArrays, ErrorClass::errormsg, getIterateResults(), SparseVector::indexes, instanceData, m_iHighestOrderEvaluated, m_mdJacValue, m_miJacIndex, m_miJacStart, SparseVector::number, Variables::numberOfVariables, SparseVector::values, and InstanceData::variables.
Referenced by main().
SparseVector * OSInstance::calculateConstraintFunctionGradient (double * x, int idx, bool new_x)
Calculate the gradient of the constraint function indexed by idx this function is overloaded.
Parameters:
x is a pointer (double array) to the current variable values idx is the index of the constraint function gradient
new_x is false if any evaluation method was previously called for the current iterate
highestOrder is the highest order of the derivative being calculated
Returns:
a pointer to a sparse vector of doubles.
Definition at line 2243 of file OSInstance.cpp.
References SparseVector::bDeleteArrays, ErrorClass::errormsg, getIterateResults(), SparseVector::indexes, instanceData, m_iHighestOrderEvaluated, m_mdJacValue, m_miJacIndex, m_miJacStart, SparseVector::number, Variables::numberOfVariables, SparseVector::values, and InstanceData::variables.
double ** OSInstance::calculateAllObjectiveFunctionGradients (double * x, double * objLambda, double * conLambda, bool new_x, int highestOrder)
Calculate the gradient of all objective functions.
Parameters:
x is a pointer (double array) to the current variable values
objLambda is the Lagrange multiplier on the objective function
conLambda is pointer (double array) of Lagrange multipliers on the constratins
new_x is false if any evaluation method was previously called for the current iterate
highestOrder is the highest order of the derivative being calculated
Returns:
an array of pointer to dense objective function gradients.
Definition at line 2268 of file OSInstance.cpp.
References ErrorClass::errormsg, getIterateResults(), m_iHighestOrderEvaluated, and m_mmdObjGradient.
Referenced by KnitroProblem::evalGA().
double * OSInstance::calculateObjectiveFunctionGradient (double * x, double * objLambda, double * conLambda, int objIdx, bool new_x, int highestOrder)
Calculate the gradient of the objective function indexed by objIdx.
Parameters:
x is a pointer (double array) to the current variable values
objLambda is the Lagrange multiplier on the objective function
conLambda is pointer (double array) of Lagrange multipliers on the constratins objIdx is the index of the objective function being optimized
new_x is false if any evaluation method was previously called for the current iterate
highestOrder is the highest order of the derivative being calculated
Returns:
a pointer to a dense vector of doubles.
Definition at line 2281 of file OSInstance.cpp.
References ErrorClass::errormsg, getIterateResults(), m_iHighestOrderEvaluated, and m_mmdObjGradient.
Referenced by IpoptProblem::eval_grad_f(), and main().
double * OSInstance::calculateObjectiveFunctionGradient (double * x, int objIdx, bool new_x)
Calculate the gradient of the objective function indexed by objIdx this function is overloaded.
Parameters:
x is a pointer (double array) to the current variable values objIdx is the index of the objective function being optimized
new_x is false if any evaluation method was previously called for the current iterate
highestOrder is the highest order of the derivative being calculated
Returns:
a pointer to a dense vector of doubles.
Definition at line 2295 of file OSInstance.cpp.
References ErrorClass::errormsg, getIterateResults(), m_iHighestOrderEvaluated, and m_mmdObjGradient.
SparseHessianMatrix * OSInstance::calculateLagrangianHessian (double * x, double * objLambda, double * conLambda, bool new_x, int highestOrder)
Calculate the Hessian of the Lagrangian Expression Tree This method will build the CppAD expression tree for only the first iteration Use this method on if the value of x does not affect the operations sequence.
Parameters:
x is a pointer (double array) to the current variable values
objLambda is the Lagrange multiplier on the objective function
conLambda is pointer (double array) of Lagrange multipliers on the constratins
new_x is false if any evaluation method was previously called for the current iterate
highestOrder is the highest order of the derivative being calculated
Returns:
a pointer a SparseHessianMatrix. Each array member corresponds to one constraint gradient.
Definition at line 2306 of file OSInstance.cpp.
References ErrorClass::errormsg, getIterateResults(), m_iHighestOrderEvaluated, and m_LagrangianSparseHessian.
Referenced by IpoptProblem::eval_h(), KnitroProblem::evalH(), and main().
SparseHessianMatrix * OSInstance::calculateHessian (double * x, int idx, bool new_x)
Calculate the Hessian of a constraint or objective function.
Parameters:
x is a pointer (double array) to the current variable values
new_x is false if any evaluation method was previously called for the current iterate idx is the index of the either a constraint or objective function Hessian
Returns:
a pointer a SparseVector. Each array member corresponds to one constraint gradient.
Definition at line 2321 of file OSInstance.cpp.
References ErrorClass::errormsg, getConstraintNumber(), getIterateResults(), getObjectiveNumber(), instanceData, m_iHighestOrderEvaluated, m_LagrangianSparseHessian, Variables::numberOfVariables, and InstanceData::variables.
Referenced by main().
bool OSInstance::getSparseJacobianFromColumnMajor ()
Returns:
true if successful in generating the constraints gradient.
Definition at line 2360 of file OSInstance.cpp.
References OSnLNodeVariable::coef, DoubleVector::el, IntVector::el, getConstraintNumber(), getVariableNumber(), OSnLNodeVariable::idx, instanceData, InstanceData::linearConstraintCoefficients, m_bColumnMajor, m_iJacValueSize, m_mapExpressionTreesMod, OSnLNode::m_mChildren, m_mdJacValue, m_miJacIndex, m_miJacNumConTerms, m_miJacStart, OSExpressionTree::m_treeRoot, LinearConstraintCoefficients::rowIdx, LinearConstraintCoefficients::start, and LinearConstraintCoefficients::value.
Referenced by getJacobianSparsityPattern().
bool OSInstance::getSparseJacobianFromRowMajor ()
Returns:
true if successful in generating the constraints gradient.
Definition at line 2506 of file OSInstance.cpp.
References OSnLNodeVariable::coef, LinearConstraintCoefficients::colIdx, DoubleVector::el, IntVector::el, getConstraintNumber(), OSnLNodeVariable::idx, instanceData, InstanceData::linearConstraintCoefficients, m_bColumnMajor, m_iJacValueSize, m_mapExpressionTreesMod, OSnLNode::m_mChildren, m_mdJacValue, m_miJacIndex, m_miJacNumConTerms, m_miJacStart, LinearConstraintCoefficients::start, and LinearConstraintCoefficients::value.
Referenced by getJacobianSparsityPattern().
OSExpressionTree * OSInstance::getLagrangianExpTree ()
Returns:
a pointer to the ExpressionTree for the Lagrangian function of current instance we only take the Lagrangian of the rows with nonlinear terms
Definition at line 2639 of file OSInstance.cpp.
References OSnLNodeVariable::coef, InstanceData::constraints, getJacobianSparsityPattern(), OSExpressionTree::getVariableIndiciesMap(), OSnLNodeVariable::idx, instanceData, OSnLNode::inumberOfChildren, m_bLagrangianExpTreeCreated, m_bSparseJacobianCalculated, m_LagrangianExpTree, m_mapExpressionTreesMod, OSnLNode::m_mChildren, OSExpressionTree::m_treeRoot, Constraints::numberOfConstraints, Variables::numberOfVariables, and InstanceData::variables.
std::map< int, int > OSInstance::getAllNonlinearVariablesIndexMap ()
Returns:
a pointer to a map of the indices of all of the variables that appear in the Lagrangian function
Definition at line 2691 of file OSInstance.cpp.
References OSExpressionTree::getVariableIndiciesMap(), m_bAllNonlinearVariablesIndex, OSExpressionTree::m_bIndexMapGenerated, m_iNumberOfNonlinearVariables, m_mapAllNonlinearVariablesIndex, m_mapExpressionTreesMod, m_miNonLinearVarsReverseMap, and OSExpressionTree::mapVarIdx.
Referenced by initForAlgDiff(), initializeNonLinearStructures(), and main().
SparseHessianMatrix * OSInstance::getLagrangianHessianSparsityPattern ()
Returns:
a pointer to a SparseHessianMatrix with the nonzero structure of the Lagrangian Expression Tree
Definition at line 2728 of file OSInstance.cpp.
References SparseHessianMatrix::bDeleteArrays, createCppADFun(), SparseHessianMatrix::hessColIdx, SparseHessianMatrix::hessDimension, SparseHessianMatrix::hessRowIdx, SparseHessianMatrix::hessValues, initForAlgDiff(), m_bCppADFunIsCreated, m_bCppADMustReTape, m_binitForAlgDiff, m_bLagrangianSparseHessianCreated, m_iNumberOfNonlinearVariables, m_LagrangianSparseHessian, m_mapAllNonlinearVariablesIndex, m_mapExpressionTreesMod, and m_vbLagHessNonz.
Referenced by IpoptProblem::eval_h(), IpoptProblem::get_nlp_info(), KnitroProblem::loadProblemIntoKnitro(), and main().
bool OSInstance::addQTermsToExressionTree ()
Returns:
true if successful in adding the qTerms to the ExpressionTree.
Definition at line 1979 of file OSInstance.cpp.
References OSnLNodeVariable::coef, QuadraticTerms::coefficients, getNumberOfNonlinearObjectives(), getQuadraticTerms(), OSExpressionTree::getVariableIndiciesMap(), OSnLNodeVariable::idx, instanceData, OSExpressionTree::m_bIndexMapGenerated, m_bProcessExpressionTrees, m_bQTermsAdded, m_iConstraintNumberNonlinear, m_iNonlinearExpressionNumber, m_iObjectiveNumberNonlinear, m_mapExpressionTrees, m_mapExpressionTreesMod, OSnLNode::m_mChildren, m_quadraticTerms, OSExpressionTree::m_treeRoot, OSExpressionTree::mapVarIdx, QuadraticCoefficients::numberOfQuadraticTerms, InstanceData::quadraticCoefficients, QuadraticTerms::rowIndexes, QuadraticTerms::varOneIndexes, and QuadraticTerms::varTwoIndexes.
Referenced by initializeNonLinearStructures().
SparseJacobianMatrix * OSInstance::getJacobianSparsityPattern ()
Returns:
pointer to a SparseJacobianMatrix.
Definition at line 1942 of file OSInstance.cpp.
References SparseJacobianMatrix::bDeleteArrays, SparseJacobianMatrix::conVals, ErrorClass::errormsg, getLinearConstraintCoefficientMajor(), getSparseJacobianFromColumnMajor(), getSparseJacobianFromRowMajor(), SparseJacobianMatrix::indexes, initializeNonLinearStructures(), m_bColumnMajor, m_bNonLinearStructuresInitialized, m_bSparseJacobianCalculated, m_iJacValueSize, m_mdJacValue, m_miJacIndex, m_miJacNumConTerms, m_miJacStart, m_sparseJacMatrix, SparseJacobianMatrix::starts, SparseJacobianMatrix::values, and SparseJacobianMatrix::valueSize.
Referenced by calculateFunctionValue(), IpoptProblem::eval_jac_g(), IpoptProblem::get_nlp_info(), getLagrangianExpTree(), initForAlgDiff(), KnitroProblem::loadProblemIntoKnitro(), and main().
void OSInstance::duplicateExpressionTreesMap ()
duplicate the map of expression trees.
Definition at line 2813 of file OSInstance.cpp.
References getAllNonlinearExpressionTrees(), m_bDuplicateExpressionTreesMap, m_bProcessExpressionTrees, m_mapExpressionTrees, and m_mapExpressionTreesMod.
Referenced by initializeNonLinearStructures().
bool OSInstance::createCppADFun (std::vector< double > vdX)
Create the a CppAD Function object: this is a function where the domain is the set of variables for the problem and the range is the objective function plus constraints.
Parameters:
vdX is a vector of doubles holding the current primal variable values the size of x should equal instanceData->variables->numberOfVariables
Returns:
if successfully created
For expression tree, record the operations for CppAD and put into the range vector m_vFG and it is a vector of CppAD objective and constraint functions.
Definition at line 2829 of file OSInstance.cpp.
References Fad, initForAlgDiff(), m_bCppADFunIsCreated, m_binitForAlgDiff, m_iHighestTaylorCoeffOrder, m_mapAllNonlinearVariablesIndex, m_mapCppADFunRangeIndex, and m_mapExpressionTreesMod.
Referenced by forwardAD(), getIterateResults(), and getLagrangianHessianSparsityPattern().
std::vector< double > OSInstance::forwardAD (int p, std::vector< double > vdX)
Perform an AD forward sweep.
Parameters:
p is the highest order Taylor coefficient
vdX is a vector of doubles of the current primal variable values the size of vdX m_iNumberOfNonlinearVariables
Returns:
a double vector equal to the dimension of the range space the result of the forward p sweep
Definition at line 2873 of file OSInstance.cpp.
References createCppADFun(), ErrorClass::errormsg, m_bCppADFunIsCreated, m_iHighestOrderEvaluated, and m_iHighestTaylorCoeffOrder.
Referenced by getFirstOrderResults(), getSecondOrderResults(), getZeroOrderResults(), and main().
std::vector< double > OSInstance::reverseAD (int p, std::vector< double > vdlambda)
Perform an AD reverse sweep.
Parameters:
p is the order of the sweep
vdlambda is a vector of doubles of the current dual (lagrange) variable values the size of lambda should equal number of objective functions plus number of constraints
Returns:
a double vector equal to the n*p
Definition at line 2893 of file OSInstance.cpp.
References ErrorClass::errormsg, m_iHighestOrderEvaluated, and m_iHighestTaylorCoeffOrder.
Referenced by getFirstOrderResults(), getSecondOrderResults(), and main().
bool OSInstance::getIterateResults (double * x, double * objLambda, double * conLambda, bool new_x, int highestOrder)
end revised AD code
Get the information for each iteration. Get the functions values, Jacobian and Hessian of the Lagrangian
Parameters:
x is a pointer of doubles of primal values for the current iteration
objLambda is is a pointer of doubles of the current dual (Lagrange) multipliers on the objective functions
conLambda is a pointer of doubles of the current dual (Lagrange) multipliers on the constraints
new_x is false if any evaluation method was previously called
highestOrder is the highest order derivative to be calculated
Returns:
true if successful
Definition at line 2910 of file OSInstance.cpp.
References bUseExpTreeForFunEval, calculateAllConstraintFunctionValues(), calculateAllObjectiveFunctionValues(), createCppADFun(), ErrorClass::errormsg, getFirstOrderResults(), getSecondOrderResults(), getZeroOrderResults(), initForAlgDiff(), m_bCppADFunIsCreated, m_bCppADMustReTape, m_binitForAlgDiff, m_iHighestOrderEvaluated, m_mapAllNonlinearVariablesIndex, m_mapExpressionTreesMod, and m_vdX.
Referenced by calculateAllConstraintFunctionGradients(), calculateAllConstraintFunctionValues(), calculateAllObjectiveFunctionGradients(), calculateAllObjectiveFunctionValues(), calculateConstraintFunctionGradient(), calculateHessian(), calculateLagrangianHessian(), and calculateObjectiveFunctionGradient().
bool OSInstance::getZeroOrderResults (double * x, double * objLambda, double * conLambda)
Calculate function values.
Parameters:
x is a pointer of doubles of primal values for the current iteration
objLambda is is a pointer of doubles of the current dual (Lagrange) multipliers on the objective functions
conLambda is a pointer of doubles of the current dual (Lagrange) multipliers on the constraints
Returns:
true if successful
Definition at line 2961 of file OSInstance.cpp.
References SparseJacobianMatrix::conVals, ErrorClass::errormsg, forwardAD(), SparseJacobianMatrix::indexes, m_iConstraintNumber, m_iObjectiveNumber, m_iVariableNumber, m_mapCppADFunRangeIndex, m_mapExpressionTreesMod, m_mdConstraintConstants, m_mdConstraintFunctionValues, m_mdObjectiveFunctionValues, m_mmdDenseObjectiveCoefficients, m_sparseJacMatrix, m_vdX, m_vdYval, SparseJacobianMatrix::starts, and SparseJacobianMatrix::values.
Referenced by getIterateResults().
bool OSInstance::getFirstOrderResults (double * x, double * objLambda, double * conLambda)
Calculate first derivatives.
Parameters:
x is a pointer of doubles of primal values for the current iteration
objLambda is is a pointer of doubles of the current dual (Lagrange) multipliers on the objective functions
conLambda is a pointer of doubles of the current dual (Lagrange) multipliers on the constraints
Returns:
true if successful
if the number of columns exceeds the number of rows we will get the Jacobian by row, however, if the number of rows exceeds the number of columns we get the Jacobian by column
Definition at line 3010 of file OSInstance.cpp.
References ErrorClass::errormsg, forwardAD(), SparseJacobianMatrix::indexes, m_iConstraintNumber, m_iNumberOfNonlinearVariables, m_iObjectiveNumber, m_iVariableNumber, m_mapAllNonlinearVariablesIndex, m_mapExpressionTreesMod, m_mdJacValue, m_miJacNumConTerms, m_miJacStart, m_miNonLinearVarsReverseMap, m_mmdDenseObjectiveCoefficients, m_mmdObjGradient, m_sparseJacMatrix, m_vdDomainUnitVec, m_vdRangeUnitVec, m_vdYjacval, OSExpressionTree::mapVarIdx, reverseAD(), SparseJacobianMatrix::starts, and SparseJacobianMatrix::values.
Referenced by getIterateResults().
bool OSInstance::getSecondOrderResults (double * x, double * objLambda, double * conLambda)
Calculate second derivatives.
Parameters:
x is a pointer of doubles of primal values for the current iteration
objLambda is is a pointer of doubles of the current dual (Lagrange) multipliers on the objective functions
conLambda is a pointer of doubles of the current dual (Lagrange) multipliers on the constraints
Returns:
true if successful
Definition at line 3137 of file OSInstance.cpp.
References ErrorClass::errormsg, forwardAD(), SparseHessianMatrix::hessValues, SparseJacobianMatrix::indexes, m_iConstraintNumber, m_iNumberOfNonlinearVariables, m_iObjectiveNumber, m_LagrangianSparseHessian, m_mapExpressionTreesMod, m_mdJacValue, m_miJacNumConTerms, m_miJacStart, m_miNonLinearVarsReverseMap, m_mmdDenseObjectiveCoefficients, m_mmdObjGradient, m_sparseJacMatrix, m_vbLagHessNonz, m_vdDomainUnitVec, m_vdLambda, m_vdw, m_vdYjacval, OSExpressionTree::mapVarIdx, reverseAD(), SparseJacobianMatrix::starts, and SparseJacobianMatrix::values.
Referenced by getIterateResults().
bool OSInstance::initForAlgDiff ()
This should be called by nonlinear solvers using callback functions.
initForAlgDiff will initialize the correct nonlinear structures in preparation for using the algorithmic differentiation routines.
Returns:
true if successful
Definition at line 3224 of file OSInstance.cpp.
References getAllNonlinearVariablesIndexMap(), getJacobianSparsityPattern(), initializeNonLinearStructures(), initObjGradients(), m_bCppADMustReTape, m_binitForAlgDiff, m_bSparseJacobianCalculated, m_iNumberOfNonlinearVariables, m_mapExpressionTreesMod, m_vdDomainUnitVec, and m_vdRangeUnitVec.
Referenced by calculateFunctionValue(), createCppADFun(), IpoptProblem::get_nlp_info(), getIterateResults(), getLagrangianHessianSparsityPattern(), KnitroProblem::loadProblemIntoKnitro(), and main().
bool OSInstance::initObjGradients ()
This should be called by initForAlgDiff().
initObjGradients will initialize the objective function gradients to be equal to the coefficients given in the <coef> section of the OSiL instance
Returns:
true if successful
Definition at line 3251 of file OSInstance.cpp.
References getDenseObjectiveCoefficients(), getObjectiveNumber(), getVariableNumber(), m_mmdDenseObjectiveCoefficients, and m_mmdObjGradient.
Referenced by initForAlgDiff().
Member Data Documentation
InstanceHeader* OSInstance::instanceHeader
A pointer to an InstanceHeader object.
Definition at line 644 of file OSInstance.h.
Referenced by getInstanceDescription(), getInstanceName(), getInstanceSource(), OSInstance(), OSiLWriter::writeOSiL(), and ~OSInstance().
InstanceData* OSInstance::instanceData
A pointer to an InstanceData object.
Definition at line 647 of file OSInstance.h.
Referenced by addQTermsToExressionTree(), LindoSolver::buildSolverInstance(), calculateConstraintFunctionGradient(), calculateHessian(), OSnl2osil::createOSInstance(), LindoSolver::dataEchoCheck(), KnitroSolver::dataEchoCheck(), IpoptSolver::dataEchoCheck(), CoinSolver::dataEchoCheck(), IpoptProblem::get_scaling_parameters(), getAllNonlinearExpressionTrees(), getConstraintNumber(), getDenseObjectiveCoefficients(), getLagrangianExpTree(), getLinearConstraintCoefficientNumber(), getNumberOfNonlinearExpressions(), getNumberOfQuadraticTerms(), getObjectiveNumber(), getQuadraticTerms(), getSparseJacobianFromColumnMajor(), getSparseJacobianFromRowMajor(), getVariableNumber(), initializeNonLinearStructures(), KnitroProblem::loadProblemIntoKnitro(), main(), OSInstance(), processConstraints(), processLinearConstraintCoefficients(), processObjectives(), processVariables(), setConstraintNumber(), setLinearConstraintCoefficients(), setObjectiveNumber(), setQuadraticTerms(), setQuadraticTermsInNonlinearExpressions(), setVariableNumber(), IpoptSolver::solve(), OSiLWriter::writeOSiL(), ~OSInstance(), OSmps2osil::~OSmps2osil(), and OSnl2osil::~OSnl2osil().
std::string OSInstance::m_sInstanceName [private]
m_sInstanceName holds the instance name.
Definition at line 653 of file OSInstance.h.
Referenced by getInstanceName().
std::string OSInstance::m_sInstanceSource [private]
m_sInstanceSource holds the instance source.
Definition at line 657 of file OSInstance.h.
Referenced by getInstanceSource().
std::string OSInstance::m_sInstanceDescription [private]
m_sInstanceDescription holds the instance description.
Definition at line 661 of file OSInstance.h.
Referenced by getInstanceDescription().
bool OSInstance::m_bProcessVariables [private]
m_bProcessVariables holds whether the variables are processed.
Definition at line 666 of file OSInstance.h.
Referenced by initializeNonLinearStructures(), and processVariables().
int OSInstance::m_iVariableNumber [private]
m_iVariableNumber holds the variable number.
Definition at line 671 of file OSInstance.h.
Referenced by getFirstOrderResults(), getVariableNumber(), getZeroOrderResults(), and initializeNonLinearStructures().
int OSInstance::m_iNumberOfIntegerVariables [private]
m_iNumberOfIntegerVariables holds the number of integer variables.
Definition at line 676 of file OSInstance.h.
Referenced by getNumberOfIntegerVariables(), and processVariables().
int OSInstance::m_iNumberOfBinaryVariables [private]
m_iNumberOfBinaryVariables holds the number of binary variables.
Definition at line 681 of file OSInstance.h.
Referenced by getNumberOfBinaryVariables(), and processVariables().
int OSInstance::m_iNumberOfQuadraticRowIndexes [private]
m_iNumberOfQuadraticRowIndexes holds the number of distinct rows and objectives with quadratic terms.
Definition at line 686 of file OSInstance.h.
Referenced by getNumberOfQuadraticRowIndexes(), and getQuadraticRowIndexes().
bool OSInstance::m_bQuadraticRowIndexesProcessed [private]
m_bQuadraticRowIndexesProcessed is true if getQuadraticRowIndexes() has been called.
Definition at line 691 of file OSInstance.h.
Referenced by getNumberOfQuadraticRowIndexes(), getQuadraticRowIndexes(), and ~OSInstance().
int* OSInstance::m_miQuadRowIndexes [private]
m_miQuadRowIndexes is an integer pointer to the distinct rows indexes with a quadratic term.
Definition at line 696 of file OSInstance.h.
Referenced by getQuadraticRowIndexes(), and ~OSInstance().
int OSInstance::m_iNumberOfNonlinearExpressionTreeIndexes [private]
m_iNumberOfNonlinearExpressionTreeIndexes holds the number of distinct rows and objectives with nonlinear terms.
Definition at line 701 of file OSInstance.h.
Referenced by getNonlinearExpressionTreeIndexes(), and getNumberOfNonlinearExpressionTreeIndexes().
bool OSInstance::m_bNonlinearExpressionTreeIndexesProcessed [private]
m_bNonlinearExpressionTreeIndexesProcessed is true if getNonlinearExpressionTreeIndexes has been called.
Definition at line 706 of file OSInstance.h.
Referenced by getNonlinearExpressionTreeIndexes(), getNumberOfNonlinearExpressionTreeIndexes(), and ~OSInstance().
int* OSInstance::m_miNonlinearExpressionTreeIndexes [private]
m_miNonlinearExpressionTreeIndexes is an integer pointer to the distinct rows indexes in the nonlinear expression tree map.
Definition at line 712 of file OSInstance.h.
Referenced by getNonlinearExpressionTreeIndexes(), and ~OSInstance().
int OSInstance::m_iNumberOfNonlinearExpressionTreeModIndexes [private]
m_iNumberOfNonlinearExpressionTreeModIndexes holds the number of distinct rows and objectives with nonlinear terms including quadratic terms added to the nonlinear expression trees.
Definition at line 718 of file OSInstance.h.
Referenced by getNonlinearExpressionTreeModIndexes(), and getNumberOfNonlinearExpressionTreeModIndexes().
bool OSInstance::m_bNonlinearExpressionTreeModIndexesProcessed [private]
m_bNonlinearExpressionTreeModIndexesProcessed is true if getNonlinearExpressionTreeModIndexes has been called.
Definition at line 723 of file OSInstance.h.
Referenced by getNonlinearExpressionTreeModIndexes(), getNumberOfNonlinearExpressionTreeModIndexes(), and ~OSInstance().
int* OSInstance::m_miNonlinearExpressionTreeModIndexes [private]
m_miNonlinearExpressionTreeModIndexes is an integer pointer to the distinct rows indexes in the modified expression tree map.
Definition at line 729 of file OSInstance.h.
Referenced by getNonlinearExpressionTreeModIndexes(), and ~OSInstance().
std::string* OSInstance::m_msVariableNames [private]
m_msVariableNames holds an array of variable names.
Definition at line 734 of file OSInstance.h.
Referenced by getVariableNames(), processVariables(), and ~OSInstance().
double* OSInstance::m_mdVariableInitialValues [private]
m_mdVariableInitialValues holds a double array of the initial variable values.
Definition at line 739 of file OSInstance.h.
Referenced by getVariableInitialValues(), processVariables(), and ~OSInstance().
std::string* OSInstance::m_msVariableInitialStringValues [private]
m_msVariableInitialStringValues holds a std::string array of the initial variable values.
Definition at line 744 of file OSInstance.h.
Referenced by getVariableInitialStringValues(), processVariables(), and ~OSInstance().
char* OSInstance::m_mcVariableTypes [private]
m_mcVariableTypes holds a char array of variable types (default = 'C').
(C for Continuous; B for Binary; I for Integer; S for String)
Definition at line 750 of file OSInstance.h.
Referenced by getVariableTypes(), processVariables(), and ~OSInstance().
double* OSInstance::m_mdVariableLowerBounds [private]
m_mdVariableLowerBounds holds a double array of variable lower bounds (default = 0.0).
Definition at line 755 of file OSInstance.h.
Referenced by getVariableLowerBounds(), processVariables(), and ~OSInstance().
double* OSInstance::m_mdVariableUpperBounds [private]
m_mdVariableUpperBounds holds a double array of variable upper bounds (default = INF).
Definition at line 760 of file OSInstance.h.
Referenced by getVariableUpperBounds(), processVariables(), and ~OSInstance().
bool OSInstance::m_bProcessObjectives [private]
m_bProcessObjectives holds whether the objectives are processed.
Definition at line 765 of file OSInstance.h.
Referenced by initializeNonLinearStructures(), processObjectives(), and ~OSInstance().
int OSInstance::m_iObjectiveNumber [private]
m_iObjectiveNumber is the number of objective functions.
Definition at line 770 of file OSInstance.h.
Referenced by getFirstOrderResults(), getObjectiveNumber(), getSecondOrderResults(), getZeroOrderResults(), and initializeNonLinearStructures().
int OSInstance::m_iObjectiveNumberNonlinear [private]
m_iObjectiveNumber is the number of objective functions with a nonlinear term.
Definition at line 775 of file OSInstance.h.
Referenced by addQTermsToExressionTree(), getAllNonlinearExpressionTrees(), and getNumberOfNonlinearObjectives().
std::string* OSInstance::m_msObjectiveNames [private]
m_msObjectiveNames holds an array of objective names.
Definition at line 780 of file OSInstance.h.
Referenced by getObjectiveNames(), processObjectives(), and ~OSInstance().
std::string* OSInstance::m_msMaxOrMins [private]
m_msMaxOrMins holds a std::string array of objective maxOrMins ("max" or "min").
Definition at line 785 of file OSInstance.h.
Referenced by getObjectiveMaxOrMins(), processObjectives(), and ~OSInstance().
int* OSInstance::m_miNumberOfObjCoef [private]
m_miNumberOfObjCoef holds an integer array of number of objective coefficients (default = 0.0).
Definition at line 790 of file OSInstance.h.
Referenced by getObjectiveCoefficientNumbers(), processObjectives(), and ~OSInstance().
double* OSInstance::m_mdObjectiveConstants [private]
m_mdObjectiveConstants holds an array of objective constants (default = 0.0).
Definition at line 795 of file OSInstance.h.
Referenced by calculateFunctionValue(), getObjectiveConstants(), processObjectives(), and ~OSInstance().
double* OSInstance::m_mdObjectiveWeights [private]
m_mdObjectiveWeights holds an array of objective weights (default = 1.0).
Definition at line 800 of file OSInstance.h.
Referenced by getObjectiveWeights(), processObjectives(), and ~OSInstance().
SparseVector** OSInstance::m_mObjectiveCoefficients [private]
m_mObjectiveCoefficients holds an array of objective coefficients, one set of objective coefficients for each objective.
Definition at line 806 of file OSInstance.h.
Referenced by getObjectiveCoefficients(), processObjectives(), and ~OSInstance().
bool OSInstance::m_bGetDenseObjectives [private]
m_bGetDenseObjectives holds whether the dense objective functions are processed.
Definition at line 811 of file OSInstance.h.
Referenced by getDenseObjectiveCoefficients().
double** OSInstance::m_mmdDenseObjectiveCoefficients [private]
m_mmdDenseObjectiveCoefficients holds an array of pointers, each pointer points to a vector of dense objective function coefficients
Definition at line 817 of file OSInstance.h.
Referenced by getDenseObjectiveCoefficients(), getFirstOrderResults(), getSecondOrderResults(), getZeroOrderResults(), initObjGradients(), and ~OSInstance().
bool OSInstance::m_bProcessConstraints [private]
m_bProcessConstraints holds whether the constraints are processed.
Definition at line 822 of file OSInstance.h.
Referenced by initializeNonLinearStructures(), and processConstraints().
int OSInstance::m_iConstraintNumber [private]
m_iConstraintNumber is the number of constraints.
Definition at line 827 of file OSInstance.h.
Referenced by getConstraintNumber(), getFirstOrderResults(), getSecondOrderResults(), getZeroOrderResults(), and initializeNonLinearStructures().
int OSInstance::m_iConstraintNumberNonlinear [private]
m_iConstraintNumberNonlinear is the number of constraints that have a nonlinear term.
Definition at line 832 of file OSInstance.h.
Referenced by addQTermsToExressionTree(), getAllNonlinearExpressionTrees(), and getNumberOfNonlinearConstraints().
std::string* OSInstance::m_msConstraintNames [private]
m_msConstraintNames holds an array of constraint names.
Definition at line 837 of file OSInstance.h.
Referenced by getConstraintNames(), processConstraints(), and ~OSInstance().
double* OSInstance::m_mdConstraintLowerBounds [private]
m_mdConstraintLowerBounds holds an array of constraint lower bounds (default = -INF).
Definition at line 842 of file OSInstance.h.
Referenced by getConstraintLowerBounds(), processConstraints(), and ~OSInstance().
double* OSInstance::m_mdConstraintUpperBounds [private]
m_mdConstraintUpperBounds holds an array of constraint upper bounds (default = INF).
Definition at line 847 of file OSInstance.h.
Referenced by getConstraintUpperBounds(), processConstraints(), and ~OSInstance().
double* OSInstance::m_mdConstraintConstants [private]
m_mdConstraintConstants holds an array of constraint constants (default = 0.0).
Definition at line 853 of file OSInstance.h.
Referenced by calculateFunctionValue(), getZeroOrderResults(), processConstraints(), and ~OSInstance().
char* OSInstance::m_mcConstraintTypes [private]
m_mcConstraintTypes holds a char array of constraint types (R for range; L for <=; G for >=; E for =; U for unconstrained)
Definition at line 859 of file OSInstance.h.
Referenced by getConstraintTypes(), processConstraints(), and ~OSInstance().
bool OSInstance::m_bProcessLinearConstraintCoefficients [private]
m_bProcessLinearConstraintCoefficients holds whether the linear constraint coefficients are processed.
Definition at line 864 of file OSInstance.h.
Referenced by processLinearConstraintCoefficients(), and ~OSInstance().
int OSInstance::m_iLinearConstraintCoefficientNumber [private]
m_iLinearConstraintCoefficientNumber holds the number of specified (usually nonzero) linear constraint coefficient values.
Definition at line 870 of file OSInstance.h.
Referenced by getLinearConstraintCoefficientNumber().
bool OSInstance::m_bColumnMajor [private]
m_bColumnMajor holds whether the linear constraint coefficients are stored in column major.
Definition at line 875 of file OSInstance.h.
Referenced by getJacobianSparsityPattern(), getLinearConstraintCoefficientMajor(), getLinearConstraintCoefficientsInColumnMajor(), getLinearConstraintCoefficientsInRowMajor(), getSparseJacobianFromColumnMajor(), getSparseJacobianFromRowMajor(), processLinearConstraintCoefficients(), and ~OSInstance().
bool OSInstance::m_binitForAlgDiff [private]
m_binitForAlgDiff is true if initForAlgDiff() has been called.
Definition at line 880 of file OSInstance.h.
Referenced by calculateFunctionValue(), createCppADFun(), getIterateResults(), getLagrangianHessianSparsityPattern(), initForAlgDiff(), and ~OSInstance().
SparseMatrix* OSInstance::m_linearConstraintCoefficientsInColumnMajor [private]
m_linearConstraintCoefficientsInColumnMajor holds the standard 3 array data structure for linear constraint coefficients (starts, indexes and values) in column major.
Definition at line 887 of file OSInstance.h.
Referenced by getLinearConstraintCoefficientsInColumnMajor(), getLinearConstraintCoefficientsInRowMajor(), processLinearConstraintCoefficients(), and ~OSInstance().
SparseMatrix* OSInstance::m_linearConstraintCoefficientsInRowMajor [private]
m_linearConstraintCoefficientsInRowMajor holds the standard 3 array data structure for linear constraint coefficients (starts, indexes and values) in row major.
Definition at line 893 of file OSInstance.h.
Referenced by getLinearConstraintCoefficientsInColumnMajor(), getLinearConstraintCoefficientsInRowMajor(), processLinearConstraintCoefficients(), and ~OSInstance().
bool OSInstance::m_bProcessQuadraticTerms [private]
m_bProcessQuadraticTerms holds whether the quadratic terms are processed.
Definition at line 899 of file OSInstance.h.
Referenced by getQuadraticTerms(), and ~OSInstance().
int OSInstance::m_iQuadraticTermNumber [private]
m_iQuadraticTermNumber holds the number of specified (usually nonzero) qTerms in the quadratic coefficients.
Definition at line 905 of file OSInstance.h.
Referenced by getNumberOfQuadraticTerms().
double* OSInstance::m_mdConstraintFunctionValues [private]
m_mdConstraintFunctionValues holds a double array of constraint function values -- the size of the array is equal to getConstraintNumber().
Definition at line 910 of file OSInstance.h.
Referenced by calculateAllConstraintFunctionValues(), calculateFunctionValue(), getZeroOrderResults(), initializeNonLinearStructures(), and ~OSInstance().
double* OSInstance::m_mdObjectiveFunctionValues [private]
m_mdObjectiveFunctionValues holds a double array of objective function values -- the size of the array is equal to getObjectiveNumber().
Definition at line 915 of file OSInstance.h.
Referenced by calculateAllObjectiveFunctionValues(), calculateFunctionValue(), getZeroOrderResults(), initializeNonLinearStructures(), and ~OSInstance().
int OSInstance::m_iJacValueSize [private]
m_iJacValueSize is the number of nonzero partial derivates in the Jacobian.
Definition at line 920 of file OSInstance.h.
Referenced by getJacobianSparsityPattern(), getSparseJacobianFromColumnMajor(), and getSparseJacobianFromRowMajor().
int* OSInstance::m_miJacStart [private]
m_miJacStart holds a int array of starts for the Jacobian matrix in sparse form (row major).
Definition at line 925 of file OSInstance.h.
Referenced by calculateConstraintFunctionGradient(), getFirstOrderResults(), getJacobianSparsityPattern(), getSecondOrderResults(), getSparseJacobianFromColumnMajor(), getSparseJacobianFromRowMajor(), and ~OSInstance().
int* OSInstance::m_miJacIndex [private]
m_miJacIndex holds a int array of variable indices for the Jacobian matrix in sparse form (row major).
Definition at line 930 of file OSInstance.h.
Referenced by calculateConstraintFunctionGradient(), getJacobianSparsityPattern(), getSparseJacobianFromColumnMajor(), getSparseJacobianFromRowMajor(), and ~OSInstance().
double* OSInstance::m_mdJacValue [private]
m_mdJacValue holds a double array of partial derivatives for the Jacobian matrix in sparse form (row major).
Definition at line 935 of file OSInstance.h.
Referenced by calculateConstraintFunctionGradient(), getFirstOrderResults(), getJacobianSparsityPattern(), getSecondOrderResults(), getSparseJacobianFromColumnMajor(), getSparseJacobianFromRowMajor(), and ~OSInstance().
int* OSInstance::m_miJacNumConTerms [private]
m_miJacNumConTerms holds a int array of the number of constant terms (gradient does not change) for the Jacobian matrix in sparse form (row major).
Definition at line 942 of file OSInstance.h.
Referenced by getFirstOrderResults(), getJacobianSparsityPattern(), getSecondOrderResults(), getSparseJacobianFromColumnMajor(), getSparseJacobianFromRowMajor(), and ~OSInstance().
SparseJacobianMatrix* OSInstance::m_sparseJacMatrix [private]
m_sparseJacMatrix is the Jacobian matrix stored in sparse matrix format
Definition at line 947 of file OSInstance.h.
Referenced by calculateAllConstraintFunctionGradients(), calculateFunctionValue(), getFirstOrderResults(), getJacobianSparsityPattern(), getSecondOrderResults(), getZeroOrderResults(), and ~OSInstance().
int OSInstance::m_iHighestTaylorCoeffOrder [private]
m_iHighestTaylorCoeffOrder is the order of highest calculated Taylor coefficient
Definition at line 953 of file OSInstance.h.
Referenced by createCppADFun(), forwardAD(), and reverseAD().
QuadraticTerms* OSInstance::m_quadraticTerms [private]
m_quadraticTerms the data structure for all the quadratic terms in the instance.
` (rowIdx, varOneIdx, varTwoIdx, coef)
Definition at line 959 of file OSInstance.h.
Referenced by addQTermsToExressionTree(), getQuadraticTerms(), and ~OSInstance().
bool OSInstance::m_bQTermsAdded [private]
m_bQTermsAdded is true if we add the quadratic terms to the expression tree
Definition at line 963 of file OSInstance.h.
Referenced by addQTermsToExressionTree().
unsigned int OSInstance::m_iNumberOfNonlinearVariables [private]
m_iNumberOfNonlinearVariables is the number of variables that appear in a nonlinear expression.
Definition at line 969 of file OSInstance.h.
Referenced by getAllNonlinearVariablesIndexMap(), getFirstOrderResults(), getLagrangianHessianSparsityPattern(), getSecondOrderResults(), and initForAlgDiff().
bool OSInstance::m_bProcessNonlinearExpressions [private]
m_bProcessNonlinearExpressions holds whether the nonlinear expressions are processed.
Definition at line 974 of file OSInstance.h.
int OSInstance::m_iNonlinearExpressionNumber [private]
m_iNonlinearExpressionNumber holds the number of nonlinear expressions.
Definition at line 979 of file OSInstance.h.
Referenced by addQTermsToExressionTree(), and getNumberOfNonlinearExpressions().
int* OSInstance::m_miNonlinearExpressionIndexes [private]
m_miNonlinearExpressionIndexes holds an integer array of nonlinear expression indexes, negative indexes correspond to objectives.
Definition at line 985 of file OSInstance.h.
bool OSInstance::m_bProcessExpressionTrees [private]
m_bProcessExpressionTrees is true if the expression trees have been processed.
Definition at line 990 of file OSInstance.h.
Referenced by addQTermsToExressionTree(), duplicateExpressionTreesMap(), getAllNonlinearExpressionTrees(), getNonlinearExpressionTree(), getNonlinearExpressionTreeInPostfix(), getNonlinearExpressionTreeInPrefix(), getNumberOfNonlinearConstraints(), getNumberOfNonlinearObjectives(), initializeNonLinearStructures(), and ~OSInstance().
bool OSInstance::m_bProcessExpressionTreesMod [private]
m_bProcessExpressionTreesMod is true if the modified expression trees have been processed.
Definition at line 995 of file OSInstance.h.
Referenced by getAllNonlinearExpressionTreesMod(), getNonlinearExpressionTreeMod(), getNonlinearExpressionTreeModInPostfix(), and getNonlinearExpressionTreeModInPrefix().
std::map<int, OSExpressionTree*> OSInstance::m_mapExpressionTrees [private]
m_mapExpressionTrees holds a hash map of expression tree pointers, with the key being the row index and value being the expression tree representing the nonlinear expression of that row.
Definition at line 1001 of file OSInstance.h.
Referenced by addQTermsToExressionTree(), duplicateExpressionTreesMap(), getAllNonlinearExpressionTrees(), getNonlinearExpressionTree(), getNonlinearExpressionTreeInPostfix(), getNonlinearExpressionTreeInPrefix(), and ~OSInstance().
std::map<int, int> OSInstance::m_mapCppADFunRangeIndex [private]
Definition at line 1005 of file OSInstance.h.
Referenced by createCppADFun(), and getZeroOrderResults().
OSExpressionTree* OSInstance::m_LagrangianExpTree [private]
m_LagrangianExpTree is an OSExpressionTree object that is the expression tree for the Lagrangian function.
Definition at line 1011 of file OSInstance.h.
Referenced by getLagrangianExpTree(), and ~OSInstance().
bool OSInstance::m_bLagrangianExpTreeCreated [private]
m_bLagrangianHessionCreated is true if a Lagrangian function for the Hessian has been created
Definition at line 1016 of file OSInstance.h.
Referenced by getLagrangianExpTree(), and ~OSInstance().
SparseHessianMatrix* OSInstance::m_LagrangianSparseHessian [private]
m_LagrangianSparseHessian is the Hessian Matrix of the Lagrangian function in sparse format
Definition at line 1021 of file OSInstance.h.
Referenced by calculateHessian(), calculateLagrangianHessian(), getLagrangianHessianSparsityPattern(), getSecondOrderResults(), and ~OSInstance().
bool OSInstance::m_bLagrangianSparseHessianCreated [private]
m_bLagrangianSparseHessianCreated is true if the sparse Hessian Matrix for the Lagrangian was created
Definition at line 1027 of file OSInstance.h.
Referenced by getLagrangianHessianSparsityPattern(), and ~OSInstance().
std::map<int, int> OSInstance::m_mapAllNonlinearVariablesIndex [private]
m_mapAllNonlinearVariablesIndexMap is a map of the variables in the Lagrangian function
Definition at line 1032 of file OSInstance.h.
Referenced by createCppADFun(), getAllNonlinearVariablesIndexMap(), getFirstOrderResults(), getIterateResults(), and getLagrangianHessianSparsityPattern().
int* OSInstance::m_miNonLinearVarsReverseMap [private]
m_miNonLinearVarsReverseMap maps the nonlinear variable number back into the original variable space
Definition at line 1037 of file OSInstance.h.
Referenced by getAllNonlinearVariablesIndexMap(), getFirstOrderResults(), getSecondOrderResults(), and ~OSInstance().
bool OSInstance::m_bAllNonlinearVariablesIndex [private]
m_bAllNonlinearVariablesIndexMap is true if the map of the variables in the Lagrangian function has been constructed
Definition at line 1043 of file OSInstance.h.
Referenced by getAllNonlinearVariablesIndexMap().
std::map<int, OSExpressionTree*> OSInstance::m_mapExpressionTreesMod [private]
m_mapExpressionTreesMod holds a map of expression trees, with the key being the row index and value being the expression tree representing a modification of the nonlinear expression of that row.
We incorporate the linear and quadratic term for a variable into the corresponding expression tree before gradient and Hessian calculations
Definition at line 1051 of file OSInstance.h.
Referenced by addQTermsToExressionTree(), calculateFunctionValue(), createCppADFun(), duplicateExpressionTreesMap(), getAllNonlinearExpressionTreesMod(), getAllNonlinearVariablesIndexMap(), getFirstOrderResults(), getIterateResults(), getLagrangianExpTree(), getLagrangianHessianSparsityPattern(), getNonlinearExpressionTreeMod(), getNonlinearExpressionTreeModInPostfix(), getNonlinearExpressionTreeModInPrefix(), getSecondOrderResults(), getSparseJacobianFromColumnMajor(), getSparseJacobianFromRowMajor(), getZeroOrderResults(), initForAlgDiff(), initializeNonLinearStructures(), and ~OSInstance().
bool OSInstance::m_bCppADFunIsCreated [private]
m_bCppADFunIsCreated is true if we have created the OSInstanc CppAD Function
Definition at line 1057 of file OSInstance.h.
Referenced by createCppADFun(), forwardAD(), getIterateResults(), getLagrangianHessianSparsityPattern(), and ~OSInstance().
bool OSInstance::m_bCppADTapesBuilt [private]
is true if a CppAD Expresion Tree has been built for each row and objective with a nonlinear expression.
Definition at line 1063 of file OSInstance.h.
bool OSInstance::m_bCppADMustReTape [private]
is true if a CppAD Expresion Tree has an expression that can change depending on the value of the input, e.g.
an if statement -- false by default
Definition at line 1069 of file OSInstance.h.
Referenced by getIterateResults(), getLagrangianHessianSparsityPattern(), and initForAlgDiff().
bool OSInstance::m_bDuplicateExpressionTreesMap [private]
m_bDuplicateExpressionTreeMap is true if m_mapExpressionTrees was duplicated.
Definition at line 1074 of file OSInstance.h.
Referenced by duplicateExpressionTreesMap(), initializeNonLinearStructures(), and ~OSInstance().
bool OSInstance::m_bNonLinearStructuresInitialized [private]
m_bNonLinearStructuresInitialized is true if initializeNonLinearStructures() has been called.
Definition at line 1079 of file OSInstance.h.
Referenced by getAllNonlinearExpressionTreesMod(), getJacobianSparsityPattern(), initializeNonLinearStructures(), and ~OSInstance().
bool OSInstance::m_bSparseJacobianCalculated [private]
m_bSparseJacobianCalculated is true if getJacobianSparsityPattern() has been called.
Definition at line 1084 of file OSInstance.h.
Referenced by calculateFunctionValue(), getJacobianSparsityPattern(), getLagrangianExpTree(), initForAlgDiff(), and ~OSInstance().
std::map<int, std::vector<OSnLNode*> > OSInstance::m_mapExpressionTreesInPostfix [private]
m_mapExpressionTrees holds a hash map of expression trees in postfix format, with the key being the row index and value being the expression tree representing the nonlinear expression of that row.
Definition at line 1090 of file OSInstance.h.
int OSInstance::m_iHighestOrderEvaluated [private]
m_iHighestOrderEvaluated is the highest order derivative of the current iterate
Definition at line 1097 of file OSInstance.h.
Referenced by calculateAllConstraintFunctionGradients(), calculateAllConstraintFunctionValues(), calculateAllObjectiveFunctionGradients(), calculateAllObjectiveFunctionValues(), calculateConstraintFunctionGradient(), calculateHessian(), calculateLagrangianHessian(), calculateObjectiveFunctionGradient(), forwardAD(), getIterateResults(), and reverseAD().
double** OSInstance::m_mmdObjGradient [private]
m_mdObjGradient holds an array of pointers, each pointer points to gradient of each objective function
Definition at line 1103 of file OSInstance.h.
Referenced by calculateAllObjectiveFunctionGradients(), calculateObjectiveFunctionGradient(), getFirstOrderResults(), getSecondOrderResults(), initObjGradients(), and ~OSInstance().
CppAD::vector< AD<double> > OSInstance::m_vX [private]
m_vX is a vector of CppAD indpendent variables.
Definition at line 1110 of file OSInstance.h.
std::vector<double> OSInstance::m_vdX [private]
m_vdX is a vector of primal variables at each iteration
Definition at line 1116 of file OSInstance.h.
Referenced by getIterateResults(), and getZeroOrderResults().
std::vector<double> OSInstance::m_vdYval [private]
m_vdYval is a vector of function values
Definition at line 1122 of file OSInstance.h.
Referenced by getZeroOrderResults().
std::vector<bool> OSInstance::m_vbLagHessNonz [private]
m_vbLagHessNonz is a boolean vector holding the nonzero pattern of the Lagrangian of the Hessian
Definition at line 1129 of file OSInstance.h.
Referenced by getLagrangianHessianSparsityPattern(), and getSecondOrderResults().
std::vector<double> OSInstance::m_vdYjacval [private]
m_vdYval is a vector equal to a column or row of the Jacobian
Definition at line 1135 of file OSInstance.h.
Referenced by getFirstOrderResults(), and getSecondOrderResults().
std::vector<double> OSInstance::m_vdw [private]
m_vdYval is a vector of derivatives -- output from a reverse sweep
Definition at line 1141 of file OSInstance.h.
Referenced by getSecondOrderResults().
std::vector<double> OSInstance::m_vdLambda [private]
m_vdYval is a vector of Lagrange multipliers
Definition at line 1147 of file OSInstance.h.
Referenced by getSecondOrderResults().
std::vector<double> OSInstance::m_vdDomainUnitVec [private]
m_vdDomainUnitVec is a unit vector in the domain space
Definition at line 1154 of file OSInstance.h.
Referenced by getFirstOrderResults(), getSecondOrderResults(), and initForAlgDiff().
std::vector<double> OSInstance::m_vdRangeUnitVec [private]
m_vdRangeUnitVec is a unit vector in the range space
Definition at line 1160 of file OSInstance.h.
Referenced by getFirstOrderResults(), and initForAlgDiff().
bool OSInstance::m_bProcessTimeDomain [private]
m_bProcessTimeDomain holds whether the time domain has been processed.
Definition at line 1166 of file OSInstance.h.
bool OSInstance::m_bProcessTimeStages [private]
m_bProcessTimeStages holds whether the time stages have been processed.
Definition at line 1171 of file OSInstance.h.
bool OSInstance::m_bProcessTimeInterval [private]
m_bProcessTimeInterval holds whether a time interval has been processed.
Definition at line 1176 of file OSInstance.h.
bool OSInstance::m_bFiniteTimeStages [private]
m_bFiniteTimeStages holds whether the time domain has the form of finite (discrete) stages.
Definition at line 1181 of file OSInstance.h.
int OSInstance::m_iNumberOfTimeStages [private]
m_iNumberOfTimeStages holds the number of discrete stages
Definition at line 1186 of file OSInstance.h.
CppAD::ADFun<double>* OSInstance::Fad
F is a CppAD function the range space is the objective + constraints functions, x is the domeain space.
Definition at line 2107 of file OSInstance.h.
Referenced by createCppADFun(), and ~OSInstance().
bool OSInstance::bUseExpTreeForFunEval
bUseExpTreeForFunEval is set to true if you wish to use the OS Expression Tree for function evaluations instead of AD -- false by default.
Definition at line 2240 of file OSInstance.h.
Referenced by IpoptProblem::get_nlp_info(), getIterateResults(), KnitroProblem::loadProblemIntoKnitro(), and main().
The documentation for this class was generated from the following files:
/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSCommonInterfaces/OSInstance.h
/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSCommonInterfaces/OSInstance.cpp