OSnLNodeSum Class Reference
OSnLNodeSum Class Reference
The OSnLNodeSum Class.
#include <OSnLNode.h>
Public Member Functions
OSnLNodeSum ()
default constructor.
~OSnLNodeSum ()
default destructor.
virtual double calculateFunction (double *x)
virtual OSnLNode * cloneOSnLNode ()
virtual AD< double > constructCppADTape (std::map< int, int > *cppADIdx, CppAD::vector< AD< double > > *XAD)
The implementation of the virtual functions.
Detailed Description
The OSnLNodeSum Class.
Author:
Robert Fourer, Jun Ma, Kipp Martin,
Version:
1.0, 10/05/2005
Since:
OS1.0
Remarks:
The in-memory representation of the OSnL element <sum>
Definition at line 311 of file OSnLNode.h.
Constructor & Destructor Documentation
OSnLNodeSum::OSnLNodeSum ()
default constructor.
Definition at line 443 of file OSnLNode.cpp.
References OSnLNode::inodeInt, OSnLNode::inodeType, OSnLNode::inumberOfChildren, and OSnLNode::snodeName.
Referenced by cloneOSnLNode().
OSnLNodeSum::~OSnLNodeSum ()
default destructor.
Definition at line 451 of file OSnLNode.cpp.
References OSnLNode::inumberOfChildren, and OSnLNode::m_mChildren.
Member Function Documentation
double OSnLNodeSum::calculateFunction (double * x) [virtual]
Calculate the function value given the current variable values. This is an abstract method which is required to be implemented by the concrete operator nodes that derive or extend from this OSnLNode class.
Parameters:
x holds the values of the variables in a double array.
Returns:
the function value given the current variable values.
Implements OSnLNode.
Definition at line 465 of file OSnLNode.cpp.
References OSnLNode::calculateFunction(), OSnLNode::inumberOfChildren, OSnLNode::m_dFunctionValue, and OSnLNode::m_mChildren.
OSnLNode * OSnLNodeSum::cloneOSnLNode () [virtual]
Create or clone a node of this type. This is an abstract method which is required to be implemented by the concrete operator nodes that derive or extend from this OSnLNode class.
Parameters:
x holds the values of the variables in a double array.
Returns:
the function value given the current variable values.
Implements OSnLNode.
Definition at line 484 of file OSnLNode.cpp.
References OSnLNodeSum().
double OSnLNodeSum::constructCppADTape (std::map< int, int > * cppADIdx, CppAD::vector< AD< double > > * XAD) [virtual]
The implementation of the virtual functions.
Returns:
a AD<double>.
Implements OSnLNode.
Definition at line 475 of file OSnLNode.cpp.
References OSnLNode::constructCppADTape(), OSnLNode::inumberOfChildren, OSnLNode::m_CppADTape, and OSnLNode::m_mChildren.
The documentation for this class was generated from the following files:
/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSCommonInterfaces/OSnLNode.h
/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSCommonInterfaces/OSnLNode.cpp