OSnLNodeMax Class Reference
OSnLNodeMax Class Reference
The OSnLNodeMax Class.
#include <OSnLNode.h>
Public Member Functions
OSnLNodeMax ()
default constructor.
~OSnLNodeMax ()
default destructor.
virtual double calculateFunction (double *x)
virtual OSnLNode * cloneOSnLNode ()
virtual AD< double > constructCppADTape (std::map< int, int > *cppADIdx, CppAD::vector< AD< double > > *XAD)
The implementation of the virtual functions.
Detailed Description
The OSnLNodeMax Class.
Author:
Robert Fourer, Jun Ma, Kipp Martin,
Version:
1.0, 10/05/2005
Since:
OS1.0
Remarks:
The in-memory representation of the OSnL element <max>
Definition at line 357 of file OSnLNode.h.
Constructor & Destructor Documentation
OSnLNodeMax::OSnLNodeMax ()
default constructor.
Definition at line 554 of file OSnLNode.cpp.
References OSnLNode::inodeInt, OSnLNode::inodeType, OSnLNode::inumberOfChildren, and OSnLNode::snodeName.
Referenced by cloneOSnLNode().
OSnLNodeMax::~OSnLNodeMax ()
default destructor.
Definition at line 562 of file OSnLNode.cpp.
References OSnLNode::inumberOfChildren, and OSnLNode::m_mChildren.
Member Function Documentation
double OSnLNodeMax::calculateFunction (double * x) [virtual]
Calculate the function value given the current variable values. This is an abstract method which is required to be implemented by the concrete operator nodes that derive or extend from this OSnLNode class.
Parameters:
x holds the values of the variables in a double array.
Returns:
the function value given the current variable values.
Implements OSnLNode.
Definition at line 576 of file OSnLNode.cpp.
References OSnLNode::calculateFunction(), OSnLNode::inumberOfChildren, OSnLNode::m_dFunctionValue, and OSnLNode::m_mChildren.
OSnLNode * OSnLNodeMax::cloneOSnLNode () [virtual]
Create or clone a node of this type. This is an abstract method which is required to be implemented by the concrete operator nodes that derive or extend from this OSnLNode class.
Parameters:
x holds the values of the variables in a double array.
Returns:
the function value given the current variable values.
Implements OSnLNode.
Definition at line 601 of file OSnLNode.cpp.
References OSnLNodeMax().
double OSnLNodeMax::constructCppADTape (std::map< int, int > * cppADIdx, CppAD::vector< AD< double > > * XAD) [virtual]
The implementation of the virtual functions.
Returns:
a AD<double>.
Implements OSnLNode.
Definition at line 589 of file OSnLNode.cpp.
References ErrorClass::errormsg, and OSnLNode::m_CppADTape.
The documentation for this class was generated from the following files:
/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSCommonInterfaces/OSnLNode.h
/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSCommonInterfaces/OSnLNode.cpp