OSnLNodePlus Class Reference
OSnLNodePlus Class Reference
The OSnLNodePlus Class.
#include <OSnLNode.h>
Public Member Functions
OSnLNodePlus ()
default constructor.
~OSnLNodePlus ()
default destructor.
virtual double calculateFunction (double *x)
The implementation of the virtual functions.
virtual AD< double > constructCppADTape (std::map< int, int > *cppADIdx, CppAD::vector< AD< double > > *XAD)
The implementation of the virtual functions.
virtual OSnLNode * cloneOSnLNode ()
Detailed Description
The OSnLNodePlus Class.
Author:
Robert Fourer, Jun Ma, Kipp Martin,
Version:
1.0, 10/05/2005
Since:
OS1.0
Remarks:
The in-memory representation of the OSnL element <plus>
Definition at line 267 of file OSnLNode.h.
Constructor & Destructor Documentation
OSnLNodePlus::OSnLNodePlus ()
default constructor.
Definition at line 399 of file OSnLNode.cpp.
References OSnLNode::inodeInt, OSnLNode::inodeType, OSnLNode::inumberOfChildren, OSnLNode::m_mChildren, and OSnLNode::snodeName.
Referenced by cloneOSnLNode().
OSnLNodePlus::~OSnLNodePlus ()
default destructor.
Definition at line 410 of file OSnLNode.cpp.
References OSnLNode::inumberOfChildren, and OSnLNode::m_mChildren.
Member Function Documentation
double OSnLNodePlus::calculateFunction (double * x) [virtual]
The implementation of the virtual functions.
Returns:
a double.
Implements OSnLNode.
Definition at line 423 of file OSnLNode.cpp.
References OSnLNode::calculateFunction(), OSnLNode::m_dFunctionValue, and OSnLNode::m_mChildren.
double OSnLNodePlus::constructCppADTape (std::map< int, int > * cppADIdx, CppAD::vector< AD< double > > * XAD) [virtual]
The implementation of the virtual functions.
Returns:
a AD<double>.
Implements OSnLNode.
Definition at line 429 of file OSnLNode.cpp.
References OSnLNode::constructCppADTape(), OSnLNode::m_CppADTape, and OSnLNode::m_mChildren.
OSnLNode * OSnLNodePlus::cloneOSnLNode () [virtual]
Create or clone a node of this type. This is an abstract method which is required to be implemented by the concrete operator nodes that derive or extend from this OSnLNode class.
Parameters:
x holds the values of the variables in a double array.
Returns:
the function value given the current variable values.
Implements OSnLNode.
Definition at line 435 of file OSnLNode.cpp.
References OSnLNodePlus().
The documentation for this class was generated from the following files:
/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSCommonInterfaces/OSnLNode.h
/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSCommonInterfaces/OSnLNode.cpp