IpoptSolver Class Reference
IpoptSolver Class Reference
The IpoptSolver class solves problems using Ipopt.
#include <OSIpoptSolver.h>
Public Member Functions
IpoptSolver ()
the IpoptSolver class constructor
~IpoptSolver ()
the IpoptSolver class destructor
virtual void solve () throw (ErrorClass)
solve results in an instance being read into the Ipopt data structrues and optimized
virtual void buildSolverInstance () throw (ErrorClass)
buildSolverInstance is a virtual function -- the actual solvers will implement their own solve method -- the solver instance is the instance the individual solver sees in its api
void dataEchoCheck ()
use this for debugging, print out the instance that the solver thinks it has and compare this with the OSiL file
Public Attributes
SmartPtr< TNLP > nlp
SmartPtr
< IpoptApplication > app
OSiLReader * m_osilreader
m_osilreader is an OSiLReader object used to create an osinstance from an osil string if needed
Private Attributes
OSrLWriter * osrlwriter
std::string ipoptErrorMsg
Detailed Description
The IpoptSolver class solves problems using Ipopt.
Author:
Robert Fourer, Jun Ma, Kipp Martin
Version:
1.0, 03/14/2004
Since:
OS 1.0
Remarks:
this class takes an OSiL instance and optimizes it using the COIN-OR Ipopt solver
Definition at line 190 of file OSIpoptSolver.h.
Constructor & Destructor Documentation
IpoptSolver::IpoptSolver ()
the IpoptSolver class constructor
Definition at line 30 of file OSIpoptSolver.cpp.
References ipoptErrorMsg, m_osilreader, DefaultSolver::osresult, and osrlwriter.
IpoptSolver::~IpoptSolver ()
the IpoptSolver class destructor
Definition at line 38 of file OSIpoptSolver.cpp.
References m_osilreader, DefaultSolver::osresult, and osrlwriter.
Member Function Documentation
void IpoptSolver::solve () throw (ErrorClass) [virtual]
solve results in an instance being read into the Ipopt data structrues and optimized
Implements DefaultSolver.
Definition at line 504 of file OSIpoptSolver.cpp.
References app, buildSolverInstance(), ErrorClass::errormsg, OSInstance::getNumberOfNonlinearExpressions(), OSInstance::getNumberOfQuadraticTerms(), OSInstance::getObjectiveNumber(), OSInstance::getVariableNumber(), OSInstance::instanceData, ipoptErrorMsg, Objective::maxOrMin, nlp, Objectives::obj, InstanceData::objectives, DefaultSolver::osinstance, DefaultSolver::osresult, DefaultSolver::osrl, osrlwriter, OSResult::setGeneralMessage(), OSResult::setGeneralStatusType(), and OSrLWriter::writeOSrL().
Referenced by main(), and OSMatlab::solve().
void IpoptSolver::buildSolverInstance () throw (ErrorClass) [virtual]
buildSolverInstance is a virtual function -- the actual solvers will implement their own solve method -- the solver instance is the instance the individual solver sees in its api
Implements DefaultSolver.
Definition at line 480 of file OSIpoptSolver.cpp.
References app, DefaultSolver::bCallbuildSolverInstance, ErrorClass::errormsg, m_osilreader, nlp, DefaultSolver::osil, DefaultSolver::osinstance, DefaultSolver::osresult, DefaultSolver::osrl, osrlwriter, OSiLReader::readOSiL(), OSResult::setGeneralMessage(), OSResult::setGeneralStatusType(), and OSrLWriter::writeOSrL().
Referenced by main(), and solve().
void IpoptSolver::dataEchoCheck ()
use this for debugging, print out the instance that the solver thinks it has and compare this with the OSiL file
Definition at line 557 of file OSIpoptSolver.cpp.
References QuadraticTerms::coefficients, OSInstance::getConstraintLowerBounds(), OSInstance::getConstraintNames(), OSInstance::getConstraintNumber(), OSInstance::getConstraintUpperBounds(), OSInstance::getDenseObjectiveCoefficients(), OSInstance::getInstanceDescription(), OSInstance::getInstanceName(), OSInstance::getInstanceSource(), OSInstance::getLinearConstraintCoefficientNumber(), OSInstance::getLinearConstraintCoefficientsInColumnMajor(), OSInstance::getNumberOfQuadraticTerms(), OSInstance::getObjectiveMaxOrMins(), OSInstance::getQuadraticTerms(), OSInstance::getVariableLowerBounds(), OSInstance::getVariableNames(), OSInstance::getVariableNumber(), OSInstance::getVariableTypes(), OSInstance::getVariableUpperBounds(), SparseMatrix::indexes, OSInstance::instanceData, Objectives::numberOfObjectives, Objectives::obj, InstanceData::objectives, DefaultSolver::osinstance, QuadraticTerms::rowIndexes, SparseMatrix::starts, SparseMatrix::values, QuadraticTerms::varOneIndexes, and QuadraticTerms::varTwoIndexes.
Member Data Documentation
SmartPtr<TNLP> IpoptSolver::nlp
Definition at line 201 of file OSIpoptSolver.h.
Referenced by buildSolverInstance(), and solve().
SmartPtr<IpoptApplication> IpoptSolver::app
Definition at line 203 of file OSIpoptSolver.h.
Referenced by buildSolverInstance(), and solve().
OSiLReader* IpoptSolver::m_osilreader
m_osilreader is an OSiLReader object used to create an osinstance from an osil string if needed
Definition at line 227 of file OSIpoptSolver.h.
Referenced by buildSolverInstance(), IpoptSolver(), and ~IpoptSolver().
OSrLWriter* IpoptSolver::osrlwriter [private]
Definition at line 231 of file OSIpoptSolver.h.
Referenced by buildSolverInstance(), IpoptSolver(), solve(), and ~IpoptSolver().
std::string IpoptSolver::ipoptErrorMsg [private]
Definition at line 249 of file OSIpoptSolver.h.
Referenced by IpoptSolver(), and solve().
The documentation for this class was generated from the following files:
/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSSolverInterfaces/OSIpoptSolver.h
/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSSolverInterfaces/OSIpoptSolver.cpp