OSrLReader Class Reference
OSrLReader Class Reference
The OSrLReader Class.
#include <OSrLReader.h>
Public Member Functions
OSrLReader ()
OSrL class constructor.
~OSrLReader ()
OSrL class destructor.
OSResult * readOSrL (const std::string &posrl) throw (ErrorClass)
Get an OSResult object from an OSrL string.
Private Attributes
OSResult * m_osresult
m_osreslut is the OSResult object returned by the OSrLReader
OSrLParserData * m_parserData
m_parerData is the object used in the parser to temporarily store data
Detailed Description
The OSrLReader Class.
Author:
Robert Fourer, Jun Ma, Kipp Martin
Version:
1.0, 03/14/2004
Since:
OS 1.0
Remarks:
A class for parsing an OSrL string and creating an OSResult object from the string.
Definition at line 41 of file OSrLReader.h.
Constructor & Destructor Documentation
OSrLReader::OSrLReader ()
OSrL class constructor.
Definition at line 28 of file OSrLReader.cpp.
References m_osresult, m_parserData, osrllex_init(), osrlset_extra(), and OSrLParserData::scanner.
OSrLReader::~OSrLReader ()
OSrL class destructor.
Definition at line 36 of file OSrLReader.cpp.
References m_osresult, m_parserData, osrllex_destroy(), and OSrLParserData::scanner.
Member Function Documentation
OSResult * OSrLReader::readOSrL (const std::string & posrl) throw (ErrorClass)
Get an OSResult object from an OSrL string.
Parameters:
osrl an OSrL string.
Returns:
the OSResult object corresponding to the OSrL string.
Definition at line 48 of file OSrLReader.cpp.
References ErrorClass::errormsg, m_osresult, m_parserData, and yygetOSResult().
Referenced by main().
Member Data Documentation
OSResult* OSrLReader::m_osresult [private]
m_osreslut is the OSResult object returned by the OSrLReader
Definition at line 71 of file OSrLReader.h.
Referenced by OSrLReader(), readOSrL(), and ~OSrLReader().
OSrLParserData* OSrLReader::m_parserData [private]
m_parerData is the object used in the parser to temporarily store data
Definition at line 76 of file OSrLReader.h.
Referenced by OSrLReader(), readOSrL(), and ~OSrLReader().
The documentation for this class was generated from the following files:
/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSCommonInterfaces/OSrLReader.h
/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSCommonInterfaces/OSrLReader.cpp