/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSParsers/parseosss.cpp File Reference
/Users/kmartin/Documents/files/code/cpp/OScpp/COIN-OS/OS/src/OSParsers/parseosss.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
#include <iostream>
#include "OSConfig.h"
#include "ErrorClass.h"
#include <sstream>
#include "osOptionsStruc.h"
#include <unistd.h>
Classes
struct yy_buffer_state
struct yy_trans_info
struct yyguts_t
Defines
#define YY_INT_ALIGNED short int
#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 33
#define FLEX_BETA
#define INT8_MIN (-128)
#define INT16_MIN (-32767-1)
#define INT32_MIN (-2147483647-1)
#define INT8_MAX (127)
#define INT16_MAX (32767)
#define INT32_MAX (2147483647)
#define UINT8_MAX (255U)
#define UINT16_MAX (65535U)
#define UINT32_MAX (4294967295U)
#define yyconst
#define YY_NULL 0
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r
#define BEGIN yyg->yy_start = 1 + 2 *
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
#define YY_NEW_FILE osssrestart(yyin ,yyscanner)
#define YY_END_OF_BUFFER_CHAR 0
#define YY_BUF_SIZE 16384
#define YY_STATE_BUF_SIZE ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))
#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
#define YY_LESS_LINENO(n)
#define yyless(n)
#define unput(c) yyunput(c, yyg->yytext_ptr , yyscanner)
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
#define YY_BUFFER_EOF_PENDING 2
#define YY_CURRENT_BUFFER
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]
#define YY_FLUSH_BUFFER osss_flush_buffer(YY_CURRENT_BUFFER ,yyscanner)
#define yy_new_buffer osss_create_buffer
#define yy_set_interactive(is_interactive)
#define yy_set_bol(at_bol)
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)
#define ossswrap(n) 1
#define YY_SKIP_YYWRAP
#define yytext_ptr yytext_r
#define YY_DO_BEFORE_ACTION
#define YY_NUM_RULES 16
#define YY_END_OF_BUFFER 17
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#define PARSERDEBUG
#define YY_PRINT printf("%s", yytext);
#define YY_EXTRA_TYPE struct osOptionsStruc*
#define INITIAL 0
#define YY_READ_BUF_SIZE 8192
#define ECHO (void) fwrite(yytext, yyleng, 1, yyout)
#define YY_INPUT(buf, result, max_size)
#define yyterminate() return YY_NULL
#define YY_START_STACK_INCR 25
#define YY_FATAL_ERROR(msg) yy_fatal_error(msg , yyscanner)
#define YY_DECL_IS_OURS 1
#define YY_DECL int ossslex (yyscan_t yyscanner)
#define YY_BREAK break;
#define YY_RULE_SETUP YY_USER_ACTION
#define YY_EXIT_FAILURE 2
#define yyless(n)
#define YYTABLES_NAME "yytables"
Typedefs
typedef signed char flex_int8_t
typedef short int flex_int16_t
typedef int flex_int32_t
typedef unsigned char flex_uint8_t
typedef unsigned
short int flex_uint16_t
typedef unsigned int flex_uint32_t
typedef void * yyscan_t
typedef struct
yy_buffer_state * YY_BUFFER_STATE
typedef unsigned int yy_size_t
typedef unsigned char YY_CHAR
typedef int yy_state_type
Functions
int ossslex_init (yyscan_t *scanner)
void osssrestart (FILE *input_file, yyscan_t yyscanner)
void osss_switch_to_buffer (YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
YY_BUFFER_STATE osss_create_buffer (FILE *file, int size, yyscan_t yyscanner)
void osss_delete_buffer (YY_BUFFER_STATE b, yyscan_t yyscanner)
void osss_flush_buffer (YY_BUFFER_STATE b, yyscan_t yyscanner)
Discard all buffered characters.
void ossspush_buffer_state (YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
Pushes the new state onto the stack.
void ossspop_buffer_state (yyscan_t yyscanner)
Removes and deletes the top of the stack, if present.
static void osssensure_buffer_stack (yyscan_t yyscanner)
static void osss_load_buffer_state (yyscan_t yyscanner)
static void osss_init_buffer (YY_BUFFER_STATE b, FILE *file, yyscan_t yyscanner)
The main scanner function which does all the work.
YY_BUFFER_STATE osss_scan_buffer (char *base, yy_size_t size, yyscan_t yyscanner)
Setup the input buffer state to scan directly from a user-specified character buffer.
YY_BUFFER_STATE osss_scan_string (yyconst char *yystr, yyscan_t yyscanner)
Setup the input buffer state to scan a string.
YY_BUFFER_STATE osss_scan_bytes (yyconst char *yybytes, int _yybytes_len, yyscan_t yyscanner)
Setup the input buffer state to scan the given bytes.
void * osssalloc (yy_size_t, yyscan_t yyscanner)
void * osssrealloc (void *, yy_size_t, yyscan_t yyscanner)
void osssfree (void *, yyscan_t yyscanner)
static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
static yy_state_type yy_try_NUL_trans (yy_state_type current_state, yyscan_t yyscanner)
static int yy_get_next_buffer (yyscan_t yyscanner)
static void yy_fatal_error (yyconst char msg[], yyscan_t yyscanner)
void setyyextra (osOptionsStruc *osoptions, void *scanner)
static int yy_init_globals (yyscan_t yyscanner)
int ossslex_destroy (yyscan_t yyscanner)
int osssget_debug (yyscan_t yyscanner)
void osssset_debug (int debug_flag, yyscan_t yyscanner)
YY_EXTRA_TYPE osssget_extra (yyscan_t yyscanner)
Get the user-defined data for this scanner.
void osssset_extra (YY_EXTRA_TYPE user_defined, yyscan_t yyscanner)
Set the user-defined data.
FILE * osssget_in (yyscan_t yyscanner)
Get the input stream.
void osssset_in (FILE *in_str, yyscan_t yyscanner)
Set the input stream.
FILE * osssget_out (yyscan_t yyscanner)
Get the output stream.
void osssset_out (FILE *out_str, yyscan_t yyscanner)
int osssget_leng (yyscan_t yyscanner)
Get the length of the current token.
char * osssget_text (yyscan_t yyscanner)
Get the current token.
int osssget_lineno (yyscan_t yyscanner)
Get the current line number.
void osssset_lineno (int line_number, yyscan_t yyscanner)
Set the current line number.
static void yyunput (int c, char *buf_ptr, yyscan_t yyscanner)
static int input (yyscan_t yyscanner)
int ossslex (yyscan_t yyscanner)
static void yy_fatal_error (yyconst char *msg, yyscan_t yyscanner)
int osssget_column (yyscan_t yyscanner)
Get the current column number.
void osssset_column (int column_no, yyscan_t yyscanner)
Set the current column.
Variables
static yyconst
flex_int16_t yy_accept [170]
static yyconst
flex_int32_t yy_ec [256]
static yyconst
flex_int32_t yy_meta [34]
static yyconst
flex_int16_t yy_base [195]
static yyconst
flex_int16_t yy_def [195]
static yyconst
flex_int16_t yy_nxt [339]
static yyconst
flex_int16_t yy_chk [339]
static yyconst
flex_int32_t yy_rule_can_match_eol [17]
Define Documentation
#define YY_INT_ALIGNED short int
Definition at line 5 of file parseosss.cpp.
#define FLEX_SCANNER
Definition at line 9 of file parseosss.cpp.
#define YY_FLEX_MAJOR_VERSION 2
Definition at line 10 of file parseosss.cpp.
#define YY_FLEX_MINOR_VERSION 5
Definition at line 11 of file parseosss.cpp.
#define YY_FLEX_SUBMINOR_VERSION 33
Definition at line 12 of file parseosss.cpp.
#define FLEX_BETA
Definition at line 14 of file parseosss.cpp.
#define INT8_MIN (-128)
Definition at line 61 of file parseosss.cpp.
#define INT16_MIN (-32767-1)
Definition at line 64 of file parseosss.cpp.
#define INT32_MIN (-2147483647-1)
Definition at line 67 of file parseosss.cpp.
#define INT8_MAX (127)
Definition at line 70 of file parseosss.cpp.
#define INT16_MAX (32767)
Definition at line 73 of file parseosss.cpp.
#define INT32_MAX (2147483647)
Definition at line 76 of file parseosss.cpp.
#define UINT8_MAX (255U)
Definition at line 79 of file parseosss.cpp.
#define UINT16_MAX (65535U)
Definition at line 82 of file parseosss.cpp.
#define UINT32_MAX (4294967295U)
Definition at line 85 of file parseosss.cpp.
#define yyconst
Definition at line 107 of file parseosss.cpp.
#define YY_NULL 0
Definition at line 111 of file parseosss.cpp.
#define YY_SC_TO_UI (c) ((unsigned int) (unsigned char) c)
Definition at line 118 of file parseosss.cpp.
#define yyin yyg->yyin_r
Definition at line 128 of file parseosss.cpp.
#define yyout yyg->yyout_r
Definition at line 129 of file parseosss.cpp.
#define yyextra yyg->yyextra_r
Definition at line 130 of file parseosss.cpp.
#define yyleng yyg->yyleng_r
Definition at line 131 of file parseosss.cpp.
#define yytext yyg->yytext_r
Definition at line 132 of file parseosss.cpp.
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
Definition at line 133 of file parseosss.cpp.
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
Definition at line 134 of file parseosss.cpp.
#define yy_flex_debug yyg->yy_flex_debug_r
Definition at line 135 of file parseosss.cpp.
#define BEGIN yyg->yy_start = 1 + 2 *
Definition at line 143 of file parseosss.cpp.
#define YY_START ((yyg->yy_start - 1) / 2)
Definition at line 149 of file parseosss.cpp.
#define YYSTATE YY_START
Definition at line 150 of file parseosss.cpp.
#define YY_STATE_EOF (state) (YY_END_OF_BUFFER + state + 1)
Definition at line 153 of file parseosss.cpp.
#define YY_NEW_FILE osssrestart(yyin ,yyscanner)
Definition at line 156 of file parseosss.cpp.
#define YY_END_OF_BUFFER_CHAR 0
Definition at line 158 of file parseosss.cpp.
#define YY_BUF_SIZE 16384
Definition at line 162 of file parseosss.cpp.
#define YY_STATE_BUF_SIZE ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))
Definition at line 167 of file parseosss.cpp.
#define EOB_ACT_CONTINUE_SCAN 0
Definition at line 174 of file parseosss.cpp.
#define EOB_ACT_END_OF_FILE 1
Definition at line 175 of file parseosss.cpp.
#define EOB_ACT_LAST_MATCH 2
Definition at line 176 of file parseosss.cpp.
#define YY_LESS_LINENO (n)
Value:
do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
Definition at line 185 of file parseosss.cpp.
#define yyless (n)
Value:
do \
                { \
                /* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
                *yy_cp = yyg->yy_hold_char; \
                YY_RESTORE_YY_MORE_OFFSET \
                yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
                YY_DO_BEFORE_ACTION; /* set up yytext again */ \
                } \
        while ( 0 )
Definition at line 2048 of file parseosss.cpp.
#define unput (c) yyunput(c, yyg->yytext_ptr , yyscanner)
Definition at line 207 of file parseosss.cpp.
#define YY_BUFFER_NEW 0
Definition at line 267 of file parseosss.cpp.
#define YY_BUFFER_NORMAL 1
Definition at line 268 of file parseosss.cpp.
#define YY_BUFFER_EOF_PENDING 2
Definition at line 279 of file parseosss.cpp.
#define YY_CURRENT_BUFFER
Value:
(yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
Definition at line 290 of file parseosss.cpp.
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]
Definition at line 297 of file parseosss.cpp.
#define YY_FLUSH_BUFFER osss_flush_buffer(YY_CURRENT_BUFFER ,yyscanner)
Definition at line 311 of file parseosss.cpp.
#define yy_new_buffer osss_create_buffer
Definition at line 321 of file parseosss.cpp.
#define yy_set_interactive (is_interactive)
Value:
{ \
        if ( ! YY_CURRENT_BUFFER ){ \
        osssensure_buffer_stack (yyscanner); \
                YY_CURRENT_BUFFER_LVALUE =    \
            osss_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
        } \
        YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
        }
Definition at line 323 of file parseosss.cpp.
#define yy_set_bol (at_bol)
Value:
{ \
        if ( ! YY_CURRENT_BUFFER ){\
        osssensure_buffer_stack (yyscanner); \
                YY_CURRENT_BUFFER_LVALUE =    \
            osss_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
        } \
        YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
        }
Definition at line 333 of file parseosss.cpp.
#define YY_AT_BOL () (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)
Definition at line 343 of file parseosss.cpp.
#define ossswrap (n) 1
Definition at line 347 of file parseosss.cpp.
#define YY_SKIP_YYWRAP
Definition at line 348 of file parseosss.cpp.
#define yytext_ptr yytext_r
Definition at line 354 of file parseosss.cpp.
#define YY_DO_BEFORE_ACTION
Value:
yyg->yytext_ptr = yy_bp; \
        yyleng = (size_t) (yy_cp - yy_bp); \
        yyg->yy_hold_char = *yy_cp; \
        *yy_cp = '\0'; \
        yyg->yy_c_buf_p = yy_cp;
Definition at line 364 of file parseosss.cpp.
#define YY_NUM_RULES 16
Definition at line 371 of file parseosss.cpp.
#define YY_END_OF_BUFFER 17
Definition at line 372 of file parseosss.cpp.
#define REJECT reject_used_but_not_detected
Definition at line 584 of file parseosss.cpp.
#define yymore () yymore_used_but_not_detected
Definition at line 585 of file parseosss.cpp.
#define YY_MORE_ADJ 0
Definition at line 586 of file parseosss.cpp.
#define YY_RESTORE_YY_MORE_OFFSET
Definition at line 587 of file parseosss.cpp.
#define PARSERDEBUG
Definition at line 638 of file parseosss.cpp.
#define YY_PRINT printf("%s", yytext);
Definition at line 640 of file parseosss.cpp.
#define YY_EXTRA_TYPE struct osOptionsStruc*
Definition at line 649 of file parseosss.cpp.
#define INITIAL 0
Definition at line 682 of file parseosss.cpp.
#define YY_READ_BUF_SIZE 8192
Definition at line 795 of file parseosss.cpp.
#define ECHO (void) fwrite(yytext, yyleng, 1, yyout)
Definition at line 803 of file parseosss.cpp.
#define YY_INPUT (buf, result, max_size)
Value:
if (YY_CURRENT_BUFFER_LVALUE->yy_is_interactive) \
                { \
                int c = '*'; \
                size_t n; \
                for ( n = 0; n < max_size && \
                             (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
                        buf[n] = (char) c; \
                if ( c == '\n' ) \
                        buf[n++] = (char) c; \
                if ( c == EOF && ferror( yyin ) ) \
                        YY_FATAL_ERROR( "input in flex scanner failed" ); \
                result = n; \
                } \
        else \
                { \
                errno=0; \
                while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
                        { \
                        if( errno != EINTR) \
                                { \
                                YY_FATAL_ERROR( "input in flex scanner failed" ); \
                                break; \
                                } \
                        errno=0; \
                        clearerr(yyin); \
                        } \
                }\
\
Definition at line 810 of file parseosss.cpp.
#define yyterminate () return YY_NULL
Definition at line 847 of file parseosss.cpp.
#define YY_START_STACK_INCR 25
Definition at line 852 of file parseosss.cpp.
#define YY_FATAL_ERROR (msg) yy_fatal_error(msg , yyscanner)
Definition at line 857 of file parseosss.cpp.
#define YY_DECL_IS_OURS 1
Definition at line 866 of file parseosss.cpp.
#define YY_DECL int ossslex (yyscan_t yyscanner)
Definition at line 870 of file parseosss.cpp.
#define YY_BREAK break;
Definition at line 882 of file parseosss.cpp.
#define YY_RULE_SETUP YY_USER_ACTION
Definition at line 885 of file parseosss.cpp.
#define YY_EXIT_FAILURE 2
Definition at line 2036 of file parseosss.cpp.
#define yyless (n)
Value:
do \
                { \
                /* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
                yytext[yyleng] = yyg->yy_hold_char; \
                yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
                yyg->yy_hold_char = *yyg->yy_c_buf_p; \
                *yyg->yy_c_buf_p = '\0'; \
                yyleng = yyless_macro_arg; \
                } \
        while ( 0 )
Definition at line 2048 of file parseosss.cpp.
#define YYTABLES_NAME "yytables"
Definition at line 2345 of file parseosss.cpp.
Typedef Documentation
typedef signed char flex_int8_t
Definition at line 51 of file parseosss.cpp.
typedef short int flex_int16_t
Definition at line 52 of file parseosss.cpp.
typedef int flex_int32_t
Definition at line 53 of file parseosss.cpp.
typedef unsigned char flex_uint8_t
Definition at line 54 of file parseosss.cpp.
typedef unsigned short int flex_uint16_t
Definition at line 55 of file parseosss.cpp.
typedef unsigned int flex_uint32_t
Definition at line 56 of file parseosss.cpp.
typedef void* yyscan_t
Definition at line 123 of file parseosss.cpp.
typedef struct yy_buffer_state* YY_BUFFER_STATE
Definition at line 171 of file parseosss.cpp.
typedef unsigned int yy_size_t
Definition at line 216 of file parseosss.cpp.
typedef unsigned char YY_CHAR
Definition at line 350 of file parseosss.cpp.
typedef int yy_state_type
Definition at line 352 of file parseosss.cpp.
Function Documentation
int ossslex_init (yyscan_t * scanner)
Definition at line 2215 of file parseosss.cpp.
References osssalloc(), and yy_init_globals().
Referenced by main().
void osssrestart (FILE * input_file, yyscan_t yyscanner)
void osss_switch_to_buffer (YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
Referenced by osss_scan_buffer().
YY_BUFFER_STATE osss_create_buffer (FILE * file, int size, yyscan_t yyscanner)
void osss_delete_buffer (YY_BUFFER_STATE b, yyscan_t yyscanner)
Referenced by ossslex_destroy(), and ossspop_buffer_state().
void osss_flush_buffer (YY_BUFFER_STATE b, yyscan_t yyscanner)
Discard all buffered characters.
On the next scan, YY_INPUT will be called.
Parameters:
b the buffer state to be flushed, usually YY_CURRENT_BUFFER.
yyscanner The scanner object.
Definition at line 1828 of file parseosss.cpp.
References osss_load_buffer_state(), yy_buffer_state::yy_at_bol, yy_buffer_state::yy_buf_pos, YY_BUFFER_NEW, yy_buffer_state::yy_buffer_status, yy_buffer_state::yy_ch_buf, YY_CURRENT_BUFFER, YY_END_OF_BUFFER_CHAR, and yy_buffer_state::yy_n_chars.
Referenced by osss_init_buffer().
void ossspush_buffer_state (YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
Pushes the new state onto the stack.
The new state becomes the current state. This function will allocate the stack if necessary.
Parameters:
new_buffer The new state.
yyscanner The scanner object.
Definition at line 1858 of file parseosss.cpp.
References osss_load_buffer_state(), osssensure_buffer_stack(), yyguts_t::yy_buffer_stack_top, yyguts_t::yy_c_buf_p, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_did_buffer_switch_on_eof, yyguts_t::yy_hold_char, and yyguts_t::yy_n_chars.
void ossspop_buffer_state (yyscan_t yyscanner)
Removes and deletes the top of the stack, if present.
The next element becomes the new top.
Parameters:
yyscanner The scanner object.
Definition at line 1889 of file parseosss.cpp.
References osss_delete_buffer(), osss_load_buffer_state(), yyguts_t::yy_buffer_stack_top, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, and yyguts_t::yy_did_buffer_switch_on_eof.
Referenced by ossslex_destroy().
static void osssensure_buffer_stack (yyscan_t yyscanner) [static]
Definition at line 1909 of file parseosss.cpp.
References osssalloc(), osssrealloc(), yyguts_t::yy_buffer_stack, yyguts_t::yy_buffer_stack_max, and yyguts_t::yy_buffer_stack_top.
Referenced by ossspush_buffer_state().
static void osss_load_buffer_state (yyscan_t yyscanner) [static]
Referenced by osss_flush_buffer(), ossspop_buffer_state(), and ossspush_buffer_state().
static void osss_init_buffer (YY_BUFFER_STATE b, FILE * file, yyscan_t yyscanner) [static]
The main scanner function which does all the work.
Definition at line 1799 of file parseosss.cpp.
References osss_flush_buffer(), yy_buffer_state::yy_bs_column, yy_buffer_state::yy_bs_lineno, YY_CURRENT_BUFFER, yy_buffer_state::yy_fill_buffer, yy_buffer_state::yy_input_file, and yy_buffer_state::yy_is_interactive.
YY_BUFFER_STATE osss_scan_buffer (char * base, yy_size_t size, yyscan_t yyscanner)
Setup the input buffer state to scan directly from a user-specified character buffer.
Parameters:
base the character buffer
size the size in bytes of the character buffer
yyscanner The scanner object.
Returns:
the newly allocated buffer state object.
Definition at line 1955 of file parseosss.cpp.
References osss_switch_to_buffer(), osssalloc(), yy_buffer_state::yy_at_bol, yy_buffer_state::yy_buf_pos, yy_buffer_state::yy_buf_size, YY_BUFFER_NEW, yy_buffer_state::yy_buffer_status, yy_buffer_state::yy_ch_buf, YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, yy_buffer_state::yy_fill_buffer, yy_buffer_state::yy_input_file, yy_buffer_state::yy_is_interactive, yy_buffer_state::yy_is_our_buffer, and yy_buffer_state::yy_n_chars.
Referenced by osss_scan_bytes().
YY_BUFFER_STATE osss_scan_string (yyconst char * yystr, yyscan_t yyscanner)
Setup the input buffer state to scan a string.
The next call to ossslex() will scan from a copy of str.
Parameters:
str a NUL-terminated string to scan
yyscanner The scanner object.
Returns:
the newly allocated buffer state object.
Note:
If you want to scan bytes that may contain NUL values, then use osss_scan_bytes() instead.
Definition at line 1992 of file parseosss.cpp.
References osss_scan_bytes().
Referenced by main().
YY_BUFFER_STATE osss_scan_bytes (yyconst char * yybytes, int _yybytes_len, yyscan_t yyscanner)
Setup the input buffer state to scan the given bytes.
The next call to ossslex() will scan from a copy of bytes.
Parameters:
bytes the byte buffer to scan
len the number of bytes in the buffer pointed to by bytes.
yyscanner The scanner object.
Returns:
the newly allocated buffer state object.
Definition at line 2005 of file parseosss.cpp.
References osss_scan_buffer(), osssalloc(), YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, and yy_buffer_state::yy_is_our_buffer.
Referenced by osss_scan_string().
void * osssalloc (yy_size_t size, yyscan_t yyscanner)
Definition at line 2323 of file parseosss.cpp.
Referenced by osss_scan_buffer(), osss_scan_bytes(), osssensure_buffer_stack(), and ossslex_init().
void * osssrealloc (void * ptr, yy_size_t size, yyscan_t yyscanner)
Definition at line 2328 of file parseosss.cpp.
Referenced by osssensure_buffer_stack().
void osssfree (void * ptr, yyscan_t yyscanner)
Definition at line 2340 of file parseosss.cpp.
Referenced by ossslex_destroy().
static yy_state_type yy_get_previous_state (yyscan_t yyscanner) [static]
static yy_state_type yy_try_NUL_trans (yy_state_type current_state, yyscan_t yyscanner) [static]
static int yy_get_next_buffer (yyscan_t yyscanner) [static]
static void yy_fatal_error (yyconst char msg[], yyscan_t yyscanner) [static]
void setyyextra (osOptionsStruc * osoptions, void * scanner)
Definition at line 2351 of file parseosss.cpp.
References osssset_extra().
Referenced by main().
static int yy_init_globals (yyscan_t yyscanner) [static]
Definition at line 2236 of file parseosss.cpp.
References yyguts_t::yy_buffer_stack, yyguts_t::yy_buffer_stack_max, yyguts_t::yy_buffer_stack_top, yyguts_t::yy_c_buf_p, yyguts_t::yy_init, yyguts_t::yy_start, yyguts_t::yy_start_stack, yyguts_t::yy_start_stack_depth, yyguts_t::yy_start_stack_ptr, yyin, and yyout.
int ossslex_destroy (yyscan_t yyscanner)
Definition at line 2270 of file parseosss.cpp.
References osss_delete_buffer(), osssfree(), ossspop_buffer_state(), yyguts_t::yy_buffer_stack, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yy_init_globals(), and yyguts_t::yy_start_stack.
int osssget_debug (yyscan_t yyscanner)
Definition at line 2194 of file parseosss.cpp.
References yy_flex_debug.
void osssset_debug (int debug_flag, yyscan_t yyscanner)
Definition at line 2200 of file parseosss.cpp.
References yy_flex_debug.
YY_EXTRA_TYPE osssget_extra (yyscan_t yyscanner)
Get the user-defined data for this scanner.
Parameters:
yyscanner The scanner object.
Definition at line 2067 of file parseosss.cpp.
References yyextra.
void osssset_extra (YY_EXTRA_TYPE user_defined, yyscan_t yyscanner)
Set the user-defined data.
This data is never touched by the scanner.
Parameters:
user_defined The data to be associated with this scanner.
yyscanner The scanner object.
Definition at line 2140 of file parseosss.cpp.
References yyextra.
Referenced by setyyextra().
FILE * osssget_in (yyscan_t yyscanner)
Get the input stream.
Parameters:
yyscanner The scanner object.
Definition at line 2102 of file parseosss.cpp.
References yyin.
void osssset_in (FILE * in_str, yyscan_t yyscanner)
Set the input stream.
This does not discard the current input buffer.
Parameters:
in_str A readable stream.
yyscanner The scanner object.
See also:
osss_switch_to_buffer
Definition at line 2182 of file parseosss.cpp.
References yyin.
FILE * osssget_out (yyscan_t yyscanner)
Get the output stream.
Parameters:
yyscanner The scanner object.
Definition at line 2111 of file parseosss.cpp.
References yyout.
void osssset_out (FILE * out_str, yyscan_t yyscanner)
Definition at line 2188 of file parseosss.cpp.
References yyout.
int osssget_leng (yyscan_t yyscanner)
Get the length of the current token.
Parameters:
yyscanner The scanner object.
Definition at line 2120 of file parseosss.cpp.
References yyleng.
char * osssget_text (yyscan_t yyscanner)
Get the current token.
Parameters:
yyscanner The scanner object.
Definition at line 2130 of file parseosss.cpp.
References yytext.
int osssget_lineno (yyscan_t yyscanner)
Get the current line number.
Parameters:
yyscanner The scanner object.
Definition at line 2076 of file parseosss.cpp.
References YY_CURRENT_BUFFER, and yylineno.
void osssset_lineno (int line_number, yyscan_t yyscanner)
Set the current line number.
Parameters:
line_number
yyscanner The scanner object.
Definition at line 2150 of file parseosss.cpp.
References YY_CURRENT_BUFFER, yy_fatal_error(), and yylineno.
static void yyunput (int c, char * buf_ptr, yyscan_t yyscanner) [static]
static int input (yyscan_t yyscanner) [static]
int ossslex (yyscan_t yyscanner)
Referenced by main().
static void yy_fatal_error (yyconst char * msg, yyscan_t yyscanner) [static]
Definition at line 2039 of file parseosss.cpp.
References YY_EXIT_FAILURE.
int osssget_column (yyscan_t yyscanner)
Get the current column number.
Parameters:
yyscanner The scanner object.
Definition at line 2089 of file parseosss.cpp.
References YY_CURRENT_BUFFER, and yycolumn.
void osssset_column (int column_no, yyscan_t yyscanner)
Set the current column.
Parameters:
line_number
yyscanner The scanner object.
Definition at line 2165 of file parseosss.cpp.
References YY_CURRENT_BUFFER, yy_fatal_error(), and yycolumn.
Variable Documentation
yyconst flex_int16_t yy_accept[170] [static]
Initial value:
    {   0,
        1,    1,   17,   15,    1,    1,   15,    1,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   12,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       11,    0,   12,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   11,    0,    3,    0,    6,    0,
        0,    0,    4,    0,    0,    0,    0,    0,    0,    3,
        0,    6,    0,    0,    0,    4,    0,    0,    0,    0,
        2,    0,    0,    0,    0,    0,    0,   13,    0,   14,
        0,    2,    0,    5,    0,    0,    0,    0,    0,   13,
        0,   14,    0,    5,    0,    0,    0,    0,    0,    7,
        0,    0,    0,    0,    7,    0,    8,    0,    0,    0,
        8,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   10,    0,
        0,    0,    0,    0,    0,    0,   10,    0,    9,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0
    }
Definition at line 380 of file parseosss.cpp.
yyconst flex_int32_t yy_ec[256] [static]
Definition at line 402 of file parseosss.cpp.
yyconst flex_int32_t yy_meta[34] [static]
Initial value:
    {   0,
        1,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2
    }
Definition at line 434 of file parseosss.cpp.
yyconst flex_int16_t yy_base[195] [static]
Initial value:
    {   0,
        0,    4,  304,  305,    8,   10,    0,   14,  275,  276,
      276,  273,  276,  269,    1,  271,  271,  266,  265,   17,
        7,  265,  269,  258,  272,  279,   20,   28,  265,  264,
      263,  262,  252,  251,  253,  260,  259,   34,   36,   39,
       42,   44,   40,   47,  258,  261,  260,  257,  246,   50,
       53,   55,  305,   58,   61,  249,  242,   64,  257,  243,
      242,   67,  239,   68,  305,   70,   73,   75,   78,  241,
      237,   80,   83,  249,   86,   88,   90,   93,   94,  305,
       96,  305,  234,  237,   98,  305,   93,  103,  106,  108,
      111,  114,  233,  231,  235,  243,  116,  119,  121,  124,
      126,  305,  128,  131,  134,  229,  243,  227,  135,  305,
      137,  305,  139,  305,  142,  145,  243,  235,  146,  149,
      152,  224,  227,  154,  305,  156,  159,  231,  235,  161,
      305,  224,  164,  224,  166,  168,  231,  151,  230,  156,
      175,  216,  222,  218,  213,  217,  218,  171,  187,  231,
      216,  223,  209,  220,  203,  177,  305,  208,  305,  211,
      211,  214,  216,  212,  220,  195,  219,  208,  305,  195,
      222,  221,  197,  199,  220,  191,  190,  201,  203,  205,
      185,  184,  182,  207,  181,  209,  211,  213,   49,  215,
        6,  217,    2,  219
    }
Definition at line 442 of file parseosss.cpp.
yyconst flex_int16_t yy_def[195] [static]
Initial value:
    {   0,
      170,  170,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  171,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  172,  173,  171,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  174,
      172,  173,  169,  175,  176,  169,  169,  177,  169,  169,
      169,  169,  169,  174,  169,  178,  175,  179,  176,  169,
      169,  180,  177,  169,  169,  169,  181,  169,  178,  169,
      179,  169,  169,  169,  180,  169,  169,  182,  183,  184,
      181,  185,  169,  169,  169,  169,  186,  182,  187,  183,
      184,  169,  188,  185,  169,  169,  169,  169,  186,  169,
      187,  169,  188,  169,  189,  169,  169,  169,  190,  189,
      191,  169,  169,  190,  169,  192,  191,  169,  169,  192,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      193,  169,  169,  169,  169,  169,  169,  194,  193,  169,
      169,  169,  169,  169,  169,  194,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,    0,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169
    }
Definition at line 468 of file parseosss.cpp.
yyconst flex_int16_t yy_nxt[339] [static]
Definition at line 494 of file parseosss.cpp.
yyconst flex_int16_t yy_chk[339] [static]
Definition at line 535 of file parseosss.cpp.
yyconst flex_int32_t yy_rule_can_match_eol[17] [static]
Initial value:
    {   0,
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,     }
Definition at line 577 of file parseosss.cpp.