package org.optimizationservices.osmodeler.parser.osml;
/* Generated By:JavaCC: Do not edit this line. OSmLPreParserConstants.java */
public interface OSmLPreParserConstants {

  int EOF = 0;
  int space = 1;
  int slasht = 2;
  int slashn = 3;
  int slashr = 4;
  int gt = 5;
  int lt = 6;
  int geq = 7;
  int leq = 8;
  int operator = 9;
  int leftparen = 10;
  int rightparen = 11;
  int startCon = 12;
  int endCon = 13;
  int startConstraints = 14;
  int endConstraints = 15;
  int startvar = 16;
  int endvar = 17;
  int startvariables = 18;
  int endvariables = 19;
  int startUserfunction = 20;
  int endUserfunction = 21;
  int startUserfunctions = 22;
  int endUserfunctions = 23;
  int startmathProgram = 24;
  int endmathProgram = 25;
  int startobj = 26;
  int endobj = 27;
  int sum = 28;
  int xpathNode = 29;
  int atoken = 30;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "<operator>",
    "\"(\"",
    "\")\"",
    "\"<con\"",
    "\"</con>\"",
    "\"<constraints>\"",
    "\"</constraints>\"",
    "\"<var>\"",
    "\"</var>\"",
    "\"<variables>\"",
    "\"</variables>\"",
    "\"<userfunction\"",
    "\"</userfunction>\"",
    "\"<userfunctions>\"",
    "\"</userfunctions>\"",
    "\"<mathProgram \"",
    "\"</mathProgram>\"",
    "\"<obj>\"",
    "\"</obj>\"",
    "\"SUM\"",
    "<xpathNode>",
    "<atoken>",
  };

}
